/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const bodyStyles = null;
const imageStyles = null;
const defaultHeaderStyles = null;
const Component = () => (
	<div className={ax(["_1e0c1txw _2lx21bp4"])}>
		<img src="test.jpg" alt="" className={ax(["_1e0c1ule"])} />
		<div className={ax(["_1e0c1txw _4cvr1q9y"])}>Header</div>
	</div>
);
export default Component;
