/* .tmp-swc-css-null-literal-variables-1765439412451-a51ff4af3d0a6.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const bodyStyles = null;
const imageStyles = null;
const defaultHeaderStyles = null;
const Component = ()=>(<div className={ax([])}>
    <img src="test.jpg" alt="" className={ax([])}/>
    <div className={ax([])}>Header</div>
  </div>);
export default Component;
