/* .tmp-swc-css-null-literal-variables-1764057096377-2b90e28ea43f.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const bodyStyles = null;
const imageStyles = null;
const defaultHeaderStyles = null;
const Component = ()=>(<div className={ax([
        "_2lx21bp4 _1e0c1txw"
    ])}>
    <img src="test.jpg" alt="" className={ax([
        "_1e0c1ule"
    ])}/>
    <div className={ax([
        "_4cvr1q9y _1e0c1txw"
    ])}>Header</div>
  </div>);
export default Component;
