/* .tmp-swc-onboarding-target-keyframes-1764627628381-e83d87263d2e6.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const baseShadow = '0 0 0 2px #6554C0';
const easing = 'cubic-bezier(0.55, 0.055, 0.675, 0.19)';
const pulseKeyframes = null;
const reduceMotionAsPerUserPreference = null;
const animationStyles = null;
export const Pulse = ({ children, pulse = true, ...props })=>(<div {...props} className={ax([
        pulse && "",
        pulse && "_5sagi11n _tip812c5 _j7hq1942 _1pglmcjr _16qsezjf",
        "_1bumglyw _sedtglyw"
    ])}>
		{children}
	</div>);
