/* .tmp-swc-onboarding-target-keyframes-1765408348068-fe9831a742ae.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const baseShadow = '0 0 0 2px #6554C0';
const easing = 'cubic-bezier(0.55, 0.055, 0.675, 0.19)';
const pulseKeyframes = null;
const reduceMotionAsPerUserPreference = null;
const animationStyles = null;
export const Pulse = ({ children, pulse = true, ...props })=>(<div {...props} className={ax([
        pulse && "",
        pulse && ""
    ])}>
		{children}
	</div>);
