/* .tmp-swc-computed-selector-empty-object-1764029521123-23c50ee64c0ab.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
const ICON_CONTAINER_SELECTOR = 'styled-category-item';
type Props = {
    error: boolean;
};
const Wrapper = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { error: error, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={{
        ...__cmpls,
        "--_120drhm": ix({}),
        "--_1mso4je": ix({
            display: 'none'
        })
    }} ref={__cmplr} className={ax([
        "",
        __cmplp.error ? "_1g922sth" : "_1g921a76",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Wrapper.displayName = "Wrapper";
}
export const Example = (props: Props)=><Wrapper {...props}>content</Wrapper>;
