/* .tmp-swc-styled-triple-ampersand-1765439427769-a41172f2e0dfd.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
const BaseLink = (props)=><a {...props}/>;
const LinkStyled = forwardRef(({ as: C = BaseLink, style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    LinkStyled.displayName = "LinkStyled";
}
export const Component = ()=><LinkStyled href="#">Help link</LinkStyled>;
