/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = () => (
	<div className={ax(["_4cvr1h6o _wpxlopcn _kdptidpf _1va9idpf _1e0c1txw"])}>
		<span />
		<span />
		<span />
	</div>
);
