/* .tmp-swc-css-child-combinator-spacing-1765408334997-c1430f788a27.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=>(<div className={ax([])}>
    <span/>
    <span/>
    <span/>
  </div>);
