/* .tmp-swc-css-child-combinator-spacing-1764358656088-a3661a47d56b3.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=>(<div className={ax([
        "_4cvr1h6o _1e0c1txw _bmksopcn _i12cidpf _fhioidpf"
    ])}>
    <span/>
    <span/>
    <span/>
  </div>);
