/* .tmp-swc-css-content-1764364387909-88caac7758f5c.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
export const blank = null;
export const text = null;
export const quoted = null;
export const arrow = null;
export const Element = <div className={ax([
    "_1sb2b3bt",
    "_1sb21e8g",
    "_1sb21e8g",
    "_1sb2bjq5"
])}/>;
