/* .tmp-swc-null-literal-styles-1765408347677-4bcee334c15d.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const bodyStyles = null;
const imageStyles = null;
const defaultHeaderStyles = null;
const DefaultHeader = ({ children })=>(<div className={ax([])}>{children}</div>);
function Component() {
    return (<div>
      <div className={ax([])}>Body content</div>
      <img src="test.jpg" alt="" className={ax([])}/>
      <DefaultHeader>Header</DefaultHeader>
    </div>);
}
export default Component;
