/* .tmp-swc-null-literal-styles-1765930116891-9e89c57f7c179.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const bodyStyles = null;
const imageStyles = null;
const defaultHeaderStyles = null;
const DefaultHeader = ({ children })=>(<div className={ax([
        "_4cvr1q9y _1bah1yb4 _1e0c1txw"
    ])}>{children}</div>);
function Component() {
    return (<div>
      <div className={ax([
        "_2lx21bp4 _ca0q7vkz _u5f37vkz _n3td7vkz _19bv7vkz _1e0c1txw"
    ])}>Body content</div>
      <img src="test.jpg" alt="" className={ax([
        "_1e0c1ule"
    ])}/>
      <DefaultHeader>Header</DefaultHeader>
    </div>);
}
export default Component;
