/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
const extraTopOffset = -1;
const StickyWrapper = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    isEmbedMode,
    zIndex,
    topOffset,
    showKeyline,
    applyVisualRefreshChanges,
    showPaddingTopOnlyOnKeyline,
    isTabLayout,
    isSidebarPanelOpened,
    flexStyle,
    isWideLayout,
    ...__cmpldp
  } = __cmplp;
  return <C {...__cmpldp} style={{
    ...__cmpls,
    "--_w6mvmh": ix(__cmplp.zIndex),
    "--_1dtg6dp": ix(`${__cmplp.topOffset + extraTopOffset}px`),
    "--_hn6azs": ix((() => {
      if (__cmplp.showPaddingTopOnlyOnKeyline) {
        return __cmplp.showKeyline && __cmplp.applyVisualRefreshChanges ? "var(--ds-space-100, 8px)" : `${-extraTopOffset}px`;
      }
      return __cmplp.applyVisualRefreshChanges ? "var(--ds-space-100, 8px)" : `${-extraTopOffset}px`;
    })()),
    "--_1lxvhyt": ix(__cmplp.isWideLayout ? '1920px' : 'inherit'),
    "--_1j3ddle": ix(__cmplp.isWideLayout ? '100%' : 'inherit'),
    "--_pxmdp9": ix(__cmplp.isWideLayout ? 'center' : 'inherit')
  }} ref={__cmplr} className={ax(["", __cmplp.flexStyle && "", __cmplp.className])} />;
});
if (process.env.NODE_ENV !== 'production') {
  StickyWrapper.displayName = 'StickyWrapper';
}
const Fixture = () => <StickyWrapper topOffset={0} showKeyline isEmbedMode zIndex={10} applyVisualRefreshChanges flexStyle isWideLayout isTabLayout showPaddingTopOnlyOnKeyline isSidebarPanelOpened={false}>
    content
  </StickyWrapper>;
export default Fixture;
