/* .tmp-swc-sticky-header-padding-1764627629458-4828e18d10cb.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
const extraTopOffset = -1;
const StickyWrapper = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { isEmbedMode: isEmbedMode, zIndex: zIndex, topOffset: topOffset, showKeyline: showKeyline, applyVisualRefreshChanges: applyVisualRefreshChanges, showPaddingTopOnlyOnKeyline: showPaddingTopOnlyOnKeyline, isTabLayout: isTabLayout, isSidebarPanelOpened: isSidebarPanelOpened, flexStyle: flexStyle, isWideLayout: isWideLayout, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={{
        ...__cmpls,
        "--_w6mvmh": ix(__cmplp.zIndex),
        "--_1dtg6dp": ix(`${__cmplp.topOffset + extraTopOffset}px`),
        "--_hn6azs": ix((()=>{
            if (__cmplp.showPaddingTopOnlyOnKeyline) {
                return __cmplp.showKeyline && __cmplp.applyVisualRefreshChanges ? "var(--ds-space-100, 8px)" : `${-extraTopOffset}px`;
            }
            return __cmplp.applyVisualRefreshChanges ? "var(--ds-space-100, 8px)" : `${-extraTopOffset}px`;
        })()),
        "--_1lxvhyt": ix(__cmplp.isWideLayout ? '1920px' : 'inherit'),
        "--_1j3ddle": ix(__cmplp.isWideLayout ? '100%' : 'inherit'),
        "--_pxmdp9": ix(__cmplp.isWideLayout ? 'center' : 'inherit')
    }} ref={__cmplr} className={ax([
        "_1axi1if8 _1ae31fcb _vggs17df _nn8px0bf _uto9d5jx",
        __cmplp.isEmbedMode ? "_r3721bhr" : "_r372vuon",
        __cmplp.showKeyline && "_igsx17gk",
        __cmplp.showKeyline && __cmplp.applyVisualRefreshChanges && "_1u8bu2gc",
        __cmplp.isTabLayout && "_4eq41ejb",
        __cmplp.isSidebarPanelOpened ? "_s9qln7od" : __cmplp.isTabLayout ? "_s9ql1ejb" : "_s9qlu2gc",
        __cmplp.flexStyle && "_1bah1yb4 _10fpdmq1 _1e0c1txw _p12f1d9w _1bsbcbx4",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    StickyWrapper.displayName = "StickyWrapper";
}
const Fixture = ()=><StickyWrapper topOffset={0} showKeyline isEmbedMode zIndex={10} applyVisualRefreshChanges flexStyle isWideLayout isTabLayout showPaddingTopOnlyOnKeyline isSidebarPanelOpened={false}>
    content
  </StickyWrapper>;
export default Fixture;
