/* .tmp-swc-cssmap-decimal-preservation-1763963507670-d45cfca80a814.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
const styles = {
    root: "_16jlfmrs"
};
export const Component = ()=><div className={ax([
        styles.root
    ])}/>;
