/* .tmp-swc-cssmap-decimal-preservation-1765439413791-f0a111d57145c.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
const styles = {
    root: ""
};
export const Component = ()=><div className={ax([
        styles.root
    ])}/>;
