/* .tmp-swc-styled-string-template-1766020321801-21f35930a4cf8.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { gridSize } from './grid-size';
const nameStyles = `
  margin-right: ${gridSize * 3}px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
`;
const NameLink = forwardRef(({ as: C = "a", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "_2hwx1tcg _o5721q9c _1reo15vq _18m915vq _1bto1l2s",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    NameLink.displayName = "NameLink";
}
export const Component = ()=><NameLink>text</NameLink>;
