/* .tmp-swc-hover-display-1765439416469-3be5a5791dbd.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const tabStyles = null;
export const Component = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={{
        ...__cmpls,
        "--_b3nd5v": ix(__cmplp.isDraggable ? 'none' : 'flex'),
        "--_11m4mys": ix(__cmplp.isDraggable ? 'flex' : 'none')
    }} ref={__cmplr} className={ax([
        "",
        __cmplp.isDragging && "",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Component.displayName = "Component";
}
