/* .tmp-swc-hover-display-1763846883628-5279a10ec12ad.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const tabStyles = null;
export const Component = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "",
        __cmplp.isDraggable ? "_15y3glyw" : "_15y31txw",
        __cmplp.isDraggable ? "_oyoh1txw" : "_oyohglyw",
        __cmplp.isDragging && "_tzy41kuy",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Component.displayName = "Component";
}
