/* .tmp-swc-navigation-system-logo-xcss-1765437470561-556b1dd8a8736.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
import { cx } from '@compiled/react';
const anchorStyles = {
    root: "",
    newInteractionStates: ""
};
const logoContainerStyles = {
    root: ""
};
const LogoRenderer = ({ logoOrIcon })=>{
    return <div>{logoOrIcon}</div>;
};
const Anchor = ({ children, xcss, ...props })=>{
    return <a {...props}>{children}</a>;
};
export const CustomLogo = ({ href, logo, icon, onClick, label })=>{
    return (<Anchor aria-label={label} href={href} xcss={cx(anchorStyles.root, anchorStyles.newInteractionStates)} onClick={onClick}>
      <div className={ax([
        logoContainerStyles.root
    ])}>
        <LogoRenderer logoOrIcon={logo}/>
      </div>
    </Anchor>);
};
