/* .tmp-swc-navigation-system-logo-xcss-1764044656732-18deadee3f182.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
import { cx } from '@compiled/react';
const anchorStyles = {
    root: "_4cvr1h6o _2rkofajl _1e0c1txw _4t3izwfg",
    newInteractionStates: "_irr31dpa _1di69yc7"
};
const logoContainerStyles = {
    root: "_18zru2gc _1e0cglyw _p12fnklw _vchh1ntv _10y41txw"
};
const LogoRenderer = ({ logoOrIcon })=>{
    return <div>{logoOrIcon}</div>;
};
const Anchor = ({ children, xcss, ...props })=>{
    return <a {...props}>{children}</a>;
};
export const CustomLogo = ({ href, logo, icon, onClick, label })=>{
    return (<Anchor aria-label={label} href={href} xcss={cx(anchorStyles.root, anchorStyles.newInteractionStates)} onClick={onClick}>
      <div className={ax([
        logoContainerStyles.root
    ])}>
        <LogoRenderer logoOrIcon={logo}/>
      </div>
    </Anchor>);
};
