/* .tmp-swc-gadget-inner-font-styles-1765408342820-1c4c1ea275b95.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
export const Gadget = ()=>{
    const fullWidthStyles = null;
    return <div className={ax([])}/>;
};
const fontStyles = null;
