/* .tmp-swc-gadget-inner-font-styles-1765437468604-65be07eb503ef.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
export const Gadget = ()=>{
    const fullWidthStyles = null;
    return <div className={ax([])}/>;
};
const fontStyles = null;
