/* .tmp-swc-gadget-inner-font-styles-1764364389782-7551a4c0854f6.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
export const Gadget = ()=>{
    const fullWidthStyles = null;
    return <div className={ax([
        "_1bsb1osq",
        "_ect41gqc"
    ])}/>;
};
const fontStyles = null;
