/* .tmp-swc-styled-imported-arithmetic-1765246831535-97960ffc99423.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { gridSize } from './constants';
const Container = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "_18u01wug _2hwx1wug _p4liftgi _owip7vkz _6aut1tcg _1pqwzwfg _1ul9ys9h _p12f1lit _13l9h2mm",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Container.displayName = "Container";
}
const Logo = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "_1bsb7vkz _4t3i1tcg _1o9zidpf",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Logo.displayName = "Logo";
}
export const Component = ()=>(<Container>
    <Logo/>
    <table>
      <tbody>
        <tr>
          <td>First</td>
          <td>Second</td>
        </tr>
      </tbody>
    </table>
  </Container>);
