/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
const gridSize = 8;
const ACTIONS_CELL_PADDING = `${gridSize / 2}px`; // 4px
const TABLE_BUTTON_OUTLINE = `${gridSize / 4}px`; // 2px

const styles = null;
export const Component = () => <div className={ax([])} />;
