/* .tmp-swc-padding-shorthand-mixed-1764112019817-e925c5f71848.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const gridSize = 8;
const ACTIONS_CELL_PADDING = `${gridSize / 2}px`;
const TABLE_BUTTON_OUTLINE = `${gridSize / 4}px`;
const styles = null;
export const Component = ()=><div className={ax([
        "_1bahesu3 _ca0q1y44 _u5f3yh40 _n3tdidpf _19bvidpf _1e0c1txw"
    ])}/>;
