/* in.tsx generated by @compiled/babel-plugin v0.38.1 */
// Reproduces spacing in nth-of-type selector that mismatches between Babel/SWC.
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
const statisticStyles = null;
const Fixture = () => <table>
		<tbody>
			<tr>
				<td className={ax([])}>first</td>
			</tr>
			<tr>
				<td className={ax([])}>second</td>
			</tr>
		</tbody>
	</table>;
export default Fixture;
