/* .tmp-swc-nth-of-type-plus-one-spaced-1765408347538-7c606779fe3a3.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const statisticStyles = null;
const Fixture = ()=>(<table>
		<tbody>
			<tr>
				<td className={ax([])}>first</td>
			</tr>
			<tr>
				<td className={ax([])}>second</td>
			</tr>
		</tbody>
	</table>);
export default Fixture;
