/* .tmp-swc-nth-of-type-plus-one-spaced-1765752974581-3703c22c41bc.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const statisticStyles = null;
const Fixture = ()=>(<table>
		<tbody>
			<tr>
				<td className={ax([
        "_1vykftgi"
    ])}>first</td>
			</tr>
			<tr>
				<td className={ax([
        "_1vykftgi"
    ])}>second</td>
			</tr>
		</tbody>
	</table>);
export default Fixture;
