/* .tmp-swc-css-expression-1765408335921-c98b74b8205c2.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=><div className={ax([])}>Hello</div>;
