/* .tmp-swc-css-expression-1765437465313-6af6ec79f2a93.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=><div className={ax([])}>Hello</div>;
