/* .tmp-swc-css-expression-1764039558254-a3caf6471c0c9.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=><div className={ax([
        "_19pk19bv _2hwx19bv _otyr19bv _18u019bv _ca0q19bv _u5f319bv _n3td19bv _19bv19bv"
    ])}>Hello</div>;
