/* .tmp-swc-xcss-prop-as-classname-1765408362094-895865cabb874.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    root: ""
};
export function Root({ children, xcss, testId }) {
    return (<div className={ax([
        styles.root,
        xcss
    ])} data-testid={testId}>
			{children}
		</div>);
}
