/* .tmp-swc-xcss-prop-as-classname-1764360576798-8a7e8fe18caaf.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    root: "_1lmcq9em _yv0ei47z _2z0516ab _1e0c11p5 _1tke1kxc _12fkuz0r _12qzrxre _1rqt70if"
};
export function Root({ children, xcss, testId }) {
    return (<div className={ax([
        styles.root,
        xcss
    ])} data-testid={testId}>
			{children}
		</div>);
}
