/* .tmp-swc-styled-template-conditional-1765408358726-1329db31ac419.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const padding = '8px';
const large = 8;
const small = 4;
const Cell = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { first: first, last: last, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax([
        "",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Cell.displayName = "Cell";
}
export const Component = ({ first, last })=>(<Cell first={first} last={last}>
    Content
  </Cell>);
