/* .tmp-swc-lozenge-complex-cssmap-1765437469456-d85b9a03422fb.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const stylesNew = {
    container: "",
    containerSubtle: "",
    text: "",
    'bg.bold.default': "",
    'bg.bold.inprogress': "",
    'bg.bold.moved': "",
    'bg.bold.new': "",
    'bg.bold.removed': "",
    'bg.bold.success': "",
    'bg.subtle.default': "",
    'bg.subtle.inprogress': "",
    'bg.subtle.moved': "",
    'bg.subtle.new': "",
    'bg.subtle.removed': "",
    'bg.subtle.success': "",
    'border.subtle.default': "",
    'border.subtle.inprogress': "",
    'border.subtle.moved': "",
    'border.subtle.new': "",
    'border.subtle.removed': "",
    'border.subtle.success': "",
    'outline.subtle.default': "",
    'outline.subtle.inprogress': "",
    'outline.subtle.moved': "",
    'outline.subtle.new': "",
    'outline.subtle.removed': "",
    'outline.subtle.success': "",
    'text.subtle': "",
    'text.bold': ""
};
function LozengeComponent({ appearance, isBold }) {
    const appearanceStyle = isBold ? 'bold' : 'subtle';
    return (<span className={ax([
        stylesNew.container,
        stylesNew[`bg.${appearanceStyle}.${appearance}`],
        stylesNew[`border.subtle.${appearance}`],
        stylesNew.containerSubtle
    ])}>
      <span className={ax([
        stylesNew.text,
        stylesNew[`text.${appearanceStyle}`]
    ])}>
        Content
      </span>
    </span>);
}
