/* .tmp-swc-timeline-cell-xcss-1765404349816-b9f29ec96f1b6.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
import { Box } from '@atlaskit/primitives/compiled';
export default function Component() {
    return <Box xcss={styles.cellWrapper}>Timeline cell</Box>;
}
const styles = {
    cellWrapper: "_1r04ze3t _u5f3u2gc _19bvu2gc _4cvr1h6o _4t3i1osq _kqswh2mm _1bsb1osq _1e0c1txw _1reo15vq"
};
