/* .tmp-swc-timeline-cell-xcss-1765439428050-1b410cc99ffce.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
import { Box } from '@atlaskit/primitives/compiled';
export default function Component() {
    return <Box xcss={styles.cellWrapper}>Timeline cell</Box>;
}
const styles = {
    cellWrapper: ""
};
