/* .tmp-swc-xcss-classname-conflict-1764733736212-8d2622518d2e6.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { Fragment } from 'react';
const mainElementStyles = {
    root: "_nd5l1gzg _152tckbl _19121cl4 _1reo1wug _18m91wug _qwfh1wug _165tk7wh _13wn1if8"
};
export function Main({ children, xcss, testId }) {
    return (<Fragment>
			<div className={ax([
        mainElementStyles.root,
        xcss
    ])} role="main" data-testid={testId}>
				{children}
			</div>
		</Fragment>);
}
