/* .tmp-swc-xcss-classname-conflict-1765439428906-f10167166aa49.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { Fragment } from 'react';
const mainElementStyles = {
    root: ""
};
export function Main({ children, xcss, testId }) {
    return (<Fragment>
			<div className={ax([
        mainElementStyles.root,
        xcss
    ])} role="main" data-testid={testId}>
				{children}
			</div>
		</Fragment>);
}
