/* .tmp-swc-selector-template-hash-new-1765930118114-fdf68072cbcab.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    padding: "_1yt414ue",
    rows: "_2z05kxnq",
    textColor: "_4bfu18uv",
    textColorImportant: "_4bfu1r81",
    columnsA: "_yv0e105t",
    columnsB: "_yv0es54b",
    paddingLeft: "_19bv1f4h",
    rowsB: "_2z05p6rl",
    textInitial: "_4bfu18uv",
    textInitialImportant: "_4bfu1r81",
    paddingRight: "_u5f31y44",
    columnsC: "_yv0e9n6h",
    columnsD: "_yv0epgpq"
};
export const Fixture = ()=>(<div className={ax([
        styles.padding,
        styles.rows,
        styles.textColor,
        styles.textColorImportant,
        styles.columnsA,
        styles.columnsB,
        styles.paddingLeft,
        styles.rowsB,
        styles.textInitial,
        styles.textInitialImportant,
        styles.paddingRight,
        styles.columnsC,
        styles.columnsD
    ])}>
    content
  </div>);
