/* .tmp-swc-css-array-with-conditions-1764368028387-4d6f29ee29c59.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const baseStyles = null;
const variantStyles = null;
export const Component = ({ variant, disabled, children })=>{
    return (<div className={ax([
        "_ca0qftgi _u5f3ftgi _n3tdftgi _19bvftgi _1e0c1txw",
        variant && "_s3uh13q2 _vt6du67f _r5gp17nt _119sr3uz",
        disabled && "_tzy4105o _lcxvglyw"
    ])}>
      {children}
    </div>);
};
