/* .tmp-swc-css-array-with-conditions-1765408334418-23694d1e36b4e.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const baseStyles = null;
const variantStyles = null;
export const Component = ({ variant, disabled, children })=>{
    return (<div className={ax([
        variant && "",
        disabled && ""
    ])}>
      {children}
    </div>);
};
