/* .tmp-swc-styled-imported-value-1764484171920-d4e7a7221e7b9.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { colors } from './palette';
const StyledDiv = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "_syaz15td",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    StyledDiv.displayName = "StyledDiv";
}
export const Component = ()=><StyledDiv>Hi</StyledDiv>;
