/* .tmp-swc-styled-token-conditional-1764364393607-eb07bc7f15919.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
export const Component = (props)=>{
    const Label = forwardRef(({ as: C = "h5", style: __cmpls, ...__cmplp }, __cmplr)=>{
        if (__cmplp.innerRef) {
            throw new Error("Please use 'ref' instead of 'innerRef'.");
        }
        return <C {...__cmplp} style={{
            ...__cmpls,
            "--_1xxt5am": ix(props.isDisabled ? 'var(--ds-text-disabled, #080F214A)' : 'var(--ds-text, #292A2E)')
        }} ref={__cmplr} className={ax([
            "_syazsxvs",
            __cmplp.className
        ])}/>;
    });
    return <Label>text</Label>;
};
