/* .tmp-swc-image-export-pointer-events-1764625074222-37d0a10d9be4e.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const hiddenTableContainerStyles = null;
const tableWrapperStyles = null;
const Fixture = ()=>(<div>
    <div className={ax([
        "_154iidpf _1ltvidpf _kqswstnw _1bsb1osq _4t3i1osq _1reo15vq _18m915vq _tzy4idpf _lcxvglyw _169tglyw"
    ])}>hidden</div>
    <div className={ax([
        "_dfo0glyw"
    ])}>wrapped</div>
  </div>);
export default Fixture;
