/* .tmp-swc-image-export-pointer-events-1765439416656-36a79ac9087a9.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const hiddenTableContainerStyles = null;
const tableWrapperStyles = null;
const Fixture = ()=>(<div>
    <div className={ax([])}>hidden</div>
    <div className={ax([])}>wrapped</div>
  </div>);
export default Fixture;
