/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const colors = {
	primary: "tomato",
	secondary: "#daa520",
};
const fadeIn = null;
export const dynamicText = null;
export const FancyButton = forwardRef(
	({ as: C = "button", style: __cmpls, ...__cmplp }, __cmplr) => {
		if (__cmplp.innerRef) {
			throw new Error("Please use 'ref' instead of 'innerRef'.");
		}
		return (
			<C
				{...__cmplp}
				style={__cmpls}
				ref={__cmplr}
				className={ax([
					"_ilggidpf _1exukb7n _bexg6l02 _1rjnyh40 _b8imnqa1 _1bl71iu8 _rkan120f",
					__cmplp.className,
				])}
			/>
		);
	}
);
if (process.env.NODE_ENV !== "production") {
	FancyButton.displayName = "FancyButton";
}
const themed = {
	primary: "_9ad01a6z",
	secondary: "_9ad01iu8",
};
const alias = "secondary";
export const mappedClass = themed[alias];
export const WithClassNames = () => <div className={ax(["_9ad01iu8 _gq7j198p"])}>example</div>;
