/* .tmp-swc-css-and-classname-conflict-1763963506441-c8d3c9b1f8be5.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    root: "_nd5lns35 _vchhusvi _kqswh2mm _glte25cg _ndwch9n0"
};
export function Component({ xcss, children }) {
    return (<aside className={ax([
        styles.root,
        xcss
    ])}>
			{children}
		</aside>);
}
