/* .tmp-swc-css-and-classname-conflict-1765408333709-9d66b1d0e7727.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    root: ""
};
export function Component({ xcss, children }) {
    return (<aside className={ax([
        styles.root,
        xcss
    ])}>
			{children}
		</aside>);
}
