/* .tmp-swc-styled-static-template-value-1763973275470-562ae458092b5.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const GRID = 8;
const SIZE = GRID * 2;
const Icon = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "_1bsb7vkz _1ul97vkz _4t3i7vkz _i0dlexct",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Icon.displayName = "Icon";
}
export const Component = ()=><Icon/>;
