/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
const styles = {
  primary: "",
  secondary: ""
};
export const Component = () => <div>
    <span className={styles.primary()}>Primary</span>
    <span className={styles.secondary()}>Secondary</span>
  </div>;
