/* .tmp-swc-css-map-1766020315692-97408eb07c54e.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    primary: "_syazso35",
    secondary: "_syaz1iu8"
};
export const Component = ()=>(<div>
    <span className={styles.primary()}>Primary</span>
    <span className={styles.secondary()}>Secondary</span>
  </div>);
