/* .tmp-swc-xcss-prop-type-in-css-array-1765437477823-cdc95d0a2c165.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    root: ""
};
function Root({ xcss }) {
    return (<div className={ax([
        styles.root
    ])}>
      Content
    </div>);
}
