/* .tmp-swc-xcss-prop-type-in-css-array-1765439429500-3a4c46456b262.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    root: ""
};
function Root({ xcss }) {
    return (<div className={ax([
        styles.root
    ])}>
      Content
    </div>);
}
