/* .tmp-swc-xcss-prop-type-in-css-array-1763973276181-4ee4c9028b6b8.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    root: "_1lmcq9em _yv0ei47z _2z0516ab _1e0c11p5 _1tke1kxc _1ciragmp _12fkuz0r _12qzrxre _1rqt70if"
};
function Root({ xcss }) {
    return (<div className={ax([
        styles.root
    ])}>
      Content
    </div>);
}
