/* .tmp-swc-csssmap-banner-1764733730346-0d2225451739b.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    root: "_nd5ldkfm _152tidpf _4t3i1p2j _kqsw1if8 _1pbyb4wl _1reo15vq _18m915vq"
};
function Banner({ children, xcss, height = 48, testId }) {
    return (<div data-layout-slot data-testid={testId} className={ax([
        styles.root
    ])}>
      {children}
    </div>);
}
export default Banner;
