/* .tmp-swc-csssmap-banner-1765437467699-f81cf8c2f2598.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    root: ""
};
function Banner({ children, xcss, height = 48, testId }) {
    return (<div data-layout-slot data-testid={testId} className={ax([
        styles.root
    ])}>
      {children}
    </div>);
}
export default Banner;
