/* .tmp-swc-media-flex-order-1765927675919-0b98e11f5c50d.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const card = null;
export const Example = ()=><div className={ax([
        "_1e0cglyw _je3o1txw _12iakb7n _1fbvkb7n _190kf1ug _1aev1h6o _vu061h6o _16puh2mm _11sj15vq _1l5315vq _ytj91myn _2tde7vkz _uwpc7vkz"
    ])}/>;
