/* .tmp-swc-media-flex-order-1765437470194-d403d5e8ffd1a.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const card = null;
export const Example = ()=><div className={ax([])}/>;
