/* .tmp-swc-media-flex-order-1765439418321-096f01474e2d9.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const card = null;
export const Example = ()=><div className={ax([])}/>;
