/* .tmp-swc-optional-chain-dynamic-style-1765408348392-7abbee4040374.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
type Position = {
    left?: number;
    top?: number;
};
const Fieldset = forwardRef(({ as: C = "fieldset", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { position: position, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={{
        ...__cmpls,
        "--_1qibnji": ix(__cmplp.position?.left, "px"),
        "--_1gg2u2w": ix(__cmplp.position?.top, "px")
    }} ref={__cmplr} className={ax([
        "",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Fieldset.displayName = "Fieldset";
}
export default function Component(props: {
    position?: Position;
}) {
    return <Fieldset position={props.position}>hello</Fieldset>;
}
