/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
const ROW_GAP = 4;
const COLUMN_GAP = 8;
const FIELD_HEIGHT = 30;
const FIELD_HEIGHT_COMPACT = 20;
const DISPLAYING_FIELDS_MIN_CARD_WIDTH = 75;

// A reduced version of the idea-card FieldsContainer styles that produced a selector hash mismatch
// between Babel and SWC. Keep the nth-of-type selector and the container query intact.
const FieldsContainer = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    isRow,
    hasMaxContent,
    cappedFieldsDisplay,
    ...__cmpldp
  } = __cmplp;
  return <C {...__cmpldp} style={{
    ...__cmpls,
    "--_szi7k6": ix(!__cmplp.isRow && '[title] fit-content(100px) [content] 1fr'),
    "--_13i0unl": ix(!__cmplp.isRow && `minmax(${FIELD_HEIGHT}px, auto)`),
    "--_12p36mt": ix(__cmplp.isRow && `${FIELD_HEIGHT_COMPACT + ROW_GAP}px`)
  }} ref={__cmplr} className={ax(["", __cmplp.className])} />;
});
if (process.env.NODE_ENV !== 'production') {
  FieldsContainer.displayName = 'FieldsContainer';
}
export const Component = () => <FieldsContainer isRow hasMaxContent cappedFieldsDisplay>
    <div />
    <div />
    <div />
    <div />
  </FieldsContainer>;
