/* .tmp-swc-css-imported-media-query-1765439411147-95793fa49a154.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { mq } from './breakpoints';
const styles = null;
export const Component = ()=><div className={ax([])}>Hello</div>;
