/* .tmp-swc-css-imported-media-query-1764034567401-4d497fc201e37.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { mq } from './breakpoints';
const styles = null;
export const Component = ()=><div className={ax([
        "_qhso1cnh"
    ])}>Hello</div>;
