/* .tmp-swc-css-shared-styles-width-1765408338466-9ce5385a02dd7.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { sharedStyles } from './sharedStyles';
const ColumnPlaceholder = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    ColumnPlaceholder.displayName = "ColumnPlaceholder";
}
export const Component = ()=><ColumnPlaceholder/>;
