/* .tmp-swc-cssmap-dynamic-property-access-1765439413880-8ffcc5136c826.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    default: "",
    'above.xs': "",
    'above.sm': "",
    'above.md': "",
    'below.xs': "",
    'below.sm': ""
};
export const Component = ({ above, below, children })=>{
    return (<div className={ax([
        styles.default,
        above && styles[`above.${above}`],
        below && styles[`below.${below}`]
    ])}>
      {children}
    </div>);
};
