/* .tmp-swc-cssmap-dynamic-property-access-1765246827588-ff2b8607a98dc.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    default: "_1e0cglyw",
    'above.xs': "_114b19ly",
    'above.sm': "_181n19ly",
    'above.md': "_dm2519ly",
    'below.xs': "_1m0a19ly",
    'below.sm': "_suga19ly"
};
export const Component = ({ above, below, children })=>{
    return (<div className={ax([
        styles.default,
        above && styles[`above.${above}`],
        below && styles[`below.${below}`]
    ])}>
      {children}
    </div>);
};
