/* .tmp-swc-responsive-show-cssmap-1765408350010-d377d6442ce21.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    default: "",
    'above.xs': "",
    'above.sm': "",
    'above.md': "",
    'above.lg': "",
    'above.xl': "",
    'below.xs': "",
    'below.sm': "",
    'below.md': "",
    'below.lg': "",
    'below.xl': ""
};
export const Show = ({ above, below, children })=>{
    return (<div className={ax([
        styles.default,
        above && styles[`above.${above}`],
        below && styles[`below.${below}`]
    ])}>
      {children}
    </div>);
};
