/* .tmp-swc-status-color-map-token-1765439421648-9dbc24d605757.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const STATUS = {
    TODO: 'TODO',
    IN_PROGRESS: 'IN_PROGRESS',
    DONE: 'DONE',
    UNKNOWN: 'UNKNOWN'
} as const;
const STATUS_COLOR_MAP = {
    [STATUS.TODO]: "var(--ds-icon-accent-gray, #7D818A)",
    [STATUS.IN_PROGRESS]: "var(--ds-icon-accent-blue, #357DE8)",
    [STATUS.DONE]: "var(--ds-icon-accent-green, #22A06B)",
    [STATUS.UNKNOWN]: 'unset'
};
export const StatusBar = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { status: status, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={{
        ...__cmpls,
        "--_1h75lj6": ix(STATUS_COLOR_MAP[__cmplp.status])
    }} ref={__cmplr} className={ax([
        "",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    StatusBar.displayName = "StatusBar";
}
