/* in.tsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
import * as styles from './styles.module.css';
const gridAreas = () => {
  if (styles.primary && styles.tertiary && styles.secondary) {
    return `"${styles.primary} ${styles.tertiary} ${styles.secondary}"`;
  }
  return '"primary tertiary secondary"';
};
const Footer = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <C {...__cmplp} style={{
    ...__cmpls,
    "--_o48r1v": ix(gridAreas())
  }} ref={__cmplr} className={ax(["_1lmc1r3e", __cmplp.className])} />;
});
if (process.env.NODE_ENV !== 'production') {
  Footer.displayName = 'Footer';
}
export const Component = () => <Footer />;
