/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix } from "@compiled/react/runtime";
import * as React from "react";
const base = 10;
const offset = 4;
const colors = ["red", "blue", "seagreen"];
export const dynamicPadding = null;
export const expressionObject = null;
export const ExpressionExample = () => (
	<div
		className={ax([
			"_ca0q1f4h _u5f31f4h _n3td1f4h _19bv1f4h _syaz1o0q _1llw1f4f",
			"_18u0dlk8 _2rko8y89",
		])}
		style={{
			"--_y28lkp": ix(Math.max(base - 5, 0), "px"),
		}}
	>
		expression output
	</div>
);
