/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
const base = 10;
const offset = 4;
const colors = ['red', 'blue', 'seagreen'];
export const dynamicPadding = null;
