/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix } from '@compiled/react/runtime';
import * as React from 'react';
const base = 10;
const offset = 4;
const colors = ['red', 'blue', 'seagreen'];
export const dynamicPadding = null;
export const expressionObject = null;
export const ExpressionExample = () => (
  <div className={[dynamicPadding, expressionObject].join(' ')}>expression output</div>
);
