/* .tmp-swc-expression-export-1764484168117-30cca2176f77e.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const base = 10;
const offset = 4;
const colors = [
    'red',
    'blue',
    'seagreen'
];
export const dynamicPadding = null;
export const expressionObject = null;
export const ExpressionExample = ()=>(<div className={ax([
        "_ca0q1f4h _u5f31f4h _n3td1f4h _19bv1f4h _syazudzx _1llw1f4f",
        "_18u0dlk8 _2rko14y2"
    ])} style={{
        "--_155apf6": ix(colors[2])
    }}>
    expression output
  </div>);
