/* .tmp-swc-expression-export-1765439415429-ef41de09a0501.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const base = 10;
const offset = 4;
const colors = [
    'red',
    'blue',
    'seagreen'
];
export const dynamicPadding = null;
export const expressionObject = null;
export const ExpressionExample = ()=>(<div className={ax([])} style={{
        "--_155apf6": ix(colors[2])
    }}>
    expression output
  </div>);
