/* .tmp-swc-contextual-summary-styles-1765408333615-7a24925072b9f.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const media = {
    above: {
        xxs: '@media (min-width: 0rem)',
        sm: '@media (min-width: 48rem)'
    }
};
const styles = null;
export const Component = ()=><div className={ax([])}>
    <span>Hi</span>
  </div>;
