/* .tmp-swc-contextual-summary-styles-1764364387499-b86748b47c382.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const media = {
    above: {
        xxs: '@media (min-width: 0rem)',
        sm: '@media (min-width: 48rem)'
    }
};
const styles = null;
export const Component = ()=><div className={ax([
        "_4cvr1h6o _19pkxy5q _19bvu2gc _11q7vuon _2rko12b0 _zulpu2gc _1e0c1txw _1tjq16l4 _1alv1bp4 _1lp7vrvc"
    ])}>
    <span>Hi</span>
  </div>;
