/* .tmp-swc-null-literal-styles-2-1764713730689-a5d74b2d0053b.jsx generated by @compiled/babel-plugin v0.38.1 */
;
const CSS_VAR_ICON_COLOR = '--flag-icon-color';
const descriptionStyles = {};
const iconWrapperStyles = {};
const flagWrapperStyles = {};
const analyticsAttributes = {
    componentName: 'flag',
    packageName: 'test',
    packageVersion: '1.0.0'
};
function Flag() {
    return (<div>
            <span>Content</span>
            <div>Test</div>
        </div>);
}
export default Flag;
