/* .tmp-swc-styled-token-gap-dedup-1765408359368-31a2fe7da26b1.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const ModalBodyWrapper = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    ModalBodyWrapper.displayName = "ModalBodyWrapper";
}
const ProgressBarWrapper = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    ProgressBarWrapper.displayName = "ProgressBarWrapper";
}
export const Example = ({ isAlternate })=>(<div>
    <ModalBodyWrapper data-testid={isAlternate ? 'alt' : 'default'}>
      Content
    </ModalBodyWrapper>
    <ProgressBarWrapper>
      <span>Hello</span>
    </ProgressBarWrapper>
  </div>);
