/* in.tsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
const containerStylesOld = null;
const titleContainerStyles = null;
const childContainerStyles = null;
const DependencyCardFixture = ({
  withParent = true
}) => {
  const content = <div className={ax([])}>content</div>;
  return withParent ? <>
      <div className={ax([])}>title</div>
      <div className={ax([])}>{content}</div>
    </> : content;
};
export default DependencyCardFixture;
