/* .tmp-swc-dependency-card-length-mismatch-1764296819885-6f9b92907f278.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const _10 = "._2lx2vrvc{flex-direction:row}";
const _11 = "._4cvr1h6o{align-items:center}";
const _12 = "._1reo15vq{overflow-x:hidden}";
const _13 = "._18m915vq{overflow-y:hidden}";
const _14 = "._19bv1ejb{padding-left:var(--ds-space-300,24px)}";
const _15 = "._19pk1b66{margin-top:var(--ds-space-050,4px)}";
const containerStylesOld = null;
const titleContainerStyles = null;
const childContainerStyles = null;
const DependencyCardFixture = ({ withParent = true })=>{
    const content = <div className={ax([
        "_2lx21bp4 _ca0qu2gc _u5f3pxbi _n3tdu2gc _19bvpxbi _1e0c1txw _kqswh2mm _bfhkhp5a _16qszucj"
    ])}>content</div>;
    return withParent ? <>
      <CC>
  <CS>{[
        _10,
        _11,
        _6,
        _7,
        _12,
        _13
    ]}</CS>
  {<div className={ax([
        "_2lx2vrvc _4cvr1h6o _1e0c1txw _kqswh2mm _1reo15vq _18m915vq"
    ])}>title</div>}
</CC>
      <CC>
  <CS>{[
        _14,
        _15,
        _7
    ]}</CS>
  {<div className={ax([
        "_19bv1ejb _19pk1b66 _kqswh2mm"
    ])}>{content}</div>}
</CC>
    </> : content;
};
export default DependencyCardFixture;
