/* .tmp-swc-dependency-card-length-mismatch-1764364389417-8d915af36d7a.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const containerStylesOld = null;
const titleContainerStyles = null;
const childContainerStyles = null;
const DependencyCardFixture = ({ withParent = true })=>{
    const content = <div className={ax([
        "_2lx21bp4 _ca0qu2gc _u5f3pxbi _n3tdu2gc _19bvpxbi _1e0c1txw _kqswh2mm _bfhkhp5a _16qszucj"
    ])}>content</div>;
    return withParent ? <>
      <div className={ax([
        "_2lx2vrvc _4cvr1h6o _1e0c1txw _kqswh2mm _1reo15vq _18m915vq"
    ])}>title</div>
      <div className={ax([
        "_19bv1ejb _19pk1b66 _kqswh2mm"
    ])}>{content}</div>
    </> : content;
};
export default DependencyCardFixture;
