/* .tmp-swc-refine-dropdown-jsx-error-1764112019919-02cd86eaf1c1f.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import DropdownMenu, { DropdownItem, DropdownItemGroup } from '@atlaskit/dropdown-menu';
function Item({ item, onItemClick, currentOpenedSubMenu, onSubMenuOpenChanged }) {
    if ('children' in item && item.children) {
        const handleOpenChange = ({ isOpen })=>{
            onSubMenuOpenChanged?.(item, isOpen);
        };
        return <DropdownMenu placement="right-start" shouldRenderToParent isOpen={currentOpenedSubMenu === item} onOpenChange={handleOpenChange} trigger={({ triggerRef, ...triggerProps })=><DropdownItem {...triggerProps} ref={triggerRef} elemBefore={item.icon} elemAfter={<span color={"var(--ds-icon-subtle, #626F86)"}>→</span>}>
						<span>{item.title}</span>
					</DropdownItem>}>
				<DropdownItemGroup>
					<RefineDropdownItems items={item.children} onItemClick={onItemClick}/>
				</DropdownItemGroup>
			</DropdownMenu>;
    }
    return <DropdownItem elemBefore={item.icon} onClick={()=>onItemClick()}>
			{item.title}
		</DropdownItem>;
}
