/* .tmp-swc-css-box-shadow-with-token-1764020413882-3f0c8fed0c76b.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const border = null;
const Component = ()=><div className={ax([
        "_16qsk52m"
    ])}>
    <span>Content with border</span>
  </div>;
export default Component;
