/* .tmp-swc-css-box-shadow-with-token-1764733728668-1c7fb65f92b8a.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const border = null;
const Component = ()=><div className={ax([
        "_16qsk52m"
    ])}>
    <span>Content with border</span>
  </div>;
export default Component;
