/* .tmp-swc-css-box-shadow-with-token-1765408334768-dd5b17aac622c.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const border = null;
const Component = ()=><div className={ax([])}>
    <span>Content with border</span>
  </div>;
export default Component;
