/* .tmp-swc-descendant-attribute-selector-1765439415034-84369f4d287c9.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const wrapper = null;
export const Example = ()=>(<div className={ax([])}>
    <div data-testid="header">Header</div>
    <div data-testid="child">Body</div>
  </div>);
