/* .tmp-swc-descendant-attribute-selector-1764318510580-a1fded47a5dea.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const wrapper = null;
export const Example = ()=>(<div className={ax([
        "_9a4nidpf _6ad7idpf _nou7idpf _1nc9idpf _i6wbidpf _1fgoidpf _170zidpf _1a3lidpf _1e0c1txw"
    ])}>
    <div data-testid="header">Header</div>
    <div data-testid="child">Body</div>
  </div>);
