/* .tmp-swc-descendant-attribute-selector-1764040764498-54d00148f97c3.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const wrapper = null;
export const Example = ()=>(<div className={ax([
        "_1e0c1txw _1fqfidpf _5legidpf _147gidpf _1ydpidpf _1jguidpf _4jztidpf _1ojvidpf _flkxidpf"
    ])}>
    <div data-testid="header">Header</div>
    <div data-testid="child">Body</div>
  </div>);
