/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
const styles = {
  container: "",
  fieldName: ""
};
const labelStyles = null;
export const Component = () => <label className={ax([])}>
    <div xcss={styles.container}>content</div>
  </label>;
