/* .tmp-swc-xcss-css-map-atlaskit-1764484173164-da7046b72ce39.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    container: "_ca0qdbr4 _u5f3dbr4 _n3tddbr4 _irr3o84u _d0altlke",
    fieldName: "_16jlkb7n"
};
const labelStyles = null;
export const Component = ()=>(<label className={ax([
        "_1e0c1ule _1bsb1osq _80omtlke"
    ])}>
    <div xcss={styles.container}>content</div>
  </label>);
