/* .tmp-swc-complex-runtime-combo-1765437463825-989501df086f.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const fade = null;
const toneMap = {
    primary: "",
    danger: ""
};
const baseStyles = null;
const Wrapper = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Wrapper.displayName = "Wrapper";
}
export const Component = ()=>((<Wrapper className={ax([
        toneMap.primary
    ])}>
        <span className={ax([])}>
          combo
        </span>
      </Wrapper>));
