/* .tmp-swc-complex-runtime-combo-1763860974002-f68ebd7bcffa4.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const fade = null;
const toneMap = {
    primary: "_syazxbvz",
    danger: "_syaz14zx"
};
const baseStyles = null;
const Wrapper = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "_ca0qftgi _u5f3ftgi _n3tdftgi _19bvftgi _1l201r31 _cwctglyw _d7ut1o36",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Wrapper.displayName = "Wrapper";
}
export const Component = ()=>((<Wrapper className={ax([
        "_1wybdlk8 _72bc18cn _1qiwr3uz",
        toneMap.primary
    ])}>
        <span className={ax([
        "_y44v65d0 _aetr1vm8"
    ])}>
          combo
        </span>
      </Wrapper>));
