/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const fade = null;
const toneMap = {
	primary: "_9ad0xbvz",
	danger: "_9ad014zx",
};
const baseStyles = null;
const Wrapper = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr) => {
	if (__cmplp.innerRef) {
		throw new Error("Please use 'ref' instead of 'innerRef'.");
	}
	return (
		<C
			{...__cmplp}
			style={__cmpls}
			ref={__cmplr}
			className={ax(["_gq7jftgi _f1qkglyw", __cmplp.className])}
		/>
	);
});
if (process.env.NODE_ENV !== "production") {
	Wrapper.displayName = "Wrapper";
}
export const Component = () => (
	<Wrapper className={ax(["_1knudlk8 _1rr818cn _m4k5r3uz", toneMap.primary])}>
		<span className={ax(["_yrq0idpf _1exukb7n", "_bexg65d0 _1qji1vm8"])}>combo</span>
	</Wrapper>
);
