/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix } from "@compiled/react/runtime";
import React from "react";
import { Box } from "@atlaskit/primitives/compiled";
const styles = {
	avatarItemWrapper: "_18u0yjp0 _u5f3ftgi",
	container: "_4cvr1h6o _1e0c1txw _bfhk1hxd",
	text: "_1wybdlk8 _k48p8n31 _syazalr3",
};
export const Component = ({ name, picture }) => {
	return (
		<Box xcss={styles.avatarItemWrapper}>
			<div className={styles.container()}>
				<img src={picture} alt={name} />
				<span className={styles.text()}>{name}</span>
			</div>
		</Box>
	);
};
export default Component;
