/* .tmp-swc-css-imported-value-1765408336243-a26efc518a2ec.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { color } from './tokens';
const styles = null;
export const Component = ()=><div className={ax([])}>Hello</div>;
