/* .tmp-swc-css-imported-value-1764484166512-6fd07483ada51.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { color } from './tokens';
const styles = null;
export const Component = ()=><div className={ax([
        "_syaz5scu"
    ])}>Hello</div>;
