/* .tmp-swc-styled-dynamic-token-flex-basis-1765317766522-986443fa1da28.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const ListItem = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { isCompact: isCompact, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax([
        "",
        __cmplp.isCompact ? "_osiyu43s" : "_osiy1r8g",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    ListItem.displayName = "ListItem";
}
export const Component = ({ isCompact })=>(<ListItem isCompact={isCompact}>
    <div>Content</div>
  </ListItem>);
