/* .tmp-swc-css-element-existing-className-1765439410895-e932ce12d8569.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=>(<div className={ax([
        "legacy"
    ])}>
    hello world
  </div>);
