/* .tmp-swc-css-element-existing-className-1763860974672-8cd70c7db5c3c.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=>(<div className={ax([
        "_syaz15td _bfhk1n88",
        "legacy"
    ])}>
    hello world
  </div>);
