/* .tmp-swc-columns-container-minheight-stack-1764713725728-a21b867aa6009.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const layout = {
    columnMargin: 6
};
const sharedStyles = {
    columnWithMarginWidth: 270 + layout.columnMargin * 2,
    zIndex: {
        boardBorders: 90
    },
    columnFixedWidth: 270,
    columnMinWidth: 150,
    columnHeaderHeight: 48
};
const fg = ()=>false;
export const Component = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { isFlexible: isFlexible, isSwimlaneMode: isSwimlaneMode, shouldShowSampleProjectDataNudge: shouldShowSampleProjectDataNudge, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax([
        "_wij21bp4 _16jlkb7n _1o9zkb7n _i0dl1wug",
        __cmplp.isFlexible ? "_1e0c11p5" : "_1e0c1txw",
        !__cmplp.isFlexible ? "_yv0eglyw" : "_yv0e16td",
        fg('avoid_board_scroll_container_style_changes') ? "_1tke1osq" : "_1tkei63v",
        __cmplp.shouldShowSampleProjectDataNudge && "_1bsb1ris",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Component.displayName = "Component";
}
export default Component;
