/* .tmp-swc-css-imported-shorthand-dynamic-1765439411230-3dc1ed4e847ec.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { padding, outline } from './external';
const styles = null;
export const Component = ()=><div className={ax([])} style={{
        "--_oex9l5": ix(outline)
    }}/>;
