/* .tmp-swc-css-imported-shorthand-dynamic-1763762852755-397912a3876a9.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { padding, outline } from './external';
const styles = null;
export const Component = ()=><div className={ax([
        "_1yt46vxg"
    ])} style={{
        "--_oex9l5": ix(outline)
    }}/>;
