/* .tmp-swc-styled-conditional-classes-1763944831654-62f7ad730a481.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const Item = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { isClickable: isClickable, spaced: spaced, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax([
        "_nt751r31 _1dit1r31 _49pcglyw _ksodglyw _1hvw1o36 _4hz81o36",
        __cmplp.isClickable ? "_80omtlke" : "_80om1wug",
        __cmplp.isClickable ? "_jomr5scu _irr35scu" : "_jomr18uv _irr318uv",
        __cmplp.spaced ? "_1mizidpf _d4l71l7b _8jx7idpf _1ko91l7b" : "_1mizidpf _d4l7idpf _8jx7idpf _1ko9idpf",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Item.displayName = "Item";
}
export const Component = ({ isClickable, spaced })=>(<Item isClickable={isClickable} spaced={spaced}>
    Content
  </Item>);
