/* .tmp-swc-styled-conditional-classes-1765408353783-d991109f7a81f.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const Item = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { isClickable: isClickable, spaced: spaced, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax([
        "",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Item.displayName = "Item";
}
export const Component = ({ isClickable, spaced })=>(<Item isClickable={isClickable} spaced={spaced}>
    Content
  </Item>);
