/* .tmp-swc-double-export-1765439415181-99e980e42b991.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const sharedClass = null;
const hoverHighlight = null;
export const first = sharedClass;
export const second = sharedClass;
export { sharedClass as default };
export const Example = ()=>(<div>
    <span className={ax([])}>object styles</span>
    <span className={ax([])}>template styles</span>
  </div>);
