/* .tmp-swc-double-export-1763963508173-f5f29cb847ff4.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const sharedClass = null;
const hoverHighlight = null;
export const first = sharedClass;
export const second = sharedClass;
export { sharedClass as default };
export const Example = ()=>(<div>
    <span className={ax([
        "_1wybdlk8 _syaz15td _bfhkqgb6"
    ])}>object styles</span>
    <span className={ax([
        "_k48p8n31 _30l31q9v"
    ])}>template styles</span>
  </div>);
