/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
const sharedClass = null;
export const first = sharedClass;
export const second = sharedClass;
export { sharedClass as default };
