/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _2 = "._ajmmnqa1{text-decoration-style:solid}";
const _1 = "._1hmsglyw{text-decoration-line:none}";
const _ = "._4bfu18uv{text-decoration-color:initial}";
const base = null;
export const Component = () => <CC>
  <CS>{[_, _1, _2]}</CS>
  {<div className={ax(["_4bfu18uv _1hmsglyw _ajmmnqa1"])}>Hello</div>}
</CC>;
