/* in.tsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
const Component = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    flag,
    other,
    ...__cmpldp
  } = __cmplp;
  return <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax(["_ca0qidpf _u5f3i2wt _n3tdidpf _19bvi2wt _kqswh2mm", __cmplp.flag && "_4t3i19bv", __cmplp.other && "_4bfu1r31 _1hmsglyw _ajmmnqa1 _bfhk32ev", __cmplp.className])} />;
});
if (process.env.NODE_ENV !== 'production') {
  Component.displayName = 'Component';
}
export default Component;
