/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix } from "@compiled/react/runtime";
import { SimpleTag as Tag } from '@atlaskit/tag';
import React from 'react';
// eslint-disable-next-line @atlaskit/design-system/no-emotion-primitives – to be migrated to @atlaskit/primitives/compiled

const styles = {
  tag: ""
};
export function TagComponent({
  children,
  color
}) {
  return <Tag color={color} className={ax([styles.tag])}>
			{children}
		</Tag>;
}
