/* .tmp-swc-unicode-em-dash-cssmap-1765317768082-482d7084c8d6f.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import { SimpleTag as Tag } from '@atlaskit/tag';
import React from 'react';
const styles = {
    tag: "_ca0q1y44 _u5f3ftgi _n3td1y44 _19bvftgi _2rko1l7b _19it14it _1e0c1o8l _1wyb1crf _k48p8n31 _1p1dangw"
};
export function TagComponent({ children, color }) {
    return (<Tag color={color} className={ax([
        styles.tag
    ])}>
			{children}
		</Tag>);
}
