/* .tmp-swc-unicode-em-dash-cssmap-1765408361229-de37544469745.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import { SimpleTag as Tag } from '@atlaskit/tag';
import React from 'react';
const styles = {
    tag: ""
};
export function TagComponent({ children, color }) {
    return (<Tag color={color} className={ax([
        styles.tag
    ])}>
			{children}
		</Tag>);
}
