/* .tmp-swc-styled-tagged-template-literal-1764625078654-60947756f4821.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const StyledDiv = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "_syaz1my7 _30l3r3uz",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    StyledDiv.displayName = "StyledDiv";
}
export const Component = ()=><StyledDiv>Hover me</StyledDiv>;
