/* .tmp-swc-styled-template-dynamic-1763762858689-0e7b0c981ed7d.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const StyledButton = forwardRef(({ as: C = "button", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { primary: primary, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax([
        "_ca0qftgi _u5f37vkz _n3tdftgi _19bv7vkz _19itglyw _2rko1y44 _syazu67f _1wybdlk8 _1j55105o _j5dh13gf",
        __cmplp.primary ? "_bfhk13q2" : "_bfhk17nt",
        __cmplp.primary ? "_irr31xek" : "_irr31osi",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    StyledButton.displayName = "StyledButton";
}
function App() {
    return (<div>
      <StyledButton primary>Primary Button</StyledButton>
      <StyledButton>Secondary Button</StyledButton>
    </div>);
}
