/* .tmp-swc-media-const-assertion-1764733731970-43f34c48a2f7d.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const media = {
    above: {
        xs: '@media (min-width: 30rem)'
    } as const
};
const styles = null;
export const Component = ()=><div className={ax([
        "_1lv75scu"
    ])}>hi</div>;
