/* .tmp-swc-styled-production-1763860980899-db6d530ba5b0f.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
export const Styled = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "_syaz5scu",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Styled.displayName = "Styled";
}
