/* .tmp-swc-css-transition-decimal-normalization-1765317762298-3a8dd36d53241.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=><div className={ax([
        "_v5641czr"
    ])}/>;
