/* .tmp-swc-css-transition-decimal-normalization-1763963507507-03885d0236a6b.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=><div className={ax([
        "_v5641czr"
    ])}/>;
