/* .tmp-swc-css-transition-decimal-normalization-1765437466865-a55c6685ad1d4.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=><div className={ax([])}/>;
