/* .tmp-swc-css-transition-decimal-normalization-1765439413331-719974288042d.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=><div className={ax([])}/>;
