/* .tmp-swc-css-transition-decimal-normalization-1764358657005-0cced747bdc0b.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=><div className={ax([
        "_v5641czr"
    ])}/>;
