/* .tmp-swc-cssmap-simple-dotted-1764023675501-29e43ee66e44c.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    container: "_1e0c1txw",
    textBold: "_syazwwip"
};
export const Component = ()=>(<div className={ax([
        styles.container
    ])}>
    <span className={ax([
        styles.textBold
    ])}>Content</span>
  </div>);
