/* .tmp-swc-cssmap-simple-dotted-1765439414323-990c81e2f2774.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    container: "",
    textBold: ""
};
export const Component = ()=>(<div className={ax([
        styles.container
    ])}>
    <span className={ax([
        styles.textBold
    ])}>Content</span>
  </div>);
