/* .tmp-swc-css-media-query-many-rules-1765437465973-a0cbc8fda5dcf.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
export const styles = null;
