/* .tmp-swc-css-media-query-many-rules-1765408337183-8ebe4d2d635b3.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
export const styles = null;
