/* .tmp-swc-css-media-query-many-rules-1764625072199-ceea849fc993b.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
export const styles = null;
