/* .tmp-swc-css-media-query-many-rules-1764484166742-c42834783f656.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
export const styles = null;
