/* .tmp-swc-css-media-query-many-rules-1765955939185-441b61507b8b4.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
export const styles = null;
