/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
const fadeIn = null;
const animatedStyles = null;
export const Component = ({
  children
}) => {
  return <div className={ax([])}>{children}</div>;
};
