/* .tmp-swc-keyframes-with-css-1763972245772-33c7b4de79675.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const fadeIn = null;
const animatedStyles = null;
export const Component = ({ children })=>{
    return <div className={ax([
        "_y44v1mvf _ca0q7vkz _u5f37vkz _n3td7vkz _19bv7vkz _2rko1y44 _bfhku67f"
    ])}>{children}</div>;
};
