/* .tmp-swc-keyframes-with-css-1765408344540-eec239dcaba89.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const fadeIn = null;
const animatedStyles = null;
export const Component = ({ children })=>{
    return <div className={ax([])}>{children}</div>;
};
