/* .tmp-swc-css-transition-decimal-normalization-extract-1765437466907-bccc9225c349d.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=><div className={ax([])}/>;
