/* .tmp-swc-css-transition-decimal-normalization-extract-1764368029503-8f2af543286a9.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=><div className={ax([
        "_v5641czr"
    ])}/>;
