/* .tmp-swc-css-transition-decimal-normalization-extract-1763944827641-ad7440f2acc15.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=><div className={ax([
        "_v5641czr"
    ])}/>;
