/* .tmp-swc-styled-dynamic-token-color-1765437474326-5a1735ff2847.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const ExpiryDateContainer = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { dueInWeek: dueInWeek, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax([
        "",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    ExpiryDateContainer.displayName = "ExpiryDateContainer";
}
export const Component = ({ dueInWeek })=>(<ExpiryDateContainer dueInWeek={dueInWeek}>Content</ExpiryDateContainer>);
