/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
	container:
		"_2rko1l7b _bozg1y44 _y4ti1y44 _1e0c116y _vchhusvi _kqswpfqs _1kz6184x _1reo15vq _18m915vq",
	containerSubtle: "_1cwg1n1a",
	text: "_ect49sn6 _1wyb1skh _zg8l4jg8 _k48p8n31 _vwz47vkz _1reo15vq _18m915vq _1bto1l2s _1p1dangw _o5721q9c",
	customLetterspacing: "_1dyz9vsi",
	bgBoldDefault: "_bfhkdpcy",
	bgBoldInprogress: "_bfhk1g3l",
	bgBoldMoved: "_bfhk15d1",
	bgBoldNew: "_bfhkve0f",
	bgBoldRemoved: "_bfhkzi9y",
	bgBoldSuccess: "_bfhk1wgd",
	bgSubtleDefault: "_bfhk118l",
	bgSubtleInprogress: "_bfhk118l",
	bgSubtleMoved: "_bfhk118l",
	bgSubtleNew: "_bfhk118l",
	bgSubtleRemoved: "_bfhk118l",
	bgSubtleSuccess: "_bfhk118l",
	borderSubtleDefault: "_19itqdlt",
	borderSubtleInprogress: "_19it1ker",
	borderSubtleMoved: "_19ito858",
	borderSubtleNew: "_19itu7px",
	borderSubtleRemoved: "_19it9pct",
	borderSubtleSuccess: "_19it1oxd",
	textSubtle: "_syaz15ve",
	textBold: "_syazjljo",
};
function Lozenge({ children, isBold = false, appearance = "default" }) {
	const appearanceStyle = isBold ? "Bold" : "Subtle";
	const bgClass = `bg${appearanceStyle}${appearance.charAt(0).toUpperCase() + appearance.slice(1)}`;
	const textClass = `text${appearanceStyle}`;
	return (
		<span className={styles.container()}>
			<span className={styles[bgClass]()}>
				<span className={styles.text()}>
					<span className={styles.customLetterspacing()}>
						<span className={styles[textClass]()}>{children}</span>
					</span>
				</span>
			</span>
		</span>
	);
}
export default Lozenge;
