/* .tmp-swc-lozenge-cssmap-complex-1765437469748-a0bd8a97ce84c.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    container: "",
    containerSubtle: "",
    text: "",
    customLetterspacing: "",
    bgBoldDefault: "",
    bgBoldInprogress: "",
    bgBoldMoved: "",
    bgBoldNew: "",
    bgBoldRemoved: "",
    bgBoldSuccess: "",
    bgSubtleDefault: "",
    bgSubtleInprogress: "",
    bgSubtleMoved: "",
    bgSubtleNew: "",
    bgSubtleRemoved: "",
    bgSubtleSuccess: "",
    borderSubtleDefault: "",
    borderSubtleInprogress: "",
    borderSubtleMoved: "",
    borderSubtleNew: "",
    borderSubtleRemoved: "",
    borderSubtleSuccess: "",
    textSubtle: "",
    textBold: ""
};
function Lozenge({ children, isBold = false, appearance = 'default' }) {
    const appearanceStyle = isBold ? 'Bold' : 'Subtle';
    const bgClass = `bg${appearanceStyle}${appearance.charAt(0).toUpperCase() + appearance.slice(1)}`;
    const textClass = `text${appearanceStyle}`;
    return (<span className={styles.container()}>
      <span className={styles[bgClass]()}>
        <span className={styles.text()}>
          <span className={styles.customLetterspacing()}>
            <span className={styles[textClass]()}>
              {children}
            </span>
          </span>
        </span>
      </span>
    </span>);
}
export default Lozenge;
