/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
const rowGapMap = {
  'space100': "",
  'space200': "",
  'space300': ""
};
const columnGapMap = {
  'space100': "",
  'space200': "",
  'space300': ""
};
const justifyContentMap = {
  start: "",
  center: "",
  end: ""
};
const alignItemsMap = {
  start: "",
  center: "",
  end: ""
};
const styles = {
  root: ""
};

/**
 * __Flex__
 *
 * `Flex` is a primitive component that implements the CSS Flexbox API.
 */
const Flex = props => {
  const {
    as: Component = 'div',
    alignItems,
    justifyContent,
    gap,
    columnGap,
    rowGap,
    children
  } = props;
  return <Component className={`
				${styles.root()} 
				${gap ? columnGapMap[gap]() : ''}
				${columnGap ? columnGapMap[columnGap]() : ''}
				${gap ? rowGapMap[gap]() : ''}
				${rowGap ? rowGapMap[rowGap]() : ''}
				${alignItems ? alignItemsMap[alignItems]() : ''}
				${justifyContent ? justifyContentMap[justifyContent]() : ''}
			`.trim()}>
			{children}
		</Component>;
};
Flex.displayName = 'Flex';
export default Flex;
