/* .tmp-swc-strip-runtime-binding-fallback-1765404347999-6ee673f7918a.jsx generated by @compiled/babel-plugin v0.38.1 */
;
const learnMoreLink = 'https://www.atlassian.com/software/compass';
export const Component = ()=><div>{learnMoreLink}</div>;
