/* .tmp-swc-strip-runtime-binding-fallback-1765439421961-f56cf1ff1227d.jsx generated by @compiled/babel-plugin v0.38.1 */
;
const learnMoreLink = 'https://www.atlassian.com/software/compass';
export const Component = ()=><div>{learnMoreLink}</div>;
