/* .tmp-swc-strip-runtime-binding-fallback-1765437472749-a3b6316a1f87a.jsx generated by @compiled/babel-plugin v0.38.1 */
;
const learnMoreLink = 'https://www.atlassian.com/software/compass';
export const Component = ()=><div>{learnMoreLink}</div>;
