/* .tmp-swc-strip-runtime-binding-fallback-1766020320283-99e33844fe50b.jsx generated by @compiled/babel-plugin v0.38.1 */
;
const learnMoreLink = 'https://www.atlassian.com/software/compass';
export const Component = ()=><div>{learnMoreLink}</div>;
