/* .tmp-swc-strip-runtime-binding-fallback-1765317765708-d3ccb0be42391.jsx generated by @compiled/babel-plugin v0.38.1 */
;
const learnMoreLink = 'https://www.atlassian.com/software/compass';
export const Component = ()=><div>{learnMoreLink}</div>;
