/* .tmp-swc-strip-runtime-binding-fallback-1765408351777-dd55e9237ec55.jsx generated by @compiled/babel-plugin v0.38.1 */
;
const learnMoreLink = 'https://www.atlassian.com/software/compass';
export const Component = ()=><div>{learnMoreLink}</div>;
