/* .tmp-swc-styled-with-comments-1765930120756-1fe388158a224.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
const badgeStyles = null;
const PopUpListItem = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "_2rko12b0 _ca0qftgi _u5f31crf _n3tdftgi _19bv1crf _bfhkcdhy _syaz15cr _p12fnklw",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    PopUpListItem.displayName = "PopUpListItem";
}
const PopUpList = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "_zulpftgi _19pkftgi _1e0c1txw",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    PopUpList.displayName = "PopUpList";
}
export const Component = ({ services = [] })=>(<div>
    <span className={ax([
        "_4cvr1h6o _1e0c116y _1wyb19bv _k48pni7l _1p1dangw _syaz5ac6 _1dyz1m6u _1kt91mp2 _eid31y44"
    ])}>{services.length} services</span>
    <PopUpList>
      <PopUpListItem>{services.join(', ') || 'No services'}</PopUpListItem>
    </PopUpList>
  </div>);
