/* .tmp-swc-css-and-keyframes-1765408333801-cb779afe608b9.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const fadeIn = null;
const styles = null;
export const Component = ()=><div className={ax([])}>Hello</div>;
