/* .tmp-swc-css-and-keyframes-1764034566834-729f575231537.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const fadeIn = null;
const styles = null;
export const Component = ()=><div className={ax([
        "_y44v16rn"
    ])}>Hello</div>;
