/* .tmp-swc-styled-conditional-padding-1764364392590-c4f4f98956ed7.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const PaddingWrapper = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { isSummaryView: isSummaryView, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax([
        "",
        __cmplp.isSummaryView ? "_ca0q1y44 _u5f3ftgi _n3tdftgi _19bvidpf" : "_ca0q1y44 _u5f3ftgi _n3tdftgi _19bv1crf",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    PaddingWrapper.displayName = "PaddingWrapper";
}
export const Component = ()=><PaddingWrapper isSummaryView={false}>Content</PaddingWrapper>;
