/* .tmp-swc-responsive-show-extra-brace-1763963510588-a0ad656c6e5d8.jsx generated by @compiled/babel-plugin v0.38.1 */
;
const styles = {
    default: {
        display: 'none'
    },
    'above.xs': {
        '@media (min-width: 30rem)': {
            display: 'revert'
        }
    },
    'below.sm': {
        '@media not all and (min-width: 48rem)': {
            display: 'revert'
        }
    }
};
export const Show = ({ above, below, children })=>{
    return (<div className={ax([
        "_1e0cglyw",
        above && "_rs4eglyw _spsm19ly _4lz619ly",
        below && "_rs4eglyw _spsm19ly _4lz619ly"
    ])}>
			{children}
		</div>);
};
