/* .tmp-swc-responsive-show-extra-brace-1765439421282-7391f723ff904.jsx generated by @compiled/babel-plugin v0.38.1 */
;
const styles = {
    default: {
        display: 'none'
    },
    'above.xs': {
        '@media (min-width: 30rem)': {
            display: 'revert'
        }
    },
    'below.sm': {
        '@media not all and (min-width: 48rem)': {
            display: 'revert'
        }
    }
};
export const Show = ({ above, below, children })=>{
    return (<div className={ax([
        above && "",
        below && ""
    ])}>
			{children}
		</div>);
};
