/* .tmp-swc-styled-nested-table-dynamic-1764018976991-73d2d77ffec75.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
type Props = {
    enabled: boolean;
};
export const Component = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { enabled: enabled, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax([
        "",
        __cmplp.enabled ? "_1d34idpf _1j4widpf _ipzridpf _wsabidpf _1h15idpf _4awn1l7b _1s6didpf _18iyidpf _1bsbys9h _v4pn1ule _1xdnt94y _1o2g1wug _16lkusic _17pe1wou _1n631y44 _13dh1osq" : "_1d34idpf _1j4widpf _ipzridpf _wsabidpf _1h15idpf _18iyidpf _v4pn1ule _1o2g1wug",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Component.displayName = "Component";
}
export const Example = ()=><Component enabled/>;
