/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const gridSize = 8;
const HeadingCellWrapper = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr) => {
	if (__cmplp.innerRef) {
		throw new Error("Please use 'ref' instead of 'innerRef'.");
	}
	const { first, last, ...__cmpldp } = __cmplp;
	return (
		<C
			{...__cmpldp}
			style={__cmpls}
			ref={__cmplr}
			className={ax([
				"_ca0qidpf _u5f3idpf _n3tdidpf _19bvidpf _1e0c1o8l",
				__cmplp.first ? "_19bvftgi" : "_19bv1y44",
				__cmplp.last ? "_u5f3ftgi" : "_u5f31y44",
				__cmplp.className,
			])}
		/>
	);
});
if (process.env.NODE_ENV !== "production") {
	HeadingCellWrapper.displayName = "HeadingCellWrapper";
}
export const Component = ({ first, last }) => (
	<HeadingCellWrapper first={first} last={last}>
		content
	</HeadingCellWrapper>
);
