/* .tmp-swc-styled-heading-cell-wrapper-1765408355747-051571e991f06.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const gridSize = 8;
const HeadingCellWrapper = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { first: first, last: last, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax([
        "",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    HeadingCellWrapper.displayName = "HeadingCellWrapper";
}
export const Component = ({ first, last })=>(<HeadingCellWrapper first={first} last={last}>
    content
  </HeadingCellWrapper>);
