/* .tmp-swc-styled-dynamic-props-1765317766459-3e1aed5392cb6.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const Dot = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={{
        ...__cmpls,
        "--_r3iodj": ix(__cmplp.y, "px"),
        "--_gzeubk": ix(__cmplp.x, "px")
    }} ref={__cmplr} className={ax([
        "_2rko1q3h _154i1yuh _1ltv9q3e _kqswstnw _1bsb19bv _4t3i19bv _t9ecni0c _bfhk13q2",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Dot.displayName = "Dot";
}
export const Component = ()=><Dot x={0} y={0}/>;
