/* .tmp-swc-css-token-font-shorthand-1763972244564-395a02bf868a.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=><div className={ax([
        "_2rko1mok _11c8dcr7 _bfhk1xt1 _syazzjem"
    ])}/>;
