/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
import { cx } from '@compiled/react';
const listStyles = {
  root: "",
  popupContainer: ""
};
export function Component({
  children
}) {
  return <div xcss={cx(listStyles.root, listStyles.popupContainer)}>
			{children}
		</div>;
}
