/* .tmp-swc-cx-with-cssmap-1765437467746-c2b71a2602e65.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
import { cx } from '@compiled/react';
const listStyles = {
    root: "",
    popupContainer: ""
};
export function Component({ children }) {
    return (<div xcss={cx(listStyles.root, listStyles.popupContainer)}>
			{children}
		</div>);
}
