/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
// Nested pseudo selector using "n+2" form that currently hashes differently between Babel and SWC.
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
export const Body = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["", __cmplp.className])} />;
});
if (process.env.NODE_ENV !== 'production') {
  Body.displayName = 'Body';
}
