/* .tmp-swc-tokens-nested-selectors-1763969933822-84b23a46b6315.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const Wrapper = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "_2x4gze3t _12hv12x7 _x5bdze3t _1rgf12x7 _1t2qazsu",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Wrapper.displayName = "Wrapper";
}
export const Component = ()=>(<Wrapper>
		<label>
			<input type="checkbox"/>
		</label>
	</Wrapper>);
