/* .tmp-swc-css-transform-rotate-1764109957286-1b95b9ed6ba0d.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
export const styles = null;
const test = <div className={ax([
    "_t9ec14w8"
])}/>;
