/* .tmp-swc-css-transform-rotate-1765408339158-41bb14dc9246b.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
export const styles = null;
const test = <div className={ax([])}/>;
