/* .tmp-swc-ts-as-cast-1765439428691-6c154a9503258.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
type Props = {
    lineclamp: number | 'auto';
};
const ClampedHighlight = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { lineclamp: lineclamp, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={{
        ...__cmpls,
        "--_xci7r5": ix(`${(__cmplp.lineclamp as number) * 1.42857142857143}em`)
    }} ref={__cmplr} className={ax([
        "",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    ClampedHighlight.displayName = "ClampedHighlight";
}
export const Example = (props: Props)=>(<ClampedHighlight {...props}>example</ClampedHighlight>);
