/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
const baseRow = null;
const wideRow = null;
const narrowRow = null;
export const Component = ({
  narrow
}) => <div className={ax(["_4t3izwfg _19pku2gc", narrow ? "_1bsbx19p" : "_1bsb1osq"])}>skeleton</div>;
