/* .tmp-swc-css-conditional-css-binding-1763762852529-6274f68ac6a58.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const baseRow = null;
const wideRow = null;
const narrowRow = null;
export const Component = ({ narrow })=>(<div className={ax([
        "_19pku2gc _4t3izwfg",
        narrow ? "_1bsbx19p" : "_1bsb1osq"
    ])}>skeleton</div>);
