/* .tmp-swc-styled-length-pc-1765752976950-d47d9da448a7c.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const Box = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "_1bsb4tsx",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Box.displayName = "Box";
}
export const Component = ()=><Box>content</Box>;
