/* .tmp-swc-columns-container-shared-styles-1765439408529-1e295352e2672.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import sharedStyles from './sharedStyles';
const fg = ()=>false;
export const Component = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { isFlexible: isFlexible, isSwimlaneMode: isSwimlaneMode, shouldShowSampleProjectDataNudge: shouldShowSampleProjectDataNudge, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax([
        "",
        __cmplp.shouldShowSampleProjectDataNudge && "",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Component.displayName = "Component";
}
export default Component;
