/* .tmp-swc-minheight-calc-fg-stack-1764034570386-573d6b15d140c.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { fg } from '@atlassian/jira-feature-gating';
const Comp = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { isFlexible: isFlexible, isSwimlaneMode: isSwimlaneMode, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax([
        "",
        fg('avoid_board_scroll_container_style_changes') ? "_1tke1osq" : "_1tkei63v",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Comp.displayName = "Comp";
}
export const Component = ()=><Comp isFlexible isSwimlaneMode={false}/>;
