/* in.tsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix } from "@compiled/react/runtime";
import React, { useMemo, useCallback, useState, useEffect, useRef, Component, type ElementRef, type ReactElement, type MouseEvent, memo } from 'react';
import intersection from 'lodash/intersection';
import isArray from 'lodash/isArray';
import join from 'lodash/join';
import round from 'lodash/round';
import { combine } from '@atlaskit/pragmatic-drag-and-drop/combine';
import { draggable } from '@atlaskit/pragmatic-drag-and-drop/element/adapter';
import { N300, B500, N500, N0, N1000, B700 } from '@atlassian/jira-polaris-lib-color-palette/src/ui/colors/index.tsx';
import { fireUIAnalytics, useAnalyticsEvents } from '@atlassian/jira-product-analytics-bridge';
import { fg } from '@atlassian/jira-feature-gating';
import { DRAGGABLE_ITEM_TYPE } from '../../common/constants/index.tsx';
import { useMatrixActions } from '../../controllers/index.tsx';
import { useClusteredItemRendererComponent, useDraggableBubbleComponent, useItemRendererComponent } from '../../controllers/selectors/components-hooks.tsx';
import { useRelativeItemCenterPosition, useZAxisPositionForItems } from '../../controllers/selectors/positions-hooks.tsx';
import { useHoveredItems, useHighlightedItem, useSelectedItems } from '../../controllers/selectors/ui-hooks.tsx';
import { sendMatrixSingularDragOperationStarted, sendMatrixGroupDragOperationStarted, sendMatrixSingularDragOperationEnded, sendMatrixGroupDragOperationEnded, sendMatrixSingletonBubbleClicked, sendMatrixGroupBubbleClicked } from '../../services/pendo/index.tsx';
import type { ItemId, ItemProps, ClusteredItemProps, CenterPosition, ItemWrapperProps, DraggableBubbleProps } from '../../types.tsx';
type BubbleProps = {
  itemIds: ItemId[];
  isItemsDragDisabled?: boolean;
};
type BubblePositioningComponentState = {
  containerRef: ElementRef<'div'> | undefined;
};
type BubblePositioningComponentProps = {
  isHovered: boolean;
  isDragging: boolean;
  centerPosition: CenterPosition;
  zPosition: number;
  renderChildren: () => ReactElement;
};

// eslint-disable-next-line jira/react/no-class-components
class BubblePositioningComponent extends Component<BubblePositioningComponentProps, BubblePositioningComponentState> {
  state = {
    containerRef: undefined
  };
  shouldComponentUpdate(nextProps: BubblePositioningComponentProps) {
    return nextProps.renderChildren !== this.props.renderChildren;
  }
  componentDidUpdate(prevProps: Readonly<BubblePositioningComponentProps>): void {
    if ((this.props.zPosition !== prevProps.zPosition || this.props.centerPosition !== prevProps.centerPosition) && this.state.containerRef) {
      this.updateStylesForProps(this.state.containerRef, this.props);
    }
  }
  updateStylesForProps = (ref: ElementRef<'div'> | null, {
    zPosition,
    centerPosition
  }: BubblePositioningComponentProps) => {
    if (ref) {
      const {
        style
      } = ref;
      style.width = `${zPosition}px`;
      style.height = `${zPosition}px`;
      style.left = `calc(${centerPosition.left}% - ${zPosition / 2}px)`;
      style.top = `calc(${centerPosition.top}% - ${zPosition / 2}px)`;
      // bucketed z positions are 30-45-60-75, assigning z index with inverse proportion
      // will make sure that smaller bubbles are always on top of bigger bubbles,
      // hence all of the bubbles will be visible
      style.zIndex = Math.ceil((75 - zPosition) / 15 + 2).toString();
    }
  };
  setContainerRef = (containerRef: ElementRef<'div'>) => {
    this.setState({
      containerRef
    });
    this.updateStylesForProps(containerRef, this.props);
  };
  render() {
    const {
      renderChildren,
      isHovered,
      isDragging
    } = this.props;
    return <BubblePositioningContainer isDragging={isDragging} ref={this.setContainerRef} isHovered={isHovered}>
				{renderChildren()}
			</BubblePositioningContainer>;
  }
}
type DefaultBubbleComponentProps = {
  color: string;
  borderColor: string | string[];
} & ItemProps;
export const DefaultBubbleComponent = ({
  color,
  borderColor,
  isHovered,
  isSelected,
  isDragging,
  isHighlighted
}: DefaultBubbleComponentProps) => <BubbleContentWrapper data-testid="polaris-lib-matrix.ui.bubble.default-bubble-component-wrapper" data-component-selector="bubble-content-wrapper-phaV">
		{!isDragging && <BubbleAurora isSelected={isSelected} isHighlighted={isHighlighted} borderColor={borderColor} color={color} isHovered={isHovered} />}
		<DefaultBubbleContainer color={color} borderColor={borderColor} isHovered={isHovered} isSelected={isSelected} isHighlighted={isHighlighted} isDragging={isDragging} />
	</BubbleContentWrapper>;
type DefaultBubbleClusterComponentProps = {
  color: string;
  borderColor: string | string[];
} & ClusteredItemProps;
const getItemCountString = (items: string[]): string => {
  if (items.length < 1000) {
    return String(items.length);
  }
  return `${round(items.length / 1000, 1)}K`;
};
export const DefaultBubbleClusterComponent = ({
  items,
  color,
  borderColor,
  isHovered,
  isSelected,
  isDragging,
  isHighlighted
}: DefaultBubbleClusterComponentProps) => <BubbleContentWrapper data-testid="polaris-lib-matrix.ui.bubble.default-bubble-cluster-wrapper" data-component-selector="bubble-content-wrapper-phaV">
		{!isDragging && <BubbleAurora isSelected={isSelected} isHighlighted={isHighlighted} borderColor={borderColor} color={color} isHovered={isHovered} />}
		<DefaultBubbleContainer color={color} borderColor={borderColor} isHovered={isHovered} isSelected={isSelected} isHighlighted={isHighlighted} isDragging={isDragging}>
			<span>{getItemCountString(items)}</span>
		</DefaultBubbleContainer>
	</BubbleContentWrapper>;
export const SimpleDefaultBubbleClusterComponent = ({
  items,
  isHovered,
  isSelected,
  isHighlighted
}: ClusteredItemProps) => <BubbleContentWrapper data-testid="polaris-lib-matrix.ui.bubble.simple-default-bubble-cluster-wrapper" data-component-selector="bubble-content-wrapper-phaV">
		<BubbleAurora isSelected={isSelected} isHighlighted={isHighlighted} color={N300} borderColor={N300} isHovered={isHovered} />
		<DefaultBubbleContainer color={N300} borderColor={N300} isHovered={isHovered} isSelected={isSelected} isHighlighted={isHighlighted}>
			<span>{getItemCountString(items)}</span>
		</DefaultBubbleContainer>
	</BubbleContentWrapper>;
export const SimpleDefaultBubbleComponent = ({
  isHovered,
  isSelected,
  isHighlighted
}: ItemProps) => <BubbleContentWrapper data-testid="polaris-lib-matrix.ui.bubble.simple-default-bubble-wrapper" data-component-selector="bubble-content-wrapper-phaV">
		<BubbleAurora isSelected={isSelected} isHighlighted={isHighlighted} color={N300} borderColor={N300} isHovered={isHovered} />
		<DefaultBubbleContainer color={N300} borderColor={N300} isHovered={isHovered} isSelected={isSelected} isHighlighted={isHighlighted} />
	</BubbleContentWrapper>;
export const SimpleDefaultBubbleWrapperComponent = (props: ItemWrapperProps) => <>{props.children}</>;
export const DraggableBubble = ({
  children,
  id,
  itemIds,
  onDragStart,
  onDragEnd,
  canDrop = true
}: DraggableBubbleProps) => {
  const {
    top,
    left
  } = useRelativeItemCenterPosition(id);
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (!ref.current) return undefined;
    const cleanupDragAndDrop = combine(draggable({
      element: ref.current,
      getInitialData() {
        return {
          id,
          itemIds,
          type: DRAGGABLE_ITEM_TYPE,
          top,
          left,
          canDrop
        };
      },
      onDragStart() {
        if (itemIds.length > 1) {
          sendMatrixGroupDragOperationStarted();
        } else {
          sendMatrixSingularDragOperationStarted();
        }
        onDragStart();
      },
      onDrop() {
        if (itemIds.length > 1) {
          sendMatrixGroupDragOperationEnded();
        } else {
          sendMatrixSingularDragOperationEnded();
        }
        onDragEnd();
      }
    }));
    return () => {
      cleanupDragAndDrop?.();
    };
  }, [canDrop, id, itemIds, left, onDragEnd, onDragStart, top]);
  return <DraggableBubbleWrapper data-testid="polaris-lib-matrix.ui.bubble.draggable-bubble-wrapper" ref={ref}>
			{children}
		</DraggableBubbleWrapper>;
};
export const Bubble = memo(({
  itemIds,
  isItemsDragDisabled
}: BubbleProps) => {
  const positioningId = itemIds[0];
  const [isDragging, setIsDragging] = useState(false);
  const toggleIsDragging = useCallback(() => setIsDragging(prev => !prev), []);
  const BubbleRenderComponent = useItemRendererComponent();
  const BubbleClusterRenderComponent = useClusteredItemRendererComponent();
  const DraggableBubbleComponentProvided = useDraggableBubbleComponent();
  const InnerBubbleComponent = BubbleRenderComponent || SimpleDefaultBubbleComponent;
  const InnerBubbleClusterComponent = BubbleClusterRenderComponent || SimpleDefaultBubbleClusterComponent;
  const DraggableBubbleComponent = fg('jpd-aurora-roadmap-inline-edit') ? DraggableBubbleComponentProvided || DraggableBubble : DraggableBubble;
  const centerPosition = useRelativeItemCenterPosition(positioningId);
  const zPosition = useZAxisPositionForItems(itemIds);
  const highlightedItem = useHighlightedItem();
  const hoveredItem = useHoveredItems();
  const selectedItems = useSelectedItems();
  const {
    createAnalyticsEvent
  } = useAnalyticsEvents();
  const [, actions] = useMatrixActions();
  const {
    setHoveredItems,
    setSelectedItems
  } = actions;
  const isHovered = useMemo(() => intersection(itemIds, hoveredItem?.items || []).length > 0, [hoveredItem?.items, itemIds]);
  const isSelected = useMemo(() => intersection(selectedItems || [], itemIds || []).length > 0, [itemIds, selectedItems]);
  const isHighlighted = useMemo(() => !!highlightedItem && itemIds.includes(highlightedItem), [itemIds, highlightedItem]);
  const setSelectionFromClickEvent = useCallback((e: MouseEvent<HTMLElement>) => {
    // do not propagate click event upwards to enable "outside-of-bubble-click" handling on the container
    e.stopPropagation();
    const analyticsAttributes = {
      bubbleType: 'single',
      multiSelect: e.shiftKey || e.metaKey || e.ctrlKey
    };
    if (itemIds.length > 1) {
      sendMatrixGroupBubbleClicked();
      analyticsAttributes.bubbleType = 'clustered';
    } else {
      sendMatrixSingletonBubbleClicked();
    }
    fireUIAnalytics(createAnalyticsEvent({
      action: 'clicked',
      actionSubject: 'icon'
    }), 'ideaBubble', analyticsAttributes);
    const selected = selectedItems ?? [];
    if (selected.length === 0) {
      if (e.shiftKey) return;
      setSelectedItems([...itemIds]);
    } else if (e.metaKey || e.ctrlKey) {
      // in case current bubble is already selected, filter out current ones first
      const otherSelected = [...selected.filter(id => !itemIds.includes(id))];
      setSelectedItems([...otherSelected, ...itemIds]);
    } else if (e.shiftKey) {
      setSelectedItems([...selected.filter(id => !itemIds.includes(id))]);
    } else {
      setSelectedItems([...itemIds]);
    }
  }, [setSelectedItems, selectedItems, itemIds, createAnalyticsEvent]);
  const setHover = useCallback(() => {
    setHoveredItems({
      items: itemIds,
      area: 'MATRIX'
    });
  }, [itemIds, setHoveredItems]);
  const clearHover = useCallback(() => {
    setHoveredItems(undefined);
  }, [setHoveredItems]);
  const renderInnerBubble = useCallback(() => {
    const InnerBubble = itemIds.length > 1 ? <InnerBubbleClusterComponent items={itemIds} isHovered={isHovered} isSelected={isSelected} isDragging={isDragging} isHighlighted={isHighlighted} /> : <InnerBubbleComponent id={positioningId} isHovered={isHovered} isSelected={isSelected} isDragging={isDragging} isHighlighted={isHighlighted} />;
    return isItemsDragDisabled ? InnerBubble : <DraggableBubbleComponent id={positioningId} itemIds={itemIds} onDragStart={toggleIsDragging} onDragEnd={toggleIsDragging}>
					{InnerBubble}
				</DraggableBubbleComponent>;
  },
  // eslint-disable-next-line react-hooks/react-compiler
  // eslint-disable-next-line react-hooks/exhaustive-deps
  [itemIds, positioningId, isSelected, isHovered, isDragging, isHighlighted]);
  return (
    // eslint-disable-next-line jsx-a11y/click-events-have-key-events, jsx-a11y/no-static-element-interactions, @atlassian/a11y/interactive-element-not-keyboard-focusable
    <div onMouseEnter={setHover} onMouseLeave={clearHover} onClick={setSelectionFromClickEvent}>
			<BubblePositioningComponent centerPosition={centerPosition} zPosition={zPosition} isHovered={isHovered} isDragging={isDragging} renderChildren={renderInnerBubble} />
		</div>
  );
});
const pulseAnimation = null;
const getConicGradient = (borderColor: string[]): string => {
  const segmentAngle = 360 / borderColor.length;

  // 0deg is at top center position, we want it at left center
  const angleShift = -90;
  const gradientSegments: string[] = [];
  const overflowSegments: string[] = [];
  borderColor.forEach((segmentColor, index) => {
    const startAngle = index * segmentAngle + angleShift;
    const endAngle = (index + 1) * segmentAngle + angleShift;
    if (startAngle >= 0) {
      gradientSegments.push(`${segmentColor} ${startAngle}deg ${endAngle}deg`);
    } else {
      overflowSegments.push(`${segmentColor} ${360 + startAngle}deg ${360}deg`);
      gradientSegments.push(`${segmentColor} ${0}deg ${endAngle}deg`);
    }
  });
  return join([...gradientSegments, ...overflowSegments], ', ');
};
const getBorderColor = (isHovered: boolean, borderColor: string | string[]) => {
  if (isArray(borderColor) && borderColor.length > 1) {
    return 'transparent';
  }
  let bc = borderColor;
  if (isArray(borderColor)) {
    [bc] = borderColor;
  } else if (isHovered) {
    bc = N500;
  }
  return bc;
};
const BORDER_THICKNESS = 3;

// eslint-disable-next-line @atlaskit/ui-styling-standard/no-styled -- To migrate as part of go/ui-styling-standard
const BubbleContentWrapper = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_2rko1rr0 _vchhusvi _kqswh2mm _bfhk18uv _1bsb1osq _4t3i1osq", __cmplp.className])} />;
});

// eslint-disable-next-line @atlaskit/ui-styling-standard/no-styled -- To migrate as part of go/ui-styling-standard
if (process.env.NODE_ENV !== 'production') {
  BubbleContentWrapper.displayName = 'BubbleContentWrapper';
}
const BubbleAurora = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    isHighlighted,
    isSelected,
    borderColor,
    ...__cmpldp
  } = __cmplp;
  return <C {...__cmpldp} style={{
    ...__cmpls,
    "--_dwe3mo": ix(B700),
    "--_ijaz3l": ix(B500),
    "--_zs9p45": ix(getConicGradient(
    // eslint-disable-next-line @atlaskit/ui-styling-standard/no-imported-style-values -- Ignored via go/DSP-18766
    isArray(__cmplp.borderColor) && __cmplp.borderColor.length > 0 ? __cmplp.borderColor : [N500])),
    "--_s99dce": ix(!__cmplp.isSelected && 'content-box, border-box')
  }} ref={__cmplr} className={ax(["_2rko1rr0 _vchhusvi _kqswstnw _1ltvidpf _154iidpf _1bsb1osq _4t3i1osq _1lrw174u _12vemgnk _ouxl1xdg _qjkj9dsr _1y1mxe2f _15i1scqs _1canymdr _nqoi12c5", __cmplp.isHighlighted ? "_bfhksfwi" : __cmplp.isSelected ? "_bfhk1fp5" : "_bfhk18uv", !__cmplp.isSelected && !__cmplp.isHighlighted ? "_1itktq9z" : "_1itkglyw", __cmplp.className])} />;
});

// eslint-disable-next-line @atlaskit/ui-styling-standard/no-styled -- To migrate as part of go/ui-styling-standard
if (process.env.NODE_ENV !== 'production') {
  BubbleAurora.displayName = 'BubbleAurora';
}
const DefaultBubbleContainer = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    isDragging,
    isHighlighted,
    isSelected,
    isHovered,
    borderColor,
    ...__cmpldp
  } = __cmplp;
  return <C {...__cmpldp} style={{
    ...__cmpls,
    "--_1r7z21x": ix(!__cmplp.isHighlighted && !__cmplp.isSelected && `${BORDER_THICKNESS}px solid ${getBorderColor(__cmplp.isHovered, __cmplp.borderColor)}`),
    "--_1cg585f": ix(!__cmplp.isSelected &&
    // eslint-disable-next-line @atlaskit/ui-styling-standard/no-imported-style-values -- Ignored via go/DSP-18766
    isArray(__cmplp.borderColor) && __cmplp.borderColor.length > 0 &&
    // eslint-disable-next-line @atlaskit/ui-styling-standard/no-imported-style-values, no-nested-ternary -- Ignored via go/DSP-18766
    `linear-gradient(${__cmplp.isHighlighted ? B700 : __cmplp.isSelected ? B500 : __cmplp.isHovered ? N500 : __cmplp.color}, ${
    // eslint-disable-next-line @atlaskit/ui-styling-standard/no-imported-style-values, no-nested-ternary -- Ignored via go/DSP-18766
    __cmplp.isHighlighted ? B700 : __cmplp.isSelected ? B500 : __cmplp.isHovered ? N500 : __cmplp.color}), conic-gradient(${getConicGradient(__cmplp.borderColor)})`),
    "--_dwe3mo": ix(B700),
    "--_ijaz3l": ix(B500),
    "--_1uodq60": ix(__cmplp.color),
    "--_1v5wkwx": ix(
    // eslint-disable-next-line @atlaskit/ui-styling-standard/no-imported-style-values -- Ignored via go/DSP-18766
    isArray(__cmplp.borderColor) && __cmplp.borderColor.length > 0 && 'content-box, border-box'),
    "--_sjyp98": ix(N0),
    "--_1i123mx": ix(N1000),
    "--_1hpfxaf": ix(
    // eslint-disable-next-line @atlaskit/ui-styling-standard/no-imported-style-values
    B700),
    "--_18666h2": ix(
    // eslint-disable-next-line @atlaskit/ui-styling-standard/no-imported-style-values
    B500),
    "--_whado": ix(__cmplp.borderColor[0]),
    "--_1szru47": ix(
    // eslint-disable-next-line @atlaskit/ui-styling-standard/no-imported-style-values
    N500),
    "--_ijc2tg": ix(!__cmplp.isSelected &&
    // eslint-disable-next-line @atlaskit/ui-styling-standard/no-imported-style-values -- Ignored via go/DSP-18766
    isArray(__cmplp.borderColor) && __cmplp.borderColor.length === 1 && `linear-gradient(${__cmplp.borderColor[0]}, ${__cmplp.borderColor[0]}), conic-gradient(${getConicGradient(__cmplp.borderColor)})`)
  }} ref={__cmplr} className={ax(["_2rko1rr0 _11c8dcr7 _v5641bs3 _19itgqsr _1bsb1osq _4t3i1osq _kqswstnw _1ltvidpf _154iidpf _vchhusvi _1e0c1txw _4cvr1h6o _1bah1h6o _1itkn916 _1lrwwvw6 _12vemgnk _ouxl1xdg _qjkj9dsr _1y1m1t4w _1yxgglyw _ejyia3fd _d0altlke", __cmplp.isDragging ? "_tzy4idpf" : "_tzy4kb7n", __cmplp.isHighlighted ? "_bfhksfwi" : __cmplp.isSelected ? "_bfhk1fp5" : "_bfhk1o7t", __cmplp.isHighlighted || __cmplp.isSelected || __cmplp.isHovered ? "_syazfl7h" : "_syazt8es", __cmplp.isHighlighted ? "_eyzj1c5c" : __cmplp.isSelected ? "_eyzj1p1s" : isArray(__cmplp.borderColor) && __cmplp.borderColor.length === 1 ? "_eyzj1gz2" : "_eyzj18q7", __cmplp.className])} />;
});

// eslint-disable-next-line @atlaskit/ui-styling-standard/no-styled -- To migrate as part of go/ui-styling-standard
if (process.env.NODE_ENV !== 'production') {
  DefaultBubbleContainer.displayName = 'DefaultBubbleContainer';
}
const DraggableBubbleWrapper = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_4t3i1kw7", __cmplp.className])} />;
});

// eslint-disable-next-line @atlaskit/ui-styling-standard/no-styled -- To migrate as part of go/ui-styling-standard
if (process.env.NODE_ENV !== 'production') {
  DraggableBubbleWrapper.displayName = 'DraggableBubbleWrapper';
}
const BubblePositioningContainer = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    isDragging,
    isHovered,
    ...__cmpldp
  } = __cmplp;
  return <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax(["_2rko1rr0 _kqswstnw _vchhusvi _17wj1kw7", __cmplp.isDragging ? "_v56418uv" : "_v5641hpz", __cmplp.isHovered ? "_1pby11wp" : "_1pbycs5v", __cmplp.className])} />;
});
if (process.env.NODE_ENV !== 'production') {
  BubblePositioningContainer.displayName = 'BubblePositioningContainer';
}
