/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
const styles = {
  default: "",
  'above.xs': "",
  'above.sm': "",
  'above.md': "",
  'above.lg': "",
  'above.xl': "",
  'below.xs': "",
  'below.sm': "",
  'below.md': "",
  'below.lg': "",
  'below.xl': ""
};
export const Show = ({
  children
}) => {
  return <div className={ax([styles.default])}>
			{children}
		</div>;
};
