/* .tmp-swc-padding-shorthand-import-1764057099675-14503dd9ac8bf.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { gridSize } from './grid-size';
const ACTIONS_CELL_PADDING = `${gridSize / 2}px`;
const styles = null;
export const Component = ()=><div className={ax([
        "_1bahesu3 _1yt4g20c _1e0c1txw"
    ])} style={{
        "--_254oyp": ix(TABLE_BUTTON_OUTLINE)
    }}/>;
