/* .tmp-swc-padding-shorthand-import-1765437471323-8ff1ee8f80e78.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { gridSize } from './grid-size';
const ACTIONS_CELL_PADDING = `${gridSize / 2}px`;
const styles = null;
export const Component = ()=><div className={ax([])} style={{
        "--_k5d4ix": ix("4px"),
        "--_254oyp": ix(TABLE_BUTTON_OUTLINE)
    }}/>;
