/* .tmp-swc-css-and-xcss-logical-and-1763944826513-2a86d59cd4167.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { Inline, xcss } from '@atlaskit/primitives';
const ListWithPopup = ({ items, ItemComponent, maxLimit, initialIsOpen, isHoverPopoverEnabled })=>{
    return (<Inline space="space.100" alignBlock="center" shouldWrap={!isHoverPopoverEnabled} xcss={isHoverPopoverEnabled && hoverPopoverStyles}>
      <ItemComponent isHoverPopoverEnabled={isHoverPopoverEnabled} className={ax([
        isHoverPopoverEnabled && "_1ul9ylrw"
    ])}/>
    </Inline>);
};
const hoverPopoverStyles = xcss({
    paddingRight: "var(--space-50, 50px)",
    width: '100%'
});
const hoverPopoverItemStyles = null;
export default ListWithPopup;
