/* .tmp-swc-css-twice-imported-1764023675089-1b3d3e4dcda13.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { palette } from './palette';
const styles = null;
export const Component = ()=>(<div className={ax([
        "_syaz1ejv _irr3u67f"
    ])}>
    imported twice
  </div>);
