/* .tmp-swc-css-twice-imported-1765437466962-babdc0fb9c2d3.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { palette } from './palette';
const styles = null;
export const Component = ()=>(<div className={ax([])}>
    imported twice
  </div>);
