/* .tmp-swc-tokens-space-200-1765752978050-51e264d599668.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    button: "_18zrpxbi"
};
export const Component = ()=><div className={styles.button()}>Content</div>;
