/* .tmp-swc-tokens-space-200-1765439428539-ab8869dc7c885.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    button: ""
};
export const Component = ()=><div className={styles.button()}>Content</div>;
