/* .tmp-swc-tokens-space-200-1764318515444-e90a2d49f279c.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    button: "_18zrpxbi"
};
export const Component = ()=><div className={styles.button()}>Content</div>;
