/* .tmp-swc-page-layout-root-cssmap-grid-1765408348830-3e6d152417b1a.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
const styles = {
    root: ""
};
export function Root({ children }) {
    return (<div className={ax([
        styles.root
    ])}>
			{children}
		</div>);
}
