/* .tmp-swc-page-layout-root-cssmap-grid-1763762856010-f2e9bbe9fdce4.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
const styles = {
    root: "_1lmcq9em _yv0ei47z _2z0516ab _1e0c11p5 _1tke1kxc _12fkuz0r _xkmgbaui _12qzrxre _1rqt70if _jbc7rxre _tyve1jg8"
};
export function Root({ children }) {
    return (<div className={ax([
        styles.root
    ])}>
			{children}
		</div>);
}
