/* .tmp-swc-interaction-layer-high-contrast-1765404345942-c4debde801014.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
const MENU_PLACEHOLDER_ID = 'software-backlog.card-list.card.card-contents.context-menu.menu_placeholder';
const cardFocusStyles = {
    content: '',
    display: 'block',
    position: 'absolute',
    zIndex: 1,
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    boxShadow: `0 0 0 2px ${"var(--ds-border-focused, #4688EC)"}`,
    pointerEvents: 'none'
};
const Container = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "_154iidpf _94n5idpf _1ltvidpf _1xi2idpf _kqswstnw _q5c0kb7n _1lztewfl _h10pb3bt _j7gt1ule _1tfxstnw _1v98kb7n _1a07idpf _ti30idpf _44x7idpf _gabdidpf _1n511y54 _6q10glyw _nt751r31 _49pcglyw _1hvw1o36 _bwdwb3bt _6ycq1ule _1h9dstnw _i6g0kb7n _9jtdidpf _1snmidpf _1jstidpf _pnw9idpf _xp6a1y54 _15y0glyw _xp6a2ef9 _zjd3b3bt _1vfc1ule _hkspstnw _1hl4kb7n _ehfnidpf _1btaidpf _1vdbidpf _o6k0idpf _1m551y54 _1191glyw _1m552ef9",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Container.displayName = "Container";
}
const Fixture = ()=><Container data-testid="interaction-layer"/>;
export default Fixture;
