/* .tmp-swc-interaction-layer-high-contrast-1765408344285-a59ad0c50d2b2.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
const MENU_PLACEHOLDER_ID = 'software-backlog.card-list.card.card-contents.context-menu.menu_placeholder';
const cardFocusStyles = {
    content: '',
    display: 'block',
    position: 'absolute',
    zIndex: 1,
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    boxShadow: `0 0 0 2px ${"var(--ds-border-focused, #4688EC)"}`,
    pointerEvents: 'none'
};
const Container = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Container.displayName = "Container";
}
const Fixture = ()=><Container data-testid="interaction-layer"/>;
export default Fixture;
