/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
const themedUnderline = {
  '&::after': {
    content: "''",
    position: 'absolute'
  }
};
const styles = null;
export const Component = () => <div className={ax([])} />;
