/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
const themedUnderline = {
  '&::after': {
    content: "''",
    position: 'absolute'
  }
};
const styles = null;
export const Component = () => <div className={ax(["_ty5w1txw _1q6e1txw _1ccmb3bt _ia7kb3bt _15opstnw _swr6stnw"])} />;
