/* .tmp-swc-css-nested-spread-underline-1764029522209-211b15f72e954.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const themedUnderline = {
    '&::after': {
        content: "''",
        position: 'absolute'
    }
};
const styles = null;
export const Component = ()=><div className={ax([
        "_1ccmb3bt _ia7kb3bt _15opstnw _swr6stnw _ty5w1txw _1q6e1txw"
    ])}/>;
