/* .tmp-swc-styled-flex-none-descendant-1763696595233-837c168f0f5a7.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const Item = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "_16jlidpf _1o9zidpf _i0dl1wug _vdz4kb7n",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Item.displayName = "Item";
}
export const Component = ()=>(<Item>
    <span data-target="child">Child</span>
  </Item>);
