/* .tmp-swc-xcss-cssmap-extract-1765439429089-20b45b0c9421.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { Box } from '@atlaskit/primitives/compiled';
const styles = {
    container: ""
};
export const Component = ()=><Box xcss={styles.container}/>;
