/* .tmp-swc-xcss-cssmap-extract-1763973276058-7b3facdfd1a2d.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { Box } from '@atlaskit/primitives/compiled';
const styles = {
    container: "_1bsb1mjv"
};
export const Component = ()=><Box xcss={styles.container}/>;
