/* .tmp-swc-simple-cssmap-unbounded-1765408350940-d1e4d242d8518.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    container: "",
    text: ""
};
export const Component = ()=>(<div className={ax([
        styles.container
    ])}>
    <span className={ax([
        styles.text
    ])}>Hello</span>
  </div>);
