/* .tmp-swc-simple-cssmap-unbounded-1765927677981-dd964cc6ea2ea.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    container: "_ca0qftgi _u5f3ftgi _n3tdftgi _19bvftgi _1e0c1txw",
    text: "_syaz5scu _1wybdlk8"
};
export const Component = ()=>(<div className={ax([
        styles.container
    ])}>
    <span className={ax([
        styles.text
    ])}>Hello</span>
  </div>);
