/* .tmp-swc-simple-cssmap-unbounded-1765439421459-0dc23a527abb2.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    container: "",
    text: ""
};
export const Component = ()=>(<div className={ax([
        styles.container
    ])}>
    <span className={ax([
        styles.text
    ])}>Hello</span>
  </div>);
