/* .tmp-swc-cssmap-unbounded-basic-1763973271631-f828e3fb95608.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    container: "_2rko1l7b _18zr1y44 _1e0c116y _1kz6184x _kqswpfqs _1reo15vq _18m915vq _vchhusvi",
    text: "_ect49sn6 _1wyb1skh _zg8l4jg8 _k48p8n31 _vwz47vkz _1reo15vq _18m915vq _1bto1l2s _1p1dangw _o5721q9c"
};
export const Component = ()=>(<div className={ax([
        styles.container
    ])}>
    <span className={ax([
        styles.text
    ])}>Hello</span>
  </div>);
