/* .tmp-swc-cssmap-unbounded-basic-1765408340803-7d8a9996b13af.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    container: "",
    text: ""
};
export const Component = ()=>(<div className={ax([
        styles.container
    ])}>
    <span className={ax([
        styles.text
    ])}>Hello</span>
  </div>);
