/* .tmp-swc-css-multi-args-1765930113435-ecb769043f9e9.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
export const className = null;
