/* .tmp-swc-css-multi-args-1765437466084-d70dc122680d9.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
export const className = null;
