/* .tmp-swc-css-multi-args-1765752971964-254e2294bf3f9.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
export const className = null;
