/* .tmp-swc-css-multi-args-1764109956865-2cf1a7c1da0b9.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
export const className = null;
