/* .tmp-swc-css-custom-property-zero-unit-1764733728893-b0cc1571a2acf.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=><div className={ax([
        "_w8uegrho"
    ])}/>;
