/* .tmp-swc-xcss-token-margin-dedup-1765439429686-34f6f77b02d6f.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { cx } from '@atlaskit/css';
const DescriptionWrapper = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    DescriptionWrapper.displayName = "DescriptionWrapper";
}
const TextWrapper = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    TextWrapper.displayName = "TextWrapper";
}
const styles = {
    bannerContainer: ""
};
export const Component = ({ showBanner })=>(<DescriptionWrapper>
    <TextWrapper>One</TextWrapper>
    {showBanner ? <div xcss={cx(styles.bannerContainer)}/> : null}
  </DescriptionWrapper>);
