/* .tmp-swc-styled-dynamic-destructure-1764364392724-83aa89aebc1b9.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const Wrapper = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { duration: duration, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={{
        ...__cmpls,
        "--_1gljcou": ix(__cmplp.width),
        "--_lbjvny": ix(`width ${__cmplp.duration}ms ease`)
    }} ref={__cmplr} className={ax([
        "_v5641gda _1bsb1rkg _1o9zidpf",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Wrapper.displayName = "Wrapper";
}
export const Component = ()=><Wrapper width="120px" duration={200}/>;
