/* in.tsx generated by @compiled/babel-plugin v0.38.1 */
// Minimal reproduction of the header cell focus outline rules where the additional
// :focus::before override repeats some properties and currently produces a length
// mismatch between Babel and SWC outputs.
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
const FocusCell = forwardRef(({
  as: C = "th",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["", __cmplp.className])} />;
});
if (process.env.NODE_ENV !== 'production') {
  FocusCell.displayName = 'FocusCell';
}
export default function Fixture() {
  return <table>
      <thead>
        <tr>
          <FocusCell>Header</FocusCell>
        </tr>
      </thead>
    </table>;
}
