/* in.tsx generated by @compiled/babel-plugin v0.38.1 */
// Minimal reproduction of the header cell focus outline rules where the additional
// :focus::before override repeats some properties and currently produces a length
// mismatch between Babel and SWC outputs.
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
const FocusCell = forwardRef(({
  as: C = "th",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_kqswh2mm _1n9didpf _12s81n1a _1hw81n1a _zzeu1n1a _1qc71hup _nt751r31 _49pcn7od _1hvw1o36 _qzh6fl6s _x7uvf705 _1j5l1ule _1qtkstnw _1w0p1osq _18141osq _1cl9j39m _p0vi1n1a _t0aw1n1a _eahy1n1a _7u4sfl6s _7ehi1l5v", __cmplp.className])} />;
});
if (process.env.NODE_ENV !== 'production') {
  FocusCell.displayName = 'FocusCell';
}
export default function Fixture() {
  return <table>
      <thead>
        <tr>
          <FocusCell>Header</FocusCell>
        </tr>
      </thead>
    </table>;
}
