/* .tmp-swc-header-cell-focus-length-1764733731118-941df8b8eaa3e.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const FocusCell = forwardRef(({ as: C = "th", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "_kqswh2mm _x7uvf705 _1j5l1ule _1qtkstnw _1w0p1osq _18141osq _1cl9j39m _p0vi1n1a _t0aw1n1a _eahy1n1a _qzh6fl6s _nt751r31 _49pcn7od _1hvw1o36 _7u4sfl6s _7ehi1l5v _1n9didpf _12s81n1a _1hw81n1a _zzeu1n1a _1qc71hup",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    FocusCell.displayName = "FocusCell";
}
export default function Fixture() {
    return (<table>
      <thead>
        <tr>
          <FocusCell>Header</FocusCell>
        </tr>
      </thead>
    </table>);
}
