/* .tmp-swc-cssmap-class-names-in-css-1765439413704-fa42a9e186561.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const asideVar = '--aside-var';
const panelSplitterResizingVar = '--n_asdRsz';
const contentInsetBlockStart = 'var(--content-inset-block-start)';
const contentHeightWhenFixed = 'var(--content-height-when-fixed)';
const styles = {
    root: "",
    inner: ""
};
function AsideComponent({ children }) {
    return (<aside className={ax([
        styles.root
    ])}>
			<div className={ax([
        styles.inner
    ])}>
				{children}
			</div>
		</aside>);
}
