/* .tmp-swc-css-at-property-1764039557913-ff27c3d1fb61a.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=><div className={ax([])} style={{
        "--_ikpmwb": ix(false)
    }}>Hello</div>;
