/* .tmp-swc-lozenge-mixed-cssmap-patterns-1765437469995-bf8ea7244db91.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const stylesOld = {
    container: "",
    'text.bold.default': "",
    'text.bold.inprogress': "",
    'text.subtle.default': ""
};
const stylesOldUnbounded = {
    text: "",
    customLetterspacing: ""
};
export const Lozenge = ({ children, appearance = 'default', isBold = false })=>(<div className={ax([
        stylesOld.container,
        stylesOldUnbounded.text,
        stylesOldUnbounded.customLetterspacing
    ])}>
		<span className={ax([
        stylesOld[`text.${isBold ? 'bold' : 'subtle'}.${appearance}`]
    ])}>
			{children}
		</span>
	</div>);
