/* .tmp-swc-lozenge-mixed-cssmap-patterns-1764368031394-e6e23ec863814.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const stylesOld = {
    container: "_2rko12b0 _18zr1b66 _1e0c116y _1kz6184x _kqswpfqs _1reo15vq _18m915vq _vchhusvi",
    'text.bold.default': "_syaz15cr",
    'text.bold.inprogress': "_syaz15cr",
    'text.subtle.default': "_syazazsu"
};
const stylesOldUnbounded = {
    text: "_ect41gqc _1wyb1skh _zg8l4jg8 _k48pmoej _vwz47vkz _1reo15vq _18m915vq _1bto1l2s _1p1dangw _o5721q9c",
    customLetterspacing: "_1dyz9vsi"
};
export const Lozenge = ({ children, appearance = 'default', isBold = false })=>(<div className={ax([
        stylesOld.container,
        stylesOldUnbounded.text,
        stylesOldUnbounded.customLetterspacing
    ])}>
		<span className={ax([
        stylesOld[`text.${isBold ? 'bold' : 'subtle'}.${appearance}`]
    ])}>
			{children}
		</span>
	</div>);
