/* .tmp-swc-styled-css-reference-1765752976390-e0f9225ddb251.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const themedUnderline = {
    '&::after': {
        left: 0,
        content: "''"
    }
};
const tabStyles = null;
export const Tab = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "_1e0c1txw _91x1idpf _gc90b3bt _1q5t1r31 _1ohyglyw _1r9x1o36",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Tab.displayName = "Tab";
}
