/* .tmp-swc-cx-with-dynamic-cssmap-property-1764484167837-98006d36e6da4.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
import { cx } from '@atlaskit/css';
const styles = {
    goalIcon: "_2rko1y44 _4cvr1h6o _1bah1h6o _1dqonqa1 _1h6d14ap _189et94y _1e0c1txw",
    size16: "_1bsb7vkz _4t3i7vkz",
    size24: "_1bsb1tcg _4t3i1tcg",
    size32: "_1bsbzwfg _4t3izwfg"
};
export function GoalIcon({ size = '24' }) {
    return (<div xcss={cx(styles.goalIcon, styles[`size${size}`])}>
			Content
		</div>);
}
