/* .tmp-swc-cx-with-dynamic-cssmap-property-1765437467811-92b0a8e357631.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
import { cx } from '@atlaskit/css';
const styles = {
    goalIcon: "",
    size16: "",
    size24: "",
    size32: ""
};
export function GoalIcon({ size = '24' }) {
    return (<div xcss={cx(styles.goalIcon, styles[`size${size}`])}>
			Content
		</div>);
}
