/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
const styles = {
  root: ""
};
function Root({
  xcss
}) {
  return <div className={ax([styles.root, xcss])}>
      Content
    </div>;
}
