/* .tmp-swc-xcss-className-prop-conflict-1765408361330-7ca1e6dd975f4.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    root: ""
};
function Root({ xcss }) {
    return (<div className={ax([
        styles.root,
        xcss
    ])}>
      Content
    </div>);
}
