/* .tmp-swc-xcss-className-prop-conflict-1765927681145-e3c71dd7c1b3d.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    root: "_1lmcq9em _yv0ei47z _2z0516ab _1e0c11p5 _1tke1kxc _12fkuz0r _12qzrxre _1rqt70if"
};
function Root({ xcss }) {
    return (<div className={ax([
        styles.root,
        xcss
    ])}>
      Content
    </div>);
}
