/* .tmp-swc-css-object-with-media-queries-1765439412547-c1fac04f975fc.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const responsiveStyles = null;
export const Component = ({ children })=>{
    return <div className={ax([])}>{children}</div>;
};
