/* .tmp-swc-css-object-with-media-queries-1763762853163-5e56a0f2f7d8b.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const responsiveStyles = null;
export const Component = ({ children })=>{
    return <div className={ax([
        "_ca0q7vkz _u5f37vkz _n3td7vkz _19bv7vkz _1wybdlk8 _zkgc1d6m _sedtglyw _1gfd1tcg _1gqrzwfg _16hr1tcg _167y1tcg _3y2o1tcg _1gw87vkz _z0qszwfg _1u24zwfg _14rczwfg _1s0pf6fq _b9611fra _1h6kidpf _ikph1wug _12taidpf _11wk1wug _hjr5u67f"
    ])}>{children}</div>;
};
