/* .tmp-swc-styled-nested-selectors-1764625078211-4f9e4c54cc2bb.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=>(<div className={ax([
        "_syaz143u _30l3u67f _1h9x1r31 _16fv8stv _hkegnqa1 _r5zo1r31 _s3beglyw _10t01o36"
    ])}>
    <span>Nested</span>
  </div>);
