/* .tmp-swc-styled-nested-selectors-1765439425797-87d7930b82124.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=>(<div className={ax([])}>
    <span>Nested</span>
  </div>);
