/* .tmp-swc-tokens-gradient-extract-1764057102712-59535cd3e9cae.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const SkeletonRow = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={{
        ...__cmpls,
        "--_1neqek2": ix(`${__cmplp.height}px`),
        "--_6f8077": ix(`${__cmplp.width}px`)
    }} ref={__cmplr} className={ax([
        "_2rkofajl _1itkh4uj _12vemgnk _4t3i2nrh _1bsb1hdq",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    SkeletonRow.displayName = "SkeletonRow";
}
export const Component = ()=><SkeletonRow height={40} width={200}/>;
