/* .tmp-swc-css-attribute-selector-1763860974388-cde82d175a67.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=><div className={ax([
        "_zkjh5scu"
    ])}/>;
