/* .tmp-swc-css-attribute-selector-1765408334642-36f16e2b3aff3.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=><div className={ax([])}/>;
