/* .tmp-swc-css-array-conditional-styles-1764039557770-0f0343d000397.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const fullpageStyles = null;
const modalStyles = null;
const customSpacingStyles = null;
export default function Component({ isEmbedView, isModalView }: {
    isEmbedView?: boolean;
    isModalView?: boolean;
}) {
    const customCss = [
        customSpacingStyles,
        isEmbedView !== true && isModalView !== true ? fullpageStyles : null,
        isModalView === true ? modalStyles : null
    ];
    return <div className={ax([
        "_p12f107j",
        isEmbedView !== true && isModalView !== true && "_uwhkftgi",
        isModalView === true && "_19pk10j7"
    ])}>hello</div>;
}
