/* .tmp-swc-css-array-conditional-styles-1765437464258-fc8f514220411.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const fullpageStyles = null;
const modalStyles = null;
const customSpacingStyles = null;
export default function Component({ isEmbedView, isModalView }: {
    isEmbedView?: boolean;
    isModalView?: boolean;
}) {
    const customCss = [
        customSpacingStyles,
        isEmbedView !== true && isModalView !== true ? fullpageStyles : null,
        isModalView === true ? modalStyles : null
    ];
    return <div className={ax([
        isEmbedView !== true && isModalView !== true && "",
        isModalView === true && ""
    ])}>hello</div>;
}
