/* .tmp-swc-css-text-decoration-none-1764733729730-aeb4315606bc2.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const base = null;
export const Component = ()=>(<div className={ax([
        "_4bfu18uv _1hmsglyw _ajmmnqa1"
    ])}>
    Hello
  </div>);
