/* .tmp-swc-css-text-decoration-none-1765437466737-1f146f666c058.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const base = null;
export const Component = ()=>(<div className={ax([])}>
    Hello
  </div>);
