/* .tmp-swc-css-text-decoration-none-1765408338946-951ba03244f74.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const base = null;
export const Component = ()=>(<div className={ax([])}>
    Hello
  </div>);
