/* .tmp-swc-css-text-decoration-none-1764358656939-1a9494f57a31f.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const base = null;
export const Component = ()=>(<div className={ax([
        "_4bfu1r31 _1hmsglyw _ajmmnqa1"
    ])}>
    Hello
  </div>);
