/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { DARK_MODE, MEDIA_QUERY } from "./media";
export const responsiveStyles = null;
export const responsiveTemplate = null;
export const MediaExample = () => (
	<section
		className={ax(["_syazr3uz _hjr51x77 _1pnl1gc2 _17lw8n31", "_syaz1lra _hjr52e8d _1pnl1he7"])}
	>
		responsive media queries
	</section>
);
