/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
const styles = {
  root: "_9qso1r31 _nt751r31 _14gfglyw _49pcglyw _dg4t1o36 _1hvw1o36 _n1v1glyw _7ehiglyw"
};
export function Component() {
  return <div className={ax([styles.root])}>
      <button type="button">Child</button>
    </div>;
}
