/* .tmp-swc-descendant-focus-outline-1765927673855-76067a92f88f6.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    root: "_9qso1r31 _14gfglyw _dg4t1o36 _n1v1glyw _nt751r31 _49pcglyw _1hvw1o36 _7ehiglyw"
};
export function Component() {
    return (<div className={ax([
        styles.root
    ])}>
      <button type="button">Child</button>
    </div>);
}
