/* .tmp-swc-descendant-focus-outline-1765439415110-eeb68dc8c8907.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    root: ""
};
export function Component() {
    return (<div className={ax([
        styles.root
    ])}>
      <button type="button">Child</button>
    </div>);
}
