/* in.tsx generated by @compiled/babel-plugin v0.38.1 */
// Mirrors the Jira action-button Counter style that returns an arrow function
// which then returns a conditional string.
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
const Counter = forwardRef(({
  as: C = "span",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    hasWatchers,
    ...__cmpldp
  } = __cmplp;
  return <C {...__cmpldp} style={{
    ...__cmpls,
    "--_1v54z33": ix(() => __cmplp.hasWatchers ? 'var(--ds-space-025)' : 'var(--ds-space-0)')
  }} ref={__cmplr} className={ax(["", __cmplp.className])} />;
});
if (process.env.NODE_ENV !== 'production') {
  Counter.displayName = 'Counter';
}
export default function Component({
  hasWatchers
}: {
  hasWatchers?: boolean;
}) {
  return <Counter hasWatchers={hasWatchers}>count</Counter>;
}
