/* .tmp-swc-backlog-panel-card-length-mismatch-1765955936986-2c118b4c31a7b.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import { ax, ix } from "@compiled/react/runtime";
import React, { createRef, useCallback, useEffect, useState, type ComponentType, type MouseEvent, type MutableRefObject, type ReactNode, type FocusEvent, useRef } from 'react';
import { type CssFunction } from '@compiled/react';
import noop from 'lodash/noop';
import type { UIAnalyticsEvent } from '@atlaskit/analytics-next';
import Heading from '@atlaskit/heading';
import { Box, Flex, xcss } from '@atlaskit/primitives';
import Spinner from '@atlaskit/spinner';
import { media } from './responsive';
import { componentWithCondition } from './component-with-condition';
import { fireUIAnalytics } from './analytics';
import { isVisualRefreshEnabled } from './feature-switch';
import { useSoftwareProjectTheming } from './software-theme';
import { Tokens } from './custom-theme-constants';
import { getIsSoftwareThemingM2Enabled } from './theming-enabled';
import { fg } from './feature-gating';
import { useModalDialogActions } from './modal-dialog-actions';
import { AnnouncerV2 } from './announcer-v2';
import { useCardOpen } from './use-card-open';
import { cardColor } from './constants.tsx';
import Expand from './expand/index.tsx';
import type { CardContainerPropsWithDragging, CardPropsWithDraggingAndStates } from './types.tsx';
import { ContextMenu } from './context-menu/index.tsx';
const Container = ({ innerRef, isActive = false, isDraggingOver = false, children, onClick = noop, isLoading, isDragging = false, expanded = false, onHoverOrFocus, onUnhoverOrBlur }: CardContainerPropsWithDragging)=>{
    const containerProps = {
        'data-test-id': 'software-backlog-panel.common.ui.card.container',
        'data-testid': 'software-backlog-panel.common.ui.card.container'
    };
    const { isSoftwareFullTheming } = getIsSoftwareThemingM2Enabled() ? useSoftwareProjectTheming() : {
        isSoftwareFullTheming: false
    };
    const cardRef = createRef<HTMLDivElement>();
    useEffect(()=>{
        if (cardRef && cardRef.current && cardRef.current.scrollIntoView && isLoading === true) {
            cardRef.current.scrollIntoView({
                behavior: 'smooth'
            });
        }
    }, [
        cardRef,
        isLoading
    ]);
    const onBlur = useCallback((event: FocusEvent)=>{
        if (innerRef?.current && !innerRef.current.contains(event.relatedTarget) && onUnhoverOrBlur) {
            onUnhoverOrBlur();
        }
    }, [
        innerRef,
        onUnhoverOrBlur
    ]);
    return isLoading === true ? <StaticContainer ref={cardRef} {...containerProps} className={ax([
        "_1gqru2gc _1e051b66 _1y7gu2gc _2ae21b66 _35p0u2gc _z0qsutpp _1u24u2gc _14rcutpp"
    ])}>
			{children}
		</StaticContainer> : <InteractiveContainer {...containerProps} ref={innerRef} isActive={isActive} isDraggingOver={isDraggingOver} onClick={onClick} isDragging={isDragging} expanded={expanded} onMouseEnter={onHoverOrFocus} onFocus={onHoverOrFocus} onBlur={onBlur} onMouseLeave={onUnhoverOrBlur} isSoftwareFullTheming={isSoftwareFullTheming} className={ax([
        "_1gqru2gc _1e051b66 _1y7gu2gc _2ae21b66 _35p0u2gc _z0qsutpp _1u24u2gc _14rcutpp"
    ])}>
			{children}
		</InteractiveContainer>;
};
const Card = (props: CardPropsWithDraggingAndStates)=>{
    const { isContentExpanded, toggleOpen } = useCardOpen(props.id);
    const { isSoftwareFullTheming } = getIsSoftwareThemingM2Enabled() ? useSoftwareProjectTheming() : {
        isSoftwareFullTheming: false
    };
    const { title = '', subtitle = null, children, isLoading, isActive = false, itemName = '', itemType, editButton, id } = props;
    const content = typeof children === 'function' ? children(isContentExpanded) : children;
    const shouldShowContents = Boolean(content) && !isLoading;
    const [isHovered, setIsHovered] = useState(false);
    const menuTriggerRef = useRef<HTMLButtonElement>(null);
    const { setReturnFocusTo } = useModalDialogActions();
    const onToggleExpanded = (event: MouseEvent<HTMLElement>, analyticsEvent: UIAnalyticsEvent): void =>{
        event.stopPropagation();
        fireUIAnalytics(analyticsEvent, 'expandToggleButton', {
            expandState: !isContentExpanded
        });
        toggleOpen();
    };
    const [announcement, setAnnouncement] = useState('');
    const showEditButton = useCallback(()=>setIsHovered(true), []);
    const hideEditButton = useCallback(()=>setIsHovered(false), []);
    const handleMenuOpenChange = useCallback((isOpen: boolean)=>{
        if (isOpen && menuTriggerRef?.current) {
            setReturnFocusTo(menuTriggerRef);
        }
    }, [
        setReturnFocusTo
    ]);
    return <Container {...props} expanded={isContentExpanded} onHoverOrFocus={showEditButton} onUnhoverOrBlur={hideEditButton}>
			<Header showChevron={shouldShowContents} visualRefresh={isVisualRefreshEnabled()}>
				{shouldShowContents && <Expand data-testid="software-backlog-panel.common.ui.card.expand" isExpanded={isContentExpanded} onToggle={onToggleExpanded} itemName={itemName} itemType={itemType} isActive={isActive}/>}
				<Title data-testid="software-backlog-panel.common.ui.card.title" visualRefresh={isVisualRefreshEnabled()}>
					{isVisualRefreshEnabled() && (fg('jfp-a11y-team_fix_heading_on_backlog_card_ui') ? <Flex justifyContent="space-between" alignItems="center">
								<Box as="h3" paddingBlockStart="space.0" xcss={[
        titleContainerStylesNew,
        isActive && titleSelectedStyles,
        isSoftwareFullTheming && isActive && titleSelectedThemedStyles
    ]}>
									{title}
								</Box>
								{isHovered && editButton}
							</Flex> : <Flex as="ul" justifyContent="space-between" alignItems="center" xcss={[
        titleContainerStyles,
        isActive && titleSelectedStyles,
        isSoftwareFullTheming && isActive && titleSelectedThemedStyles
    ]}>
								<Box as="li" paddingBlockStart="space.0">
									{title}
								</Box>
								{isHovered && editButton}
							</Flex>)}
					{!isVisualRefreshEnabled() && <Heading as="h3" size="xsmall">
							{title}
						</Heading>}
				</Title>
				{isLoading === true && <Box xcss={cardSpinnerStyles}>
						<Spinner testId="software-backlog-panel.common.ui.card.spinner" size="small" appearance={isActive ? 'invert' : 'inherit'}/>
					</Box>}
				{itemType === 'epic' && shouldShowContents && <>
						<AnnouncerV2 message={announcement} shouldAnnounce={announcement !== ''} liveMode="polite"/>
						<ContextMenu cardId={id} onOpenChange={handleMenuOpenChange} triggerRef={menuTriggerRef} setAnnouncement={setAnnouncement}/>
					</>}
			</Header>
			{subtitle}
			{shouldShowContents && isContentExpanded && <AnimatedHeight data-testid="software-backlog-panel.common.ui.card.content-container" aria-hidden={!isContentExpanded} isExpanded={isContentExpanded}>
					<Box xcss={contentStyles}>{content}</Box>
				</AnimatedHeight>}
		</Container>;
};
export default Card;
const cardMaxWidth = 270;
const responsiveStyles = null;
const AnimatedHeight = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { isExpanded: isExpanded, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax([
        "_v5644er6 _1reo15vq _18m915vq",
        __cmplp.isExpanded ? "_c71lw7q6" : "_c71lidpf",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    AnimatedHeight.displayName = "AnimatedHeight";
}
const cardSpinnerStyles = xcss({
    marginLeft: 'space.150'
});
const defaultBoxShadow = "var(--ds-shadow-raised, 0px 1px 1px #091E4240, 0px 0px 1px #091E424f)";
const focusBoxShadow = `inset 0 0 0 2px ${"var(--ds-border-focused, #388BFF)"};`;
const outlineStyles = `
    outline: none;
    &:focus {
        box-shadow: ${focusBoxShadow};
    }
`;
const StaticContainer = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { isLoading: isLoading, isDraggingOver: isDraggingOver, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={{
        ...__cmpls,
        "--_1h09nl0": ix(cardColor.default.mouseLeave.backgroundColor),
        "--_1dnfcf4": ix(cardColor.default.mouseLeave.textColor)
    }} ref={__cmplr} className={ax([
        "_2lx21bp4 _2rko12b0 _v56419bn _19pkv77o _2hwx1b66 _otyrv77o _18u01b66 _1e0c1txw _vchhusvi _p12f1ogy _bfhk1365 _syazhclr",
        __cmplp.isLoading ? "_80om15jw" : "_80om73ad",
        __cmplp.isDraggingOver ? "_16qs64oc" : "_16qszucj",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    StaticContainer.displayName = "StaticContainer";
}
const StaticContainerNew = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { isLoading: isLoading, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={{
        ...__cmpls,
        "--_1dnfcf4": ix(cardColor.default.mouseLeave.textColor)
    }} ref={__cmplr} className={ax([
        "_2lx21bp4 _2rko12b0 _v56419bn _19pkv77o _2hwxu2gc _otyrv77o _18u0u2gc _1e0c1txw _vchhusvi _p12f1ogy _bfhk1j28 _syazhclr",
        __cmplp.isLoading ? "_80om15jw" : "_80om73ad",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    StaticContainerNew.displayName = "StaticContainerNew";
}
const InteractiveContainerOld: ComponentType<{
    ['data-test-id']: string;
    ref?: MutableRefObject<HTMLDivElement | null>;
    isDragging?: boolean;
    isActive?: boolean;
    isDraggingOver: boolean;
    tabIndex?: number;
    onClick?: (event: MouseEvent<HTMLElement>) => void;
    onMouseDown?: (event: MouseEvent<HTMLElement>) => void;
    children?: ReactNode;
    isSoftwareFullTheming?: boolean;
    css?: CssFunction | CssFunction[];
}> = forwardRef(({ as: C = StaticContainer, style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={{
        ...__cmpls,
        "--_xo8bol": ix(cardColor.default.mouseOver.backgroundColor),
        "--_au4plk": ix(cardColor.default.mouseOver.textColor),
        "--_181jl6c": ix(cardColor.active.mouseDown.backgroundColor),
        "--_1yuuf1b": ix(cardColor.default.mouseDown.backgroundColor),
        "--_rgmfhj": ix(cardColor.active.mouseLeave.backgroundColor),
        "--_fdouhv": ix(cardColor.active.mouseLeave.textColor),
        "--_lyilio": ix(cardColor.active.mouseOver.backgroundColor),
        "--_1g6q8x": ix(cardColor.active.mouseOver.textColor)
    }} ref={__cmplr} className={ax([
        "_12ji1r31 _1qu2glyw _12y31o36 _10j71jng _irr31jng _vp7g1lpq _30l31lpq _7ehi64oc",
        __cmplp.isActive ? "_1di61uj6" : "_1di6hjni",
        __cmplp.isDragging && "_bfhkfg4m _irr3fg4m",
        __cmplp.isActive && "_bfhk1ayf _syaz1o5v _10j78okp _irr38okp _vp7g1r2d _30l31r2d",
        __cmplp.isDraggingOver && "_bfhkfg4m _syaz1fxt _irr3fg4m _30l31fxt",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    InteractiveContainerOld.displayName = "InteractiveContainerOld";
}
const InteractiveContainerNew: ComponentType<{
    ['data-test-id']: string;
    ref?: MutableRefObject<HTMLDivElement | null>;
    isDragging?: boolean;
    isActive?: boolean;
    isDraggingOver: boolean;
    tabIndex?: number;
    onClick?: (event: MouseEvent<HTMLElement>) => void;
    onMouseDown?: (event: MouseEvent<HTMLElement>) => void;
    onMouseEnter?: (event: MouseEvent<HTMLElement>) => void;
    onFocus?: (event: FocusEvent) => void;
    onBlur?: (event: FocusEvent) => void;
    onMouseLeave?: (event: MouseEvent<HTMLElement>) => void;
    children?: ReactNode;
    expanded?: boolean;
    isSoftwareFullTheming?: boolean;
    css?: CssFunction | CssFunction[];
}> = forwardRef(({ as: C = StaticContainerNew, style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={{
        ...__cmpls,
        "--_1smle1g": ix(cardColor.default.mouseOver.backgroundColor),
        "--_au4plk": ix(cardColor.default.mouseOver.textColor),
        "--_1yuuf1b": ix(cardColor.default.mouseDown.backgroundColor),
        "--_1koxd6y": ix(__cmplp.isSoftwareFullTheming ? Tokens.COLOR_BACKGROUND_NEUTRAL : "var(--ds-background-selected, #E9F2FF)"),
        "--_fdouhv": ix(cardColor.active.mouseLeave.textColor),
        "--_17sxilo": ix(__cmplp.isSoftwareFullTheming ? Tokens.COLOR_BORDER_SELECTED : "var(--ds-border-selected, #0C66E4)"),
        "--_g5kx1x": ix(__cmplp.isSoftwareFullTheming ? Tokens.COLOR_BACKGROUND_NEUTRAL_HOVERED : cardColor.active.mouseOver.backgroundColor),
        "--_1g6q8x": ix(cardColor.active.mouseOver.textColor),
        "--_5lhzjr": ix(__cmplp.isSoftwareFullTheming ? Tokens.WRAPPER_BACKGROUND : "var(--ds-surface, #FFFFFF)")
    }} ref={__cmplr} className={ax([
        "_2rko12b0 _1h6d1j28 _1dqonqa1 _189ee4h9 _12ji1r31 _1qu2glyw _12y31o36 _vp7g1lpq _30l31lpq _7ehi64oc",
        __cmplp.isSoftwareFullTheming ? "_10j7llho _irr3llho" : "_10j71rtj _irr31rtj",
        __cmplp.isActive ? "_1di6fg4m" : "_1di6hjni",
        __cmplp.isDragging && "_bfhkfg4m _irr3fg4m",
        __cmplp.isActive && "_2rko12b0 _1h6d1031 _1dqonqa1 _189ee4h9 _bfhk1ru1 _syaz1o5v _10j7sgqa _irr3sgqa _vp7g1r2d _30l31r2d",
        __cmplp.isDraggingOver && "_bfhkfg4m _syaz1fxt _irr3fg4m _30l31fxt",
        __cmplp.expanded && !__cmplp.isActive && "_1h6dmuej _bfhk1v2w",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    InteractiveContainerNew.displayName = "InteractiveContainerNew";
}
const InteractiveContainer = componentWithCondition(isVisualRefreshEnabled, InteractiveContainerNew, InteractiveContainerOld);
const Header = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { showChevron: showChevron, visualRefresh: visualRefresh, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax([
        "_4cvr1h6o _19pkv77o _2rko12b0 _1e0c1txw _1tke1ejb _12ji1r31 _1qu2glyw _12y31o36 _7ehi64oc",
        __cmplp.showChevron && !__cmplp.visualRefresh ? "_18u0x0bf" : "_18u0ze3t",
        __cmplp.visualRefresh && "_1tke1f4h",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Header.displayName = "Header";
}
const Title = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { visualRefresh: visualRefresh, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={{
        ...__cmpls,
        "--_14jabjs": ix(cardColor.default.textColor)
    }} ref={__cmplr} className={ax([
        "_ca0qv77o _11c81psy _1wpz1h6o _1e0c1o8l _slp31hna _1reo15vq _k48p1wq8 _16jlkb7n _1o9zkb7n _i0dlf1ug _syaz15fh",
        __cmplp.visualRefresh && "_1yt4v77o",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Title.displayName = "Title";
}
const titleContainerStylesNew = xcss({
    font: 'font.body',
    fontWeight: "var(--ds-font-weight-medium, 500)",
    color: 'color.text.subtle',
    paddingLeft: 'space.0',
    margin: 'space.0',
    minHeight: 'space.300'
});
const titleContainerStyles = xcss({
    listStyle: 'none',
    color: 'color.text.subtle',
    paddingLeft: 'space.0',
    margin: 'space.0',
    minHeight: 'space.300'
});
const contentStyles = xcss({
    marginTop: 'space.100'
});
const titleSelectedStyles = xcss({
    color: 'color.text.selected'
});
const titleSelectedThemedStyles = xcss({
    color: Tokens.COLOR_TEXT_SUBTLE
});
