/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
import { ACTIONS_CELL_PADDING, TABLE_BUTTON_OUTLINE } from './constants';
const styles = null;
export const Component = () => <div className={ax(["_1yt419se _1e0c1txw _1bahesu3"])} style={{
  "--_k5d4ix": ix(ACTIONS_CELL_PADDING),
  "--_254oyp": ix(TABLE_BUTTON_OUTLINE)
}} />;
