/* .tmp-swc-padding-shorthand-imported-constants-1766020318892-ed1df16b4f034.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { ACTIONS_CELL_PADDING, TABLE_BUTTON_OUTLINE } from './constants';
const styles = null;
export const Component = ()=><div className={ax([
        "_1bahesu3 _1yt419se _1e0c1txw"
    ])} style={{
        "--_k5d4ix": ix(`${gridSize / 2}px`),
        "--_254oyp": ix(`${gridSize / 4}px`)
    }}/>;
