/* .tmp-swc-styled-computed-negative-margin-1765408353670-cfd62e511d0f5.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const gridSize = 8;
const IssueContainer = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    IssueContainer.displayName = "IssueContainer";
}
const Component = ()=>(<IssueContainer>
		<div>Content</div>
	</IssueContainer>);
export default Component;
