/* .tmp-swc-styled-dynamic-grid-template-repeat-1765408354784-3cc9fa64f513b.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const gridSize = 8;
const StatusContainer = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { widthMultiplier: widthMultiplier, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={{
        ...__cmpls,
        "--_1w2vits": ix(`repeat(auto-fit,${gridSize * __cmplp.widthMultiplier}px)`)
    }} ref={__cmplr} className={ax([
        "",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    StatusContainer.displayName = "StatusContainer";
}
export const Component = ({ widthMultiplier })=>(<StatusContainer widthMultiplier={widthMultiplier}>
    <div/>
  </StatusContainer>);
