/* .tmp-swc-css-vendor-prefix-1765437467010-6aea18e63c256.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=><div className={ax([])}/>;
