/* .tmp-swc-css-vendor-prefix-1763944827690-1a367fa855e91.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=><div className={ax([
        "_13di1kw7 _wstuglyw _1fpfglyw _uiztglyw"
    ])}/>;
