/* .tmp-swc-css-vendor-prefix-1764733729898-ee8c4b4b30639.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=><div className={ax([
        "_13di1kw7 _wstuglyw _1fpfglyw _uiztglyw"
    ])}/>;
