/* .tmp-swc-image-export-pointer-events-simple-1764358658382-e714e48889dab.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const hiddenTableContainerStyles = null;
const Fixture = ()=><div className={ax([
        "_154iidpf _1ltvidpf _kqswstnw _1bsb1osq _4t3i1osq _1reo15vq _18m915vq _tzy4idpf _lcxvglyw _169tglyw"
    ])}>hidden</div>;
export default Fixture;
