/* .tmp-swc-image-export-pointer-events-simple-1765437469194-8808c82927ea7.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const hiddenTableContainerStyles = null;
const Fixture = ()=><div className={ax([])}>hidden</div>;
export default Fixture;
