/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const Base = ({ children })=><button>{children}</button>;
export const StyledButton = forwardRef(({ as: C = Base, style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "_syaz1q9v",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    StyledButton.displayName = "StyledButton";
}
export const Component = ()=><StyledButton>Click me</StyledButton>;
