/* .tmp-swc-responsive-show-cssmap-dynamic-1763963510433-f678f81e66028.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    default: "_1e0cglyw",
    'above.xs': "_114b19ly",
    'above.sm': "_181n19ly",
    'above.md': "_dm2519ly",
    'above.lg': "_je3o19ly",
    'above.xl': "_1uxv19ly",
    'below.xs': "_1m0a19ly",
    'below.sm': "_suga19ly",
    'below.md': "_1mjb19ly",
    'below.lg': "_liwc19ly",
    'below.xl': "_14wz19ly"
};
export const Show = ({ above, below, children, as: AsElement = 'div', className })=>{
    return (<AsElement className={ax([
        styles.default,
        above && styles[`above.${above}`],
        below && styles[`below.${below}`],
        className
    ])}>
			{children}
		</AsElement>);
};
