/* .tmp-swc-styled-dynamic-preloader-1763846887063-986f711cfa965.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
const Preloader = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { hideLabel: hideLabel, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax([
        "_1bah1h6o _4cvr1h6o _1e0c1txw _1reo15vq _18m915vq",
        __cmplp.hideLabel ? "_1tkeuuw1" : "_1tke68cl",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Preloader.displayName = "Preloader";
}
export const Component = ({ hideLabel })=>(<Preloader hideLabel={hideLabel}>
    <div>content</div>
  </Preloader>);
