/* .tmp-swc-column-gap-prefix-1764044652004-659618bdd056a.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { xcss } from '@atlaskit/primitives';
const _ = "._4cvr1q9y{align-items:baseline}";
const _2 = "._1bah1h6o{justify-content:center}";
const _3 = "._2rko12b0{border-radius:var(--ds-radius-small,4px)}";
const _4 = '._11c82smr{font:var(--ds-font-body,normal 400 14px/20px ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",Ubuntu,"Helvetica Neue",sans-serif)}';
const _5 = "._189ee4h9{border-width:var(--ds-border-width,1px)}";
const _6 = "._1dqonqa1{border-style:solid}";
const _7 = "._1h6d1j28{border-color:transparent}";
const _8 = "._1rjc12x7{padding-block:var(--ds-space-075,6px)}";
const _9 = "._18zrutpp{padding-inline:var(--ds-space-150,9pt)}";
const _10 = "._1bsb1wug{width:auto}";
const _11 = "._p12f1osq{max-width:100%}";
const _12 = "._gy1p1b66{column-gap:var(--ds-space-050,4px)}";
const _13 = "._c71lzwfg{max-height:2pc}";
const _14 = "._k48p1wq8{font-weight:var(--ds-font-weight-medium,500)}";
const _15 = "._80omtlke{cursor:pointer}";
const _16 = "._y2mv5e4z:focus{outline:var(--ds-border-width-focused,2px) auto var(--ds-border-focused,#388bff)}";
const _17 = "._1bg41i6y:focus{outline-offset:var(--ds-space-negative-025,-2px)}";
const _18 = "._1ygb5e4z:focus-visible{outline:var(--ds-border-width-focused,2px) auto var(--ds-border-focused,#388bff)}";
const _19 = "._1ah31i6y:focus-visible{outline-offset:var(--ds-space-negative-025,-2px)}";
const _20 = "._1jhm5e4z:active{outline:var(--ds-border-width-focused,2px) auto var(--ds-border-focused,#388bff)}";
const _21 = "._13ro1i6y:active{outline-offset:var(--ds-space-negative-025,-2px)}";
const legacyStyles = xcss({
    display: 'inline-flex',
    columnGap: 'space.050',
    maxWidth: '100%',
    alignItems: 'baseline',
    justifyContent: 'center'
});
const refreshedStyles = null;
export const Example = ()=><>
    <div xcss={legacyStyles}>legacy</div>
    <CC>
  <CS>{[
        _,
        _2,
        _3,
        _4,
        _5,
        _6,
        _7,
        _8,
        _9,
        _10,
        _11,
        _12,
        _13,
        _14,
        _15,
        _16,
        _17,
        _18,
        _19,
        _20,
        _21
    ]}</CS>
  {<div className={ax([
        "_4cvr1q9y _1bah1h6o _2rko12b0 _11c82smr _189ee4h9 _1dqonqa1 _1h6d1j28 _1rjc12x7 _18zrutpp _1bsb1wug _p12f1osq _gy1p1b66 _c71lzwfg _k48p1wq8 _80omtlke _1jhm5e4z _y2mv5e4z _1ygb5e4z _13ro1i6y _1bg41i6y _1ah31i6y"
    ])}>refresh</div>}
</CC>
  </>;
