/* .tmp-swc-column-gap-prefix-1764368027647-e9bd65c1652ae.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { xcss } from '@atlaskit/primitives';
const legacyStyles = xcss({
    display: 'inline-flex',
    columnGap: 'space.050',
    maxWidth: '100%',
    alignItems: 'baseline',
    justifyContent: 'center'
});
const refreshedStyles = null;
export const Example = ()=><>
    <div xcss={legacyStyles}>legacy</div>
    <div className={ax([
        "_4cvr1q9y _1bah1h6o _2rko12b0 _11c82smr _189ee4h9 _1dqonqa1 _1h6d1j28 _1rjc12x7 _18zrutpp _1bsb1wug _p12f1osq _gy1p1b66 _c71lzwfg _k48p1wq8 _80omtlke _1jhm5e4z _y2mv5e4z _1ygb5e4z _13ro1i6y _1bg41i6y _1ah31i6y"
    ])}>refresh</div>
  </>;
