/* .tmp-swc-column-gap-prefix-1765439408215-26cf94d01b9d9.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { xcss } from '@atlaskit/primitives';
const legacyStyles = xcss({
    display: 'inline-flex',
    columnGap: 'space.050',
    maxWidth: '100%',
    alignItems: 'baseline',
    justifyContent: 'center'
});
const refreshedStyles = null;
export const Example = ()=><>
    <div xcss={legacyStyles}>legacy</div>
    <div className={ax([])}>refresh</div>
  </>;
