/* .tmp-swc-css-template-with-expressions-1765439413034-43a4c75ab3b3d.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const theme = {
    primary: '#007bff',
    secondary: '#6c757d',
    spacing: {
        small: '8px',
        medium: '16px',
        large: '24px'
    }
};
const buttonStyles = null;
export const Component = ({ children, onClick })=>{
    return (<button onClick={onClick} className={ax([])}>
      {children}
    </button>);
};
