/* .tmp-swc-css-template-with-expressions-1764360570843-af9e09c89db4f.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const theme = {
    primary: '#007bff',
    secondary: '#6c757d',
    spacing: {
        small: '8px',
        medium: '16px',
        large: '24px'
    }
};
const buttonStyles = null;
export const Component = ({ children, onClick })=>{
    return (<button onClick={onClick} className={ax([
        "_ca0q7vkz _u5f37vkz _n3td7vkz _19bv7vkz _19itxtig _2rko1y44 _v5641hdd _bfhk130e _syazu67f _1wybdlk8 _80omtlke _irr3i6ib _4cvxi6ib _nt75130e _49pcnqa1 _1hvwyh40 _1bg4yh40"
    ])}>
      {children}
    </button>);
};
