/* in.tsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
const QuarterPickerContainer = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_12apidpf _hxt6idpf _7rs5idpf _cs56idpf _osiy1ssb _1yp31ssb _1mizidpf _1v09idpf _d4l7idpf _1ilridpf _8jx714y2 _2gv614y2 _1ko9idpf _15h6idpf _wvzr1nzx _t74o1nzx _1u1q1nzx _1p4f1nzx _r6ob1nzx _1kne1nzx _925w1h6o", __cmplp.className])} />;
});
if (process.env.NODE_ENV !== 'production') {
  QuarterPickerContainer.displayName = 'QuarterPickerContainer';
}
const QuarterPicker = () => <QuarterPickerContainer>
    <button>
      <span>Custom</span>
    </button>
    <div>Quarter</div>
  </QuarterPickerContainer>;
export default QuarterPicker;
