/* .tmp-swc-quarter-picker-selector-1765439420183-818d4470aa161.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const QuarterPickerContainer = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    QuarterPickerContainer.displayName = "QuarterPickerContainer";
}
const QuarterPicker = ()=>(<QuarterPickerContainer>
    <button>
      <span>Custom</span>
    </button>
    <div>Quarter</div>
  </QuarterPickerContainer>);
export default QuarterPicker;
