/* .tmp-swc-navigation-system-root-xcss-classname-1765437470633-6dcfa6b4f149d.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
const styles = {
    root: ""
};
export function Root({ children, xcss, testId }) {
    return (<div className={ax([
        styles.root,
        xcss
    ])} data-testid={testId}>
			{children}
		</div>);
}
