/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix } from "@compiled/react/runtime";
import React from "react";
const styles = {
	root: "_1lmcq9em _yv0ei47z _2z0516ab _1e0c11p5 _1tke1kxc _1ciragmp _12fkuz0r _12qzrxre _1rqt70if",
};
export function Root({ children, xcss, testId }) {
	return (
		<div className={ax([styles.root, xcss])} data-testid={testId}>
			{children}
		</div>
	);
}
