/* .tmp-swc-onboarding-target-unterminated-jsx-1764029525548-fecaac5c4de4b.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const reduceMotionAsPerUserPreference = null;
const baseShadow = `0 0 0 2px ${'var(--ds-border-discovery, #AF59E1)'}`;
const easing = 'cubic-bezier(0.55, 0.055, 0.675, 0.19)';
const pulseKeyframes = null;
const animationStyles = null;
const Base = ({ bgColor, children, className, radius, testId, style, ...props })=>(<div className={className} data-testid={testId} style={{
        ...style,
        backgroundColor: bgColor,
        borderRadius: radius ? `${radius}px` : undefined
    }} {...props}>
    {children}
  </div>);
export const TargetInner = ({ bgColor, children, className, pulse, radius, testId, ...props })=>(<Base bgColor={bgColor} className={ax([
        pulse && "",
        pulse && "_5sagi11n _tip812c5 _j7hq1mi7 _1pglmcjr _16qs1peg",
        "_1bumglyw _sedtglyw",
        className
    ])} radius={radius} testId={testId} {...props} style={props.style}>
    {children}
  </Base>);
