/* .tmp-swc-metric-text-cssmap-mixed-1765408346448-4780444ed907a.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React, { forwardRef } from 'react';
const styles = {
    root: "",
    'textAlign.center': "",
    'textAlign.end': "",
    'textAlign.start': ""
};
const fontSizeMap = {
    small: "",
    medium: "",
    large: ""
};
const MetricText = forwardRef((props, ref)=>{
    const { as: Component = 'span', align, testId, id, size, children } = props;
    return (<Component ref={ref} className={`
				${styles.root()}
				${size ? fontSizeMap[size]() : ''}
				${align ? styles[`textAlign.${align}`]() : ''}
			`.trim()} data-testid={testId} id={id}>
			{children}
		</Component>);
});
MetricText.displayName = 'MetricText';
export default MetricText;
