/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React, { forwardRef } from 'react';
const styles = {
    root: "_19pkidpf _2hwxidpf _otyridpf _18u0idpf",
    'textAlign.center': "_y3gn1h6o",
    'textAlign.end': "_y3gnh9n0",
    'textAlign.start': "_y3gnv2br"
};
const fontSizeMap = {
    small: "_1wyb1crf",
    medium: "_1wyb7vkz",
    large: "_1wyb1tcg"
};
const MetricText = forwardRef((props, ref)=>{
    const { as: Component = 'span', align, testId, id, size, children } = props;
    return (<Component ref={ref} className={`
				${styles.root()}
				${size ? fontSizeMap[size]() : ''}
				${align ? styles[`textAlign.${align}`]() : ''}
			`.trim()} data-testid={testId} id={id}>
			{children}
		</Component>);
});
MetricText.displayName = 'MetricText';
export default MetricText;
