/* .tmp-swc-styled-clickable-banner-1765938259975-b22ae840b1bdf.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const containerBackgrounds = {
    information: {
        default: 'info-default',
        hovered: 'info-hovered',
        active: 'info-active'
    },
    warning: {
        default: 'warn-default',
        hovered: 'warn-hovered',
        active: 'warn-active'
    }
};
const Container = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { hasAction: hasAction, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={{
        ...__cmpls,
        "--_y6477n": ix(__cmplp.hasAction && 'pointer'),
        "--_uotol0": ix(containerBackgrounds[__cmplp.type].default),
        "--_p92on0": ix(__cmplp.spacing),
        "--_1qak2ff": ix(containerBackgrounds[__cmplp.type].hovered),
        "--_1yb3cim": ix(containerBackgrounds[__cmplp.type].active)
    }} ref={__cmplr} className={ax([
        "_11q71qmv _18zr10ul _1rjcftgi _80om87zm _xvyzuvh6 _c2zzuvh6 _1du2m6ea _19lcm6ea _11kduvh6 _j6xt1euz",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Container.displayName = "Container";
}
export const Component = ({ hasAction = true, type = 'information', spacing = '16px' })=>(<Container hasAction={hasAction} type={type} spacing={spacing}>
		Content
		<span data-component-selector="shortcut-icon-lQi8">icon</span>
	</Container>);
