/* .tmp-swc-styled-clickable-banner-1765927678500-deb77055439c5.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const containerBackgrounds = {
    information: {
        default: 'info-default',
        hovered: 'info-hovered',
        active: 'info-active'
    },
    warning: {
        default: 'warn-default',
        hovered: 'warn-hovered',
        active: 'warn-active'
    }
};
const Container = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { hasAction: hasAction, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={{
        ...__cmpls,
        "--_y6477n": ix(__cmplp.hasAction && 'pointer'),
        "--_p92on0": ix(__cmplp.spacing)
    }} ref={__cmplr} className={ax([
        "_18zr10ul _1rjcftgi _80om87zm _1qu91bte _jxjtf6vs _1882dfwi _ntmnqqx0 _1psk1usc _8n4k1ux6 _n20f1bte _5v0d1bte _1mfpf6vs _1hmjf6vs _1855dfwi _7m96dfwi _1l1aqqx0 _gwk6qqx0 _ojbw1usc _1w8t1usc _ar451ux6 _htyt1ux6 _xvyzuvh6 _c2zzuvh6 _10q41bte _1ifxf6vs _z5k3dfwi _1m8iqqx0 _1vpe1usc _1of81ux6 _11kduvh6",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Container.displayName = "Container";
}
export const Component = ({ hasAction = true, type = 'information', spacing = '16px' })=>(<Container hasAction={hasAction} type={type} spacing={spacing}>
		Content
		<span data-component-selector="shortcut-icon-lQi8">icon</span>
	</Container>);
