/* .tmp-swc-css-template-arrow-map-1764368029370-bbe6611baf3ae.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const MAP = {
    small: 16,
    medium: 24
} as const;
const Avatar = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={{
        ...__cmpls,
        "--_u081c2": ix(MAP[__cmplp.size], "px")
    }} ref={__cmplr} className={ax([
        "_2rko1y44 _4t3i1si1 _1bsb1si1",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Avatar.displayName = "Avatar";
}
export default Avatar;
