/* .tmp-swc-styled-dynamic-computed-selector-1765408354371-5b29020bb6959.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
const selectors = {
    helper: 'helper-class',
    id: 'target-id'
};
const Component = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { isActive: isActive, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax([
        "",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Component.displayName = "Component";
}
export const Styled = ()=>(<Component isActive>
    <span className="helper-class">Helper</span>
    <span id="target-id">Target</span>
  </Component>);
