/* .tmp-swc-styled-dynamic-computed-selector-1765752976453-c31d4db7921c.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
const selectors = {
    helper: 'helper-class',
    id: 'target-id'
};
const Component = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { isActive: isActive, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax([
        "_1ud41y44 _tozs1y44 _38gu1y44 _mn4j1y44 _12nkftgi _syaz15td _10r21a6z _10jz105o",
        __cmplp.isActive ? "_bfhk1paw" : "_bfhk1i1c",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Component.displayName = "Component";
}
export const Styled = ()=>(<Component isActive>
    <span className="helper-class">Helper</span>
    <span id="target-id">Target</span>
  </Component>);
