/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix } from "@compiled/react/runtime";
import * as React from "react";
const base = {
	fontSize: "16px",
	color: "purple",
	padding: "8px",
};
const overrides = {
	color: "purple",
	padding: "10px",
	border: "1px solid black",
};
const conditional = {
	color: "teal",
	backgroundColor: "beige",
};
export const spreadExample = null;
export const spreadTemplate = null;
export const SpreadExampleComponent = () => (
	<main
		className={ax([
			"_1e0c1txw _1wyb7vkz _syaz1cnh _ca0qftgi _u5f3ftgi _n3tdftgi _19bvftgi _zulp1fwx _ca0q19bv _u5f319bv _n3td19bv _19bv19bv _19it97hw _syaz1my7 _bfhk188t _syazd5lx",
			"_2rko1y44 _16qsz314",
		])}
	>
		spread styles
	</main>
);
