/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix } from '@compiled/react/runtime';
import * as React from 'react';
const base = {
  fontSize: '16px',
  color: 'purple',
  padding: '8px',
};
const overrides = {
  color: 'purple',
  padding: '10px',
  border: '1px solid black',
};
const conditional = {
  ...(true
    ? {
        color: 'teal',
      }
    : {}),
  backgroundColor: 'beige',
};
export const spreadExample = null;
export const spreadTemplate = null;
export const SpreadExampleComponent = () => (
  <main className={[spreadExample, spreadTemplate].join(' ')}>spread styles</main>
);
