/* .tmp-swc-spread-duplicates-1764044658214-2fb8160c1a002.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const base = {
    fontSize: '16px',
    color: 'purple',
    padding: '8px'
};
const overrides = {
    color: 'purple',
    padding: '10px',
    border: '1px solid black'
};
const conditional = {
    color: 'teal',
    backgroundColor: 'beige'
};
export const spreadExample = null;
export const spreadTemplate = null;
export const SpreadExampleComponent = ()=>(<main className={ax([
        "_zulp1crf _ca0q19bv _u5f319bv _n3td19bv _19bv19bv _19it1ujt _1e0c1txw _1wyb7vkz _bfhk188t _syazd5lx",
        "_2rko1y44 _16qs1r5l"
    ])}>
    spread styles
  </main>);
