/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const base = {
	fontSize: "16px",
	color: "purple",
	padding: "8px",
};
const overrides = {
	color: "purple",
	padding: "10px",
	border: "1px solid black",
};
const conditional = {
	color: "teal",
	backgroundColor: "beige",
};
export const spreadExample = null;
export const spreadTemplate = null;
export const SpreadExampleComponent = () => (
	<main
		className={ax([
			"_313o1txw _1knu7vkz _9ad01cnh _gq7jftgi _g4701crf _gq7j19bv _1qfs1ujt _9ad01my7 _1n55188t _9ad0d5lx",
			"_1qpb1y44 _z2s51r5l",
		])}
	>
		spread styles
	</main>
);
