/* .tmp-swc-spread-duplicates-1765437472453-954e2115dc55a.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const base = {
    fontSize: '16px',
    color: 'purple',
    padding: '8px'
};
const overrides = {
    color: 'purple',
    padding: '10px',
    border: '1px solid black'
};
const conditional = {
    color: 'teal',
    backgroundColor: 'beige'
};
export const spreadExample = null;
export const spreadTemplate = null;
export const SpreadExampleComponent = ()=>(<main className={ax([])}>
    spread styles
  </main>);
