/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = () => (
	<div className={ax(["_1kt9b3bt _aetr1e8g _1q7w1isi"])}>
		<span data-label="test" />
	</div>
);
