/* .tmp-swc-css-content-selectors-1764627624481-cc7daba78b2c5.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=>(<div className={ax([
        "_1q7w1isi _1kt9b3bt _aetr1e8g"
    ])}>
    <span data-label="test"/>
  </div>);
