/* .tmp-swc-css-content-selectors-1765437465001-c75b49da35408.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=>(<div className={ax([])}>
    <span data-label="test"/>
  </div>);
