/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
function Component() {
  return <div className={ax([])}>
      Hello World
    </div>;
}
