/* .tmp-swc-css-prop-inline-1765439412618-b1ff06d343c88.jsx generated by @compiled/babel-plugin v0.38.1 */
;
function Component() {
    return (<div className={ax([])}>
      Hello World
    </div>);
}
