/* .tmp-swc-css-prop-inline-1765408338134-874207495d558.jsx generated by @compiled/babel-plugin v0.38.1 */
;
function Component() {
    return (<div className={ax([])}>
      Hello World
    </div>);
}
