/* .tmp-swc-css-prop-inline-1763860975211-90dbf8eee3a3c.jsx generated by @compiled/babel-plugin v0.38.1 */
;
function Component() {
    return (<div className={ax([
        "_ca0qftgi _u5f3ftgi _n3tdftgi _19bvftgi _syaz5scu _bfhk13q2 _30l3bf54"
    ])}>
      Hello World
    </div>);
}
