/* .tmp-swc-css-prop-inline-1765437466401-c876999e99501.jsx generated by @compiled/babel-plugin v0.38.1 */
;
function Component() {
    return (<div className={ax([])}>
      Hello World
    </div>);
}
