/* .tmp-swc-css-prop-nested-rules-1764034567906-349c7971d82c1.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
export const styles = null;
