/* .tmp-swc-css-prop-nested-rules-1765439412693-f22a5a25f8246.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
export const styles = null;
