/* .tmp-swc-css-prop-nested-rules-1765404344494-6b60532aa4ccd.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
export const styles = null;
