/* .tmp-swc-css-prop-nested-rules-1765408338250-b32ab55d674d7.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
export const styles = null;
