/* .tmp-swc-css-prop-nested-rules-1765437466447-aa7e2fad2e78d.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
export const styles = null;
