/* .tmp-swc-css-prop-nested-rules-1765927672537-6e49da38a672d.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
export const styles = null;
