/* .tmp-swc-xcss-inline-object-1765439429242-daa3bd6796beb.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const Component = ()=>(<div xcss={undefined}/>);
export default Component;
