/* .tmp-swc-xcss-inline-object-1765930121315-b416df2a609f2.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const Component = ()=>(<div xcss={"_syaz5scu _bfhk13q2"}/>);
export default Component;
