/* .tmp-swc-xcss-inline-object-1765408361929-e75d63fdbc5ab.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const Component = ()=>(<div xcss={undefined}/>);
export default Component;
