/* .tmp-swc-xcss-inline-object-1765437477655-c35dc516f5e25.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const Component = ()=>(<div xcss={undefined}/>);
export default Component;
