/* .tmp-swc-xcss-inline-object-1763696015786-8c969f1764ce7.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const Component = ()=>(<div xcss={"_syaz5scu _bfhk13q2"}/>);
export default Component;
