/* .tmp-swc-xcss-inline-object-1764358663027-e70b40d19c7c4.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const Component = ()=>(<div xcss={"_syaz5scu _bfhk13q2"}/>);
export default Component;
