use std::env;
use std::fs;
use std::path::PathBuf;

use serde::{Deserialize, Serialize};
use swc_core::common::{FileName, SourceMap};
use swc_core::ecma::ast::EsVersion;
use swc_core::ecma::ast::Program;
use swc_core::ecma::codegen::{text_writer::JsWriter, Emitter};
use swc_ecma_parser::{lexer::Lexer, Parser, StringInput, Syntax, TsSyntax};

use compiled_babel::{
    transform_with_file as compiled_transform, PluginOptions as CompiledOptions, TransformFile,
    TransformFileOptions,
};
use compiled_strip_runtime::{transform as strip_transform, TransformConfig as StripConfig};

#[derive(Debug, Deserialize, Default)]
#[serde(default)]
struct FixtureConfig {
    extract: Option<bool>,
    #[serde(rename = "classNameCompressionMap")]
    class_name_compression_map: Option<std::collections::BTreeMap<String, String>>,
}

#[derive(Debug, Serialize)]
struct CliOutput {
    code: String,
    #[serde(rename = "styleRules")]
    style_rules: Vec<String>,
}

fn parse_program(
    cm: &swc_core::common::sync::Lrc<SourceMap>,
    filename: &str,
    src: &str,
) -> Program {
    let fm = cm.new_source_file(
        FileName::Real(PathBuf::from(filename)).into(),
        src.to_string(),
    );
    let lexer = Lexer::new(
        Syntax::Typescript(TsSyntax {
            tsx: true,
            ..Default::default()
        }),
        EsVersion::Es2022,
        StringInput::from(&*fm),
        None,
    );
    let mut parser = Parser::new_from(lexer);
    parser.parse_program().expect("failed to parse program")
}

fn print_program(cm: &swc_core::common::sync::Lrc<SourceMap>, program: &Program) -> String {
    let mut buf = Vec::new();
    {
        let mut emitter = Emitter {
            cfg: swc_ecma_codegen::Config::default(),
            comments: None,
            cm: cm.clone(),
            wr: JsWriter::new(cm.clone(), "\n", &mut buf, None),
        };
        match program {
            Program::Module(m) => emitter.emit_module(m).expect("emit failed"),
            Program::Script(s) => emitter.emit_script(s).expect("emit failed"),
        }
    }
    String::from_utf8(buf).expect("non utf8 output")
}

fn header_comment_for(path: &str) -> String {
    use std::path::Path;
    let filename = Path::new(path)
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("File");
    let version =
        env::var("TEST_PKG_VERSION").unwrap_or_else(|_| env!("CARGO_PKG_VERSION").to_string());
    format!(
        "/* {} generated by @compiled/babel-plugin v{} */\n",
        filename, version
    )
}

fn main() {
    if std::env::var("COMPILED_CLI_TRACE").is_ok() {
        eprintln!("[cli] entry");
    }
    let mut args = env::args().skip(1);
    let input_path = args.next().expect("usage: fixtures_cli <input_path>");

    let input_code = fs::read_to_string(&input_path).expect("read input");

    // Load optional config.json next to input
    let mut cfg = FixtureConfig::default();
    if let Some(parent) = PathBuf::from(&input_path).parent() {
        let cfg_path = parent.join("config.json");
        if cfg_path.exists() {
            if let Ok(text) = fs::read_to_string(&cfg_path) {
                if let Ok(parsed) = serde_json::from_str::<FixtureConfig>(&text) {
                    cfg = parsed;
                }
            }
        }
    }

    let cm: swc_core::common::sync::Lrc<SourceMap> = Default::default();
    if std::env::var("COMPILED_CLI_TRACE").is_ok() {
        eprintln!("[cli] parse begin");
    }
    let program = parse_program(&cm, &input_path, &input_code);
    if std::env::var("COMPILED_CLI_TRACE").is_ok() {
        eprintln!("[cli] parse done");
    }

    let compiled_opts = CompiledOptions {
        cache: Some(compiled_babel::CacheBehavior::Enabled(false)),
        import_react: Some(true),
        optimize_css: Some(true),
        class_name_compression_map: cfg.class_name_compression_map,
        extract: Some(cfg.extract.unwrap_or(true)),
        ..CompiledOptions::default()
    };
    let tf = TransformFile::with_options(
        cm.clone(),
        Vec::new(),
        TransformFileOptions {
            filename: Some(input_path.clone()),
            ..Default::default()
        },
    );
    if std::env::var("COMPILED_CLI_TRACE").is_ok() {
        eprintln!("[cli] compiled begin");
    }
    let out1 = compiled_transform(program, tf, compiled_opts);
    if std::env::var("COMPILED_CLI_TRACE").is_ok() {
        eprintln!("[cli] compiled done");
    }

    // Pass through strip-runtime
    let strip_cfg = StripConfig {
        filename: Some(input_path.clone()),
        options: compiled_strip_runtime::PluginOptions {
            compiled_require_exclude: Some(true),
            ..Default::default()
        },
        ..Default::default()
    };
    if std::env::var("COMPILED_CLI_TRACE").is_ok() {
        eprintln!("[cli] strip begin");
    }
    let out2 = strip_transform(out1.program, strip_cfg);
    if std::env::var("COMPILED_CLI_TRACE").is_ok() {
        eprintln!("[cli] strip done");
    }

    // Prefer strip-runtime style rules if available, else compiled
    let mut style_rules = if !out2.metadata.style_rules.is_empty() {
        out2.metadata.style_rules
    } else {
        out1.metadata.style_rules
    };
    style_rules.retain(|rule| rule.contains('{'));

    let mut code = print_program(&cm, &out2.program);
    if !code.contains("generated by @compiled/babel-plugin") {
        let header = header_comment_for(&input_path);
        code = format!("{}{}", header, code);
    }

    let result = CliOutput { code, style_rules };
    if std::env::var("COMPILED_CLI_TRACE").is_ok() {
        eprintln!("[cli] output ready");
    }
    println!("{}", serde_json::to_string(&result).unwrap());
}
