use std::env;
use std::fs;
use std::path::PathBuf;
use std::time::Instant;

use serde::{Deserialize, Serialize};
use serde_json;
use swc_core::common::comments::{Comment, SingleThreadedComments};
use swc_core::common::{FileName, SourceMap};
use swc_core::ecma::ast::EsVersion;
use swc_core::ecma::ast::Program;
use swc_core::ecma::codegen::{text_writer::JsWriter, Emitter};
use swc_ecma_parser::{lexer::Lexer, Parser, StringInput, Syntax, TsSyntax};

use compiled_babel::{
  transform_with_file as compiled_transform, PluginOptions as CompiledOptions, ResolverCompatOptions,
  ResolverOption, TransformFile, TransformFileOptions,
};
use compiled_strip_runtime::{transform as strip_transform, TransformConfig as StripConfig};

#[derive(Debug, Deserialize, Default)]
#[serde(default)]
struct FixtureConfig {
  extract: Option<bool>,
  #[serde(rename = "classNameCompressionMap")]
  class_name_compression_map: Option<std::collections::BTreeMap<String, String>>,
}

#[derive(Debug, Serialize)]
struct CliOutput {
  code: String,
  #[serde(rename = "styleRules")]
  style_rules: Vec<String>,
  #[serde(skip_serializing_if = "Option::is_none")]
  timings: Option<Timings>,
}

#[derive(Debug, Serialize)]
struct Timings {
  #[serde(rename = "totalMs")]
  total_ms: f64,
  #[serde(rename = "postcssMs")]
  postcss_ms: f64,
  #[serde(rename = "postcssPluginMs")]
  postcss_plugin_ms: f64,
}

fn parse_program(
  cm: &swc_core::common::sync::Lrc<SourceMap>,
  filename: &str,
  src: &str,
) -> (Program, Vec<Comment>) {
  let fm = cm.new_source_file(
    FileName::Real(PathBuf::from(filename)).into(),
    src.to_string(),
  );
  // COMPAT: Preserve comments so hashing matches Babel's generate() output.
  let comments = SingleThreadedComments::default();
  let lexer = Lexer::new(
    Syntax::Typescript(TsSyntax {
      tsx: true,
      ..Default::default()
    }),
    EsVersion::Es2022,
    StringInput::from(&*fm),
    Some(&comments),
  );
  let mut parser = Parser::new_from(lexer);
  let program = parser.parse_program().expect("failed to parse program");
  let mut collected: Vec<Comment> = Vec::new();
  let (leading, trailing) = comments.take_all();

  {
    let mut leading = leading.borrow_mut();
    for (_, mut list) in leading.drain() {
      collected.append(&mut list);
    }
  }

  {
    let mut trailing = trailing.borrow_mut();
    for (_, mut list) in trailing.drain() {
      collected.append(&mut list);
    }
  }

  (program, collected)
}

fn print_program(cm: &swc_core::common::sync::Lrc<SourceMap>, program: &Program) -> String {
  let mut buf = Vec::new();
  {
    let mut emitter = Emitter {
      cfg: swc_ecma_codegen::Config::default(),
      comments: None,
      cm: cm.clone(),
      wr: JsWriter::new(cm.clone(), "\n", &mut buf, None),
    };
    match program {
      Program::Module(m) => emitter.emit_module(m).expect("emit failed"),
      Program::Script(s) => emitter.emit_script(s).expect("emit failed"),
    }
  }
  String::from_utf8(buf).expect("non utf8 output")
}

fn header_comment_for(path: &str) -> String {
  use std::path::Path;
  let filename = Path::new(path)
    .file_name()
    .and_then(|s| s.to_str())
    .unwrap_or("File");
  let version =
    env::var("TEST_PKG_VERSION").unwrap_or_else(|_| env!("CARGO_PKG_VERSION").to_string());
  format!(
    "/* {} generated by @compiled/babel-plugin v{} */\n",
    filename, version
  )
}

fn resolver_from_env() -> Option<ResolverOption> {
  env::var("COMPILED_FIXTURES_RESOLVER")
    .ok()
    .and_then(|raw| {
      serde_json::from_str::<serde_json::Value>(&raw)
        .map(ResolverOption::Inline)
        .ok()
        .or_else(|| Some(ResolverOption::Module(raw)))
    })
}

fn resolver_compat_from_env() -> Option<ResolverCompatOptions> {
  env::var("COMPILED_FIXTURES_RESOLVER_COMPAT")
    .ok()
    .and_then(|raw| serde_json::from_str::<ResolverCompatOptions>(&raw).ok())
}

fn main() {
  let start = Instant::now();
  if std::env::var("COMPILED_CLI_TRACE").is_ok() {
    eprintln!("[cli] entry");
  }
  let debug_rules = std::env::var("COMPILED_CLI_DEBUG_STYLE_RULES").is_ok();
  if debug_rules {
    eprintln!("[cli] debug style rules enabled");
  }
  let mut args = env::args().skip(1);
  let input_path = args.next().expect("usage: fixtures_cli <input_path>");

  let input_code = fs::read_to_string(&input_path).expect("read input");

  // Load optional config.json next to input
  let mut cfg = FixtureConfig::default();
  if let Some(parent) = PathBuf::from(&input_path).parent() {
    let cfg_path = parent.join("config.json");
    if cfg_path.exists() {
      if let Ok(text) = fs::read_to_string(&cfg_path) {
        if let Ok(parsed) = serde_json::from_str::<FixtureConfig>(&text) {
          cfg = parsed;
        }
      }
    }
  }

  let cm: swc_core::common::sync::Lrc<SourceMap> = Default::default();
  if std::env::var("COMPILED_CLI_TRACE").is_ok() {
    eprintln!("[cli] parse begin");
  }
  let (program, comments) = parse_program(&cm, &input_path, &input_code);
  if std::env::var("COMPILED_CLI_TRACE").is_ok() {
    eprintln!("[cli] parse done");
  }

  let resolver = resolver_from_env();
  let resolver_compat = resolver_compat_from_env();

  let compiled_opts = CompiledOptions {
    cache: Some(compiled_babel::CacheBehavior::Enabled(false)),
    import_react: Some(true),
    optimize_css: Some(true),
    class_name_compression_map: cfg.class_name_compression_map,
    extract: Some(cfg.extract.unwrap_or(true)),
    resolver,
    resolver_compat,
    ..CompiledOptions::default()
  };
  let tf = TransformFile::with_options(
    cm.clone(),
    comments,
    TransformFileOptions {
      filename: Some(input_path.clone()),
      ..Default::default()
    },
  );
  if std::env::var("COMPILED_CLI_TRACE").is_ok() {
    eprintln!("[cli] compiled begin");
  }
  let out1 = compiled_transform(program, tf, compiled_opts);
  if std::env::var("COMPILED_CLI_TRACE").is_ok() {
    eprintln!("[cli] compiled done");
  }
  if debug_rules {
    let compiled_code = print_program(&cm, &out1.program);
    eprintln!("[cli] compiled code:\n{}", compiled_code);
    eprintln!(
      "[cli] compiled metadata: {} style_rules: {:?}",
      out1.metadata.style_rules.len(),
      out1.metadata.style_rules
    );
  }

  // Pass through strip-runtime
  let strip_cfg = StripConfig {
    filename: Some(input_path.clone()),
    options: compiled_strip_runtime::PluginOptions {
      compiled_require_exclude: Some(true),
      ..Default::default()
    },
    ..Default::default()
  };
  if std::env::var("COMPILED_CLI_TRACE").is_ok() {
    eprintln!("[cli] strip begin");
  }
  let out2 = strip_transform(out1.program, strip_cfg);
  if std::env::var("COMPILED_CLI_TRACE").is_ok() {
    eprintln!("[cli] strip done");
  }
  if debug_rules {
    let stripped_code = print_program(&cm, &out2.program);
    eprintln!("[cli] strip code:\n{}", stripped_code);
    eprintln!(
      "[cli] strip metadata: {} style_rules: {:?}",
      out2.metadata.style_rules.len(),
      out2.metadata.style_rules
    );
  }

  // Prefer strip-runtime style rules if available, else compiled
  let mut style_rules = if !out2.metadata.style_rules.is_empty() {
    out2.metadata.style_rules
  } else {
    out1.metadata.style_rules
  };
  style_rules.retain(|rule| rule.contains('{'));

  let mut code = print_program(&cm, &out2.program);
  if !code.contains("generated by @compiled/babel-plugin") {
    let header = header_comment_for(&input_path);
    code = format!("{}{}", header, code);
  }

  let postcss_ns = compiled_babel::postcss::metrics::take_postcss_ns();
  let postcss_plugin_ns = compiled_babel::postcss::metrics::take_postcss_plugin_ns();
  let total_ms = start.elapsed().as_secs_f64() * 1000.0;
  let timings = Some(Timings {
    total_ms,
    postcss_ms: postcss_ns as f64 / 1_000_000.0,
    postcss_plugin_ms: postcss_plugin_ns as f64 / 1_000_000.0,
  });

  let result = CliOutput {
    code,
    style_rules,
    timings,
  };
  if std::env::var("COMPILED_CLI_TRACE").is_ok() {
    eprintln!("[cli] output ready");
  }
  println!("{}", serde_json::to_string(&result).unwrap());
}
