/* .tmp-swc-css-custom-property-length-1765246826569-db9e08adb020b.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const className = null;
export const Component = ()=><div className={ax([
        "_9p01fyhu"
    ])}>custom property</div>;
