/* .tmp-swc-css-custom-property-length-1765408335452-09c3b84413f9b.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const className = null;
export const Component = ()=><div className={ax([])}>custom property</div>;
