/* .tmp-swc-css-custom-property-length-1765437465052-dff73fde08071.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const className = null;
export const Component = ()=><div className={ax([])}>custom property</div>;
