/* .tmp-swc-css-custom-property-length-1764109956403-811809d0387b1.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const className = null;
export const Component = ()=><div className={ax([
        "_9p01fyhu"
    ])}>custom property</div>;
