/* .tmp-swc-editor-big-1764713728657-e85c6f6f05aad.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React, { useState, useMemo, useCallback, useContext, createContext } from 'react';
const EditorThemeContext = createContext({
    mode: 'light'
});
const containerStyles = null;
const toolbarStyles = null;
const editorStyles = null;
const statusStyles = null;
const badgeStyles = null;
const ToneBadge = ({ mode })=>(<span style={{
        color: mode === 'dark' ? '#9BE7FF' : '#1D7AFC'
    }} className={ax([
        "_ca0qyh40 _u5f3i2wt _n3tdyh40 _19bvi2wt _2rkow7q6 _19itx2ht _1wyb19bv _1p1dangw"
    ])}>
    {mode} mode
  </span>);
const ToolbarButton = ({ active, label, onClick })=>(<button type="button" data-active={active} onClick={onClick}>
    {label}
  </button>);
const EditorShell = ()=>{
    const [value, setValue] = useState('Type something beautiful…');
    const [bold, setBold] = useState(false);
    const [italics, setItalics] = useState(false);
    const [mode, setMode] = useState('light');
    const wordCount = useMemo(()=>value.trim().split(/\s+/).filter(Boolean).length, [
        value
    ]);
    const handleToggle = useCallback((setter)=>()=>setter((prev)=>!prev), []);
    const contextValue = useMemo(()=>({
            mode,
            toggleMode: ()=>setMode((prev)=>(prev === 'light' ? 'dark' : 'light'))
        }), [
        mode
    ]);
    return (<EditorThemeContext.Provider value={contextValue}>
      <section aria-label="Rich text editor" className={ax([
        "_zulp7vkz _ca0q1tcg _u5f31tcg _n3td1tcg _19bv1tcg _2rko7vkz _1e0c11p5 _bfhk1hxd"
    ])}>
        <header className={ax([
        "_1n261g80 _zulpftgi _stfgokh7 _zs121y44 _1gfl1y44 _yhjmftgi _1gqn1y44 _11lvftgi _19e7owjk _1e0c1txw _1uegowjk _1o7p1crf _1i49angw _7dir1j28 _4rtxtlke _m4w23739 _6pupu67f"
    ])}>
          <ToolbarButton active={bold} label="Bold" onClick={handleToggle(setBold)}/>
          <ToolbarButton active={italics} label="Italics" onClick={handleToggle(setItalics)}/>
          <ToolbarButton active={mode === 'dark'} label="Toggle theme" onClick={()=>contextValue.toggleMode()}/>
        </header>
        <textarea style={{
        fontWeight: bold ? 600 : 400,
        fontStyle: italics ? 'italic' : 'normal'
    }} value={value} onChange={(event)=>setValue(event.target.value)} className={ax([
        "_ca0q7vkz _u5f37vkz _n3td7vkz _19bv7vkz _2rko1crf _19it1i89 _1tkeuuw1 _bfhku67f _1wybo7ao _vwz4yu22 _nt75b0wy _49pcnqa1 _1hvwyh40 _1bg4yh40"
    ])}/>
        <footer className={ax([
        "_1bah1yb4 _1e0c1txw _1wyb1crf _syaz9sh9"
    ])}>
          <span>{wordCount} words</span>
          <EditorStatus/>
        </footer>
      </section>
    </EditorThemeContext.Provider>);
};
const EditorStatus = ()=>{
    const { mode } = useContext(EditorThemeContext);
    return <ToneBadge mode={mode}/>;
};
export const Component = ()=><EditorShell/>;
