/* .tmp-swc-timeline-main-container-1763973275772-8f4bcb812256b.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React, { type FC } from 'react';
type Props = {
    children?: React.ReactNode;
};
export const MainContainer: FC<Props> = ({ children, ...props })=>{
    return <div {...props} className={ax([
        "_2lx21bp4 _1n261q9c _2rko1mok _1h6dmuej _1dqonqa1 _1e0c1txw _1reo15vq _18m915vq _kqswh2mm"
    ])}>
      {children}
    </div>;
};
const styles = null;
