/* .tmp-swc-timeline-main-container-1763963512220-e03d0d1100c6f.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
const styles = null;
export const Component = ()=><div className={ax([
        "_2lx21bp4 _1n261q9c _2rko1mok _1h6dmuej _1dqonqa1 _1e0c1txw"
    ])}/>;
