/* .tmp-swc-timeline-main-container-1765439428131-c0a33919e36a4.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React, { type FC } from 'react';
type Props = {
    children?: React.ReactNode;
};
export const MainContainer: FC<Props> = ({ children, ...props })=>{
    return <div {...props} className={ax([])}>
      {children}
    </div>;
};
const styles = null;
