/* .tmp-swc-selector-template-hash-attr-1766020319817-858af2666d197.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const READ_VIEW_CONTAINER_SELECTOR = '[data-component-selector=jira-issue-field-inline-edit-read-view-container]';
const Wrapper = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "_rhradabe",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Wrapper.displayName = "Wrapper";
}
export const Component = ()=><Wrapper/>;
