/* .tmp-swc-css-keyframes-background-position-1765437465544-a88957a04fc3e.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const shimmer = null;
const styles = null;
export const Component = ()=><div className={ax([])}/>;
