/* .tmp-swc-css-keyframes-background-position-1764318509177-4d3d2d62ebbb3.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const shimmer = null;
const styles = null;
export const Component = ()=><div className={ax([
        "_j7hq1en8 _5sag9cwz"
    ])}/>;
