/* .tmp-swc-responsive-hide-cssmap-dynamic-1765408349159-7021351128db9.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    'above.xs': "",
    'above.sm': "",
    'above.md': "",
    'above.lg': "",
    'above.xl': "",
    'below.xs': "",
    'below.sm': "",
    'below.md': "",
    'below.lg': "",
    'below.xl': ""
};
export const Hide = ({ above, below, children, as: AsElement = 'div', className })=>{
    return (<AsElement className={ax([
        above && styles[`above.${above}`],
        below && styles[`below.${below}`],
        className
    ])}>
			{children}
		</AsElement>);
};
