/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
const TableWrapper = ({
  selectedRows
}) => {
  const styles = {};
  selectedRows.forEach(index => {
    styles[`tbody tr:nth-child(${index + 1})`] = {
      backgroundColor: "var(--ds-background-selected, #E9F2FF)"
    };
  });
  return <div className={ax(["_kqswh2mm _1cuj1osq _10wbnkob"])}>
					content
				</div>;
};
export const Fixture = () => <TableWrapper selectedRows={[0, 2]} />;
