/* .tmp-swc-styled-object-spread-1765317767163-94b2901ae94a1.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const layoutStyles = {
    alignItems: 'center',
    display: 'flex',
    gap: `${'var(--ds-space-100, 8px)'}`
};
const checkboxStyles = {
    ...layoutStyles,
    borderBottom: `${'var(--ds-space-025, 2px)'} solid ${'var(--ds-border, #0B120E24)'}`,
    height: `${'var(--ds-space-500, 40px)'}`,
    width: '100%'
};
const getBackgroundColor = (checked, disabled)=>{
    if (disabled) {
        return 'var(--ds-background-accent-gray-subtlest, #F0F1F2)';
    }
    return checked ? 'var(--ds-background-accent-blue-subtlest, #E9F2FE)' : 'transparent';
};
const ProjectCheckbox = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "_4cvr1h6o _zulpu2gc _2x4gze3t _12hv12x7 _x5bdze3t _1rgf12x7 _1eq11h6o _dlecu2gc _clfdze3t _11pqze3t _q0a5ze3t _c3k8ze3t _n7zl1hrc _1e0c1txw _4t3i1jfw _1bsb1osq _bfhkysee _15pj1txw",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    ProjectCheckbox.displayName = "ProjectCheckbox";
}
export const Component = ()=>(<ProjectCheckbox checked disabled={false}>
		<label>
			<input type="checkbox"/>
			<p>Description</p>
		</label>
	</ProjectCheckbox>);
