/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
const SIZE = 16;
const Icon = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    url,
    ...__cmpldp
  } = __cmplp;
  return <C {...__cmpldp} style={{
    ...__cmpls,
    "--_wrma1b": ix(__cmplp.url, ")", "url(")
  }} ref={__cmplr} className={ax(["", __cmplp.className])} />;
});
if (process.env.NODE_ENV !== 'production') {
  Icon.displayName = 'Icon';
}
export const Component = ({
  url
}) => <Icon url={url} />;
