/* .tmp-swc-grid-cssmap-complex-1765437468678-356224edcb6ec.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
const rowGapMap = {
    'space100': "",
    'space200': "",
    'space300': "",
    'space400': ""
};
const columnGapMap = {
    'space100': "",
    'space200': "",
    'space300': "",
    'space400': ""
};
const justifyContentMap = {
    start: "",
    center: "",
    end: "",
    spaceBetween: ""
};
const alignContentMap = {
    start: "",
    center: "",
    end: "",
    spaceBetween: ""
};
const alignItemsMap = {
    start: "",
    center: "",
    baseline: "",
    end: ""
};
const baseStyles = {
    root: ""
};
const gridAutoFlowMap = {
    row: "",
    column: "",
    dense: ""
};
const Grid = (props)=>{
    const { as: Component = 'div', alignItems, alignContent, justifyContent, gap, columnGap, rowGap, children, id, autoFlow } = props;
    return (<Component id={id} className={`
				${baseStyles.root()} 
				${gap ? columnGapMap[gap]() : ''}
				${columnGap ? columnGapMap[columnGap]() : ''}
				${gap ? rowGapMap[gap]() : ''}
				${rowGap ? rowGapMap[rowGap]() : ''}
				${alignItems ? alignItemsMap[alignItems]() : ''}
				${alignContent ? alignContentMap[alignContent]() : ''}
				${justifyContent ? justifyContentMap[justifyContent]() : ''}
				${autoFlow ? gridAutoFlowMap[autoFlow]() : ''}
			`.trim()}>
			{children}
		</Component>);
};
Grid.displayName = 'Grid';
export default Grid;
