/* .tmp-swc-styled-token-nested-ternary-1764018977432-7b5d13553d051.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
export const Component = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { isRowSelected: isRowSelected, formatRuleBackgroundColor: formatRuleBackgroundColor, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={{
        ...__cmpls,
        "--_qn7x4k": ix(()=>{
            return __cmplp.isRowSelected ? "var(--ds-background-selected, #E9F2FF)" : __cmplp.formatRuleBackgroundColor ? __cmplp.formatRuleBackgroundColor : "var(--ds-background-neutral-subtle, #00000000)";
        }())
    }} ref={__cmplr} className={ax([
        "_bfhkmoow",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Component.displayName = "Component";
}
