/* .tmp-swc-styled-add-component-name-1765927678279-f6b4ce91d557b.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
export const MyDiv = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "_syaz5scu",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    MyDiv.displayName = "MyDiv";
}
