/* in.tsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
// Regression: content expression with a regex literal should not crash keyframes hashing.
const LegendName = forwardRef(({
  as: C = "span",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <C {...__cmplp} style={{
    ...__cmpls,
    "--_1tyhdq6": ix(JSON.stringify((__cmplp.name || '').replace(/\\/g, '')))
  }} ref={__cmplr} className={ax(["", __cmplp.className])} />;
});
if (process.env.NODE_ENV !== 'production') {
  LegendName.displayName = 'LegendName';
}
export const Component = () => <LegendName name="foo\\bar" />;
