/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
import { cx } from '@atlaskit/css';
const styles = {
  base: "",
  extra: ""
};
export const Component = ({
  showExtra
}) => <div xcss={cx(styles.base, showExtra ? styles.extra : null)}>content</div>;
