/* .tmp-swc-xcss-cx-css-map-1764023680845-e0936c17912da.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { cx } from '@atlaskit/css';
const styles = {
    base: "_ca0qdbr4 _syaz1wbm",
    extra: "_otyru43s"
};
export const Component = ({ showExtra })=>(<div xcss={cx(styles.base, showExtra ? styles.extra : null)}>content</div>);
