/* .tmp-swc-xcss-prop-suffix-1764368035148-6ae2b11dc976e.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    row: "_o5724jg8"
};
const Table = (props)=><div {...props}/>;
export const Component = ()=><Table rowCellXcss={styles.row}/>;
