/* .tmp-swc-xcss-prop-suffix-1765408362201-c5410ea9fce52.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    row: ""
};
const Table = (props)=><div {...props}/>;
export const Component = ()=><Table rowCellXcss={styles.row}/>;
