/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const Item = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr) => {
	if (__cmplp.innerRef) {
		throw new Error("Please use 'ref' instead of 'innerRef'.");
	}
	const { isClickable: isClickable, spaced: spaced, ...__cmpldp } = __cmplp;
	return (
		<C
			{...__cmpldp}
			style={{
				...__cmpls,
				"--_11qq6im": ix(__cmplp.isClickable ? "pointer" : "auto"),
				"--_x1dbdm": ix(__cmplp.isClickable ? "red" : "initial"),
				"--_lqb9ck": ix(__cmplp.spaced ? "0 3px" : "0"),
			}}
			ref={__cmplr}
			className={ax([
				"_56nn1vuy _80om6r3y _1n1p1r31 _5bn0glyw _1vs41o36 _13wf1547",
				__cmplp.className,
			])}
		/>
	);
});
if (process.env.NODE_ENV !== "production") {
	Item.displayName = "Item";
}
export const Component = ({ isClickable, spaced }) => (
	<Item isClickable={isClickable} spaced={spaced}>
		Content
	</Item>
);
