/* in.tsx generated by @compiled/babel-plugin v0.38.1 */
/** @jsxRuntime classic */
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
import { cx } from '@atlaskit/css';
import { Box } from '@atlaskit/primitives/compiled';
const styles = {
  card: "",
  iconContainer: ""
};
export const IconContainer = () => <Box xcss={cx(styles.card)}>
		<Box as="span" xcss={cx(styles.iconContainer)}>
			icon
		</Box>
	</Box>;
