/* .tmp-swc-icon-border-radius-token-1765752973590-f4bca1d387b0f.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { cx } from '@atlaskit/css';
import { Box } from '@atlaskit/primitives/compiled';
const styles = {
    card: "_2rko12b0",
    iconContainer: "_2rko12b0 _y3gn1h6o"
};
export const IconContainer = ()=><Box xcss={cx(styles.card)}>
		<Box as="span" xcss={cx(styles.iconContainer)}>
			icon
		</Box>
	</Box>;
