/* .tmp-swc-selector-template-hash-jira-copy-1765930117961-aa63908819edd.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const READ_VIEW_CONTAINER_SELECTOR = '[data-component-selector=jira-issue-field-inline-edit-read-view-container]';
const ORIGINAL_READ_VIEW_SELECTOR = '[data-component-selector=jira-issue-field-original-estimate-read-view-container]';
const Wrapper = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { disableClick: disableClick, isIncrementPlanningBoard: isIncrementPlanningBoard, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax([
        "_1bt61i6y _1bb7idpf _wv4j6up6 _1nf9idpf _4t3ipxbi _gx371q9c _1dbovuon",
        __cmplp.disableClick && "_lcxvglyw",
        __cmplp.isIncrementPlanningBoard && "_g51qdabe",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Wrapper.displayName = "Wrapper";
}
export const Component = ({ disableClick, isIncrementPlanningBoard })=><Wrapper disableClick={disableClick} isIncrementPlanningBoard={isIncrementPlanningBoard}/>;
