/* .tmp-swc-styled-token-conditional-border-1764713734088-56628bdb21e2.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
const Wrapper = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { isSummaryView: isSummaryView, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax([
        "",
        __cmplp.isSummaryView ? "_19itglyw" : "_19itj0fz",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Wrapper.displayName = "Wrapper";
}
export const Component = ()=><Wrapper isSummaryView={false}/>;
