/* .tmp-swc-calendar-header-cell-length-mismatch-1765437462849-aa0119b16284e.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const weekViewStyles = null;
const CalendarHeader = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { weekViewEnabled: weekViewEnabled, hasIssuesPages: hasIssuesPages, isVisualRefresh: isVisualRefresh, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={{
        ...__cmpls,
        "--_uapmxa": ix(__cmplp.weekViewEnabled && 'row')
    }} ref={__cmplr} className={ax([
        "",
        __cmplp.weekViewEnabled && "",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    CalendarHeader.displayName = "CalendarHeader";
}
const CalendarHeaderFixture = ({ weekViewEnabled = true })=><CalendarHeader weekViewEnabled={weekViewEnabled} isVisualRefresh>
		header
	</CalendarHeader>;
export default CalendarHeaderFixture;
