/* .tmp-swc-calendar-header-cell-length-mismatch-1766020314373-347f3ea14d785.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const weekViewStyles = null;
const CalendarHeader = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { weekViewEnabled: weekViewEnabled, hasIssuesPages: hasIssuesPages, isVisualRefresh: isVisualRefresh, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={{
        ...__cmpls,
        "--_uapmxa": ix(__cmplp.weekViewEnabled && 'row')
    }} ref={__cmplr} className={ax([
        "_1e2tvrvc _1tzj1h6o _1w351h6o _vrr81vhk _ogrsidpf _62pcsbjq _lkmm1vhk _l4b7sbjq _c6pa1txw _gqw31gjq _8wp8moej _1vsm1dk0 _wwc41gjq _fuolmoej _66cp1dk0",
        __cmplp.weekViewEnabled && "_1du31vhk _162m1b66 _o0k41vhk _7u3q1vhk _ahuqglyw _1va6glyw _1nl2glyw _12vt1gjq _qcb21pd9 _1hox1wug _15oh1wug _fl9r131l _1ogc1pd9 _ltzu131l _1lx21pd9 _d9q91e6v _1rng1e6v _zgyx1e6v",
        __cmplp.hasIssuesPages ? __cmplp.isVisualRefresh ? "_2rko1v12" : "_2rkome6u" : __cmplp.isVisualRefresh ? "_2rko12x7" : "_2rkolb4i",
        __cmplp.isVisualRefresh ? "_14b41ylp" : "_14b41tcg",
        __cmplp.weekViewEnabled ? "_19e21txw" : "_19e21ule",
        __cmplp.weekViewEnabled ? "_rmns1txw" : "_rmns1ule",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    CalendarHeader.displayName = "CalendarHeader";
}
const CalendarHeaderFixture = ({ weekViewEnabled = true })=><CalendarHeader weekViewEnabled={weekViewEnabled} isVisualRefresh>
		header
	</CalendarHeader>;
export default CalendarHeaderFixture;
