/* .tmp-swc-styled-dynamic-cursor-object-1765439423870-f97f7ad411a71.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const Button = forwardRef(({ as: C = "button", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { isFromServerSide: isFromServerSide, isDisabled: isDisabled, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax([
        "",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Button.displayName = "Button";
}
export const Component = ({ isDisabled, isFromServerSide })=>(<Button isDisabled={isDisabled} isFromServerSide={isFromServerSide}>
		Assignee
	</Button>);
