/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { componentWithCondition } from "@atlassian/jira-feature-flagging-utils";
import { easeInOut } from "@atlaskit/motion";
const OuterWrapperOld = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr) => {
	if (__cmplp.innerRef) {
		throw new Error("Please use 'ref' instead of 'innerRef'.");
	}
	const { duration, ...__cmpldp } = __cmplp;
	return (
		<C
			{...__cmpldp}
			style={{
				...__cmpls,
				"--_1gljcou": ix(__cmplp.width),
				"--_7nn7wk": ix(`width ${__cmplp.duration}ms ${easeInOut}`),
			}}
			ref={__cmplr}
			className={ax(["_v5641lsu _1e0c1txw _njlp1rql _1bsb1rkg", __cmplp.className])}
		/>
	);
});
if (process.env.NODE_ENV !== "production") {
	OuterWrapperOld.displayName = "OuterWrapperOld";
}
const OuterWrapperNew = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr) => {
	if (__cmplp.innerRef) {
		throw new Error("Please use 'ref' instead of 'innerRef'.");
	}
	const { duration, ...__cmpldp } = __cmplp;
	return (
		<C
			{...__cmpldp}
			style={{
				...__cmpls,
				"--_1gljcou": ix(__cmplp.width),
				"--_7nn7wk": ix(`width ${__cmplp.duration}ms ${easeInOut}`),
			}}
			ref={__cmplr}
			className={ax([
				"_v5641lsu _1reo15vq _18m915vq _1e0c1txw _njlp1rql _1bsb1rkg",
				__cmplp.className,
			])}
		/>
	);
});
if (process.env.NODE_ENV !== "production") {
	OuterWrapperNew.displayName = "OuterWrapperNew";
}
const OuterWrapper = componentWithCondition(() => true, OuterWrapperNew, OuterWrapperOld);
const InnerWrapper = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr) => {
	if (__cmplp.innerRef) {
		throw new Error("Please use 'ref' instead of 'innerRef'.");
	}
	return (
		<C
			{...__cmplp}
			style={__cmpls}
			ref={__cmplr}
			className={ax(["_1o9zidpf", __cmplp.className])}
		/>
	);
});
if (process.env.NODE_ENV !== "production") {
	InnerWrapper.displayName = "InnerWrapper";
}
export const Component = ({ width, duration }) => (
	<OuterWrapper width={width} duration={duration}>
		<InnerWrapper />
	</OuterWrapper>
);
