/* .tmp-swc-styled-combinator-spacing-1765437473182-8de71721739a9.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import { ax, ix } from "@compiled/react/runtime";
import * as React from 'react';
const Copyable = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Copyable.displayName = "Copyable";
}
export const Component = ()=>(<Copyable>
    <span>details</span>
  </Copyable>);
