/* .tmp-swc-styled-flex-shorthand-1765317766616-3cc60dc4d2134.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const Cell = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "_16jlidpf _1o9zidpf _i0dl1wug",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Cell.displayName = "Cell";
}
export const Component = ()=><Cell>Content</Cell>;
