/* .tmp-swc-styled-margin-multiplier-1764627630791-51b81e1906519.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const marginMultiplier = (hasScrolled, isShadowVisible)=>{
    if (isShadowVisible) return 0;
    if (hasScrolled) return -1;
    return 1;
};
const getMargin = (hasScrolled, isShadowVisible)=>8 * marginMultiplier(hasScrolled, isShadowVisible);
const Wrapper = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { hasScrolled: hasScrolled, leftShadowVisible: leftShadowVisible, rightShadowVisible: rightShadowVisible, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={{
        ...__cmpls,
        "--_150w5uv": ix(`${getMargin(__cmplp.hasScrolled, __cmplp.leftShadowVisible)}px`),
        "--_oytggz": ix(`${getMargin(__cmplp.hasScrolled, __cmplp.rightShadowVisible)}px`)
    }} ref={__cmplr} className={ax([
        "_18u0t6e2 _2hwx1meq _1e0c1txw",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Wrapper.displayName = "Wrapper";
}
export const Component = (props)=><Wrapper {...props}>Content</Wrapper>;
