/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
const gridSize = 8;
const Container = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    hideDropdownLabel,
    ...__cmpldp
  } = __cmplp;
  return <C {...__cmpldp} style={{
    ...__cmpls,
    "--_rmnwww": ix(gridSize * (__cmplp.hideDropdownLabel ? 14 : 17), "px")
  }} ref={__cmplr} className={ax(["", __cmplp.className])} />;
});
if (process.env.NODE_ENV !== 'production') {
  Container.displayName = 'Container';
}
export const Component = ({
  hideDropdownLabel
}) => <Container hideDropdownLabel={hideDropdownLabel} />;
