/* .tmp-swc-styled-arrow-function-static-dynamic-1763696013449-0907e545fbbee.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const gridSize = 8;
const Container = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { hideDropdownLabel: hideDropdownLabel, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={{
        ...__cmpls,
        "--_rmnwww": ix(gridSize * (__cmplp.hideDropdownLabel ? 14 : 17), "px")
    }} ref={__cmplr} className={ax([
        "_1bah1h6o _4cvr1h6o _1e0c1txw _1tke1mlo _1reo15vq _18m915vq",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Container.displayName = "Container";
}
export const Component = ({ hideDropdownLabel })=>(<Container hideDropdownLabel={hideDropdownLabel}/>);
