/* .tmp-swc-styled-dynamic-absolute-position-1765437473893-84470839a1e4d.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const DotStart = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={{
        ...__cmpls,
        "--_bajtf7": ix(`${__cmplp.y}px`),
        "--_172sugn": ix(`${__cmplp.x}px`)
    }} ref={__cmplr} className={ax([
        "",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    DotStart.displayName = "DotStart";
}
const DotEnd = forwardRef(({ as: C = DotStart, style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    DotEnd.displayName = "DotEnd";
}
export const Example = ()=><DotEnd x={10} y={20}/>;
