/* .tmp-swc-main-navigation-system-1765439418154-5040a0f9e0019.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { Fragment } from 'react';
const contentHeightWhenFixed = `calc(100vh - var(--n_bnrM, 0px) - var(--n_tNvM, 0px))`;
const contentInsetBlockStart = `calc(var(--n_bnrM, 0px) + var(--n_tNvM, 0px))`;
const mainElementStyles = {
    root: "",
    containPaint: ""
};
export function Main({ children, testId, id }) {
    return (<Fragment>
			<div id={id} data-layout-slot role="main" data-testid={testId} className={ax([
        mainElementStyles.root
    ])}>
				{children}
			</div>
		</Fragment>);
}
