/* .tmp-swc-main-navigation-system-1765930116400-6e327825412e6.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { Fragment } from 'react';
const contentHeightWhenFixed = `calc(100vh - var(--n_bnrM, 0px) - var(--n_tNvM, 0px))`;
const contentInsetBlockStart = `calc(var(--n_bnrM, 0px) + var(--n_tNvM, 0px))`;
const mainElementStyles = {
    root: "_nd5l1gzg _152timx3 _19121cl4 _1reo1wug _18m91wug _qwfh1wug _165teqxy _13wn1if8",
    containPaint: "_njlp1t7j"
};
export function Main({ children, testId, id }) {
    return (<Fragment>
			<div id={id} data-layout-slot role="main" data-testid={testId} className={ax([
        mainElementStyles.root
    ])}>
				{children}
			</div>
		</Fragment>);
}
