/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
import styled, { css } from 'styled-components';

// Mixed patterns: css2 from @compiled/react and css from styled-components
const referencedObjectsContainerStyles = null;
const maxWidth2 = null;
const plainTextStyles = null;

// Styled component using css template literal
const LozengeLink = styled.a`
	${lozengeStyles};

	&:focus,
	&:hover {
		background-color: #f4f5f7;
		color: #333;
		text-decoration: none;
	}

	&:active {
		background-color: #e4e5ea;
	}
`;
const lozengeStyles = css`
	display: flex;
	align-items: center;
	padding: 2px 6px;
	border-radius: 3px;
	background-color: #f7f8f9;
`;

// Component using @compiled/react jsx and css
const Component = ({
  children,
  forceMaxWidth
}) => <div className={ax([forceMaxWidth && ""])}>
		{children}
	</div>;

// Component using styled-components
const StyledComponent = styled.div`
	${plainTextStyles};
	${props => props.forceMaxWidth && maxWidth2};
`;
export default Component;
