/* .tmp-swc-styled-compiled-mixed-css-array-1764029527010-a86c029fe7c0a.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
import styled, { css } from 'styled-components';
const referencedObjectsContainerStyles = null;
const maxWidth2 = null;
const plainTextStyles = null;
const LozengeLink = styled.a`
	${lozengeStyles};

	&:focus,
	&:hover {
		background-color: #f4f5f7;
		color: #333;
		text-decoration: none;
	}

	&:active {
		background-color: #e4e5ea;
	}
`;
const lozengeStyles = css`
	display: flex;
	align-items: center;
	padding: 2px 6px;
	border-radius: 3px;
	background-color: #f7f8f9;
`;
const Component = ({ children, forceMaxWidth })=>(<div className={ax([
        "_4cvr1h6o _ca0qyh40 _u5f3idpf _n3tdyh40 _19bvidpf _2hwx1y44 _1e0c1txw _bfhk1kw7 _syaz1d6m",
        forceMaxWidth && "_p12fuuw1 _1reo15vq _18m915vq"
    ])}>
		{children}
	</div>);
const StyledComponent = styled.div`
	${plainTextStyles};
	${(props)=>props.forceMaxWidth && maxWidth2};
`;
export default Component;
