/* .tmp-swc-cssmap-class-names-as-css-1765408339758-61bf1f3a826ae.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
const styles = {
    root: ""
};
export function Root({ children, xcss }) {
    return (<div className={ax([
        styles.root
    ])}>
			{children}
		</div>);
}
