/* .tmp-swc-css-array-syntax-1765437464420-262e20bcfa70f.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const base = null;
const padding = null;
export const Component = ()=>(<div className={ax([])}>
    Hello
  </div>);
