/* .tmp-swc-css-array-syntax-1763944826570-f39e225d42de4.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const base = null;
const padding = null;
export const Component = ()=>(<div className={ax([
        "_syazu67f",
        "_ca0q7vkz _u5f37vkz _n3td7vkz _19bv7vkz"
    ])}>
    Hello
  </div>);
