/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
const styles = {
  root: ""
};
export function GridLayout({
  children
}) {
  return <div className={ax([styles.root])}>
			{children}
		</div>;
}
