/* .tmp-swc-cssmap-grid-template-areas-nested-selectors-1764713728077-2cfaa2a841dc7.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
const styles = {
    root: "_1lmcq9em _yv0ei47z _2z0516ab _1e0c11p5 _1tke1kxc _1ciragmp _12fkuz0r _xkmgbaui _12qzrxre _1rqt70if _jbc7rxre _tyve1jg8"
};
export function GridLayout({ children }) {
    return (<div className={ax([
        styles.root
    ])}>
			{children}
		</div>);
}
