/* .tmp-swc-css-null-literal-styles-1763969928892-e19dc57e0cb73.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const CSS_VAR_ICON_COLOR = '--flag-icon-color';
const descriptionStyles = null;
const iconWrapperStyles = null;
const flagWrapperStyles = null;
const Flag = ({ description, testId })=>{
    return (<div role="alert" data-testid={testId} className={ax([
        "_1bsb1osq"
    ])}>
			<div className={ax([
        "_4cvr1h6o _1bah1h6o _1e0c1txw _1ul91tcg _1tke1tcg _1o9zidpf _syaz1jn0"
    ])}>
				Icon
			</div>
			<div className={ax([
        "_11c81lyf _c71l53f4 _1reo1wug _18m91wug _1i4qfg65"
    ])}>
				{description}
			</div>
		</div>);
};
export default Flag;
