/* .tmp-swc-css-null-literal-styles-1765439412342-6ab58e6e04d3c.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const CSS_VAR_ICON_COLOR = '--flag-icon-color';
const descriptionStyles = null;
const iconWrapperStyles = null;
const flagWrapperStyles = null;
const Flag = ({ description, testId })=>{
    return (<div role="alert" data-testid={testId} className={ax([])}>
			<div className={ax([])}>
				Icon
			</div>
			<div className={ax([])}>
				{description}
			</div>
		</div>);
};
export default Flag;
