/* in.tsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
import Textfield from '@atlaskit/textfield';
const textFieldStyle = {
  invalid: "",
  valid: ""
};
type Props = {
  isValid: boolean;
};
export const Example = ({
  isValid
}: Props) => <Textfield className={ax([])} />;
