/* .tmp-swc-number-decoration-range-input-1764627628341-3ed4b88bf5879.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import Textfield from '@atlaskit/textfield';
const textFieldStyle = {
    invalid: "_syaz1tmw",
    valid: "_syaz1fxt"
};
type Props = {
    isValid: boolean;
};
export const Example = ({ isValid }: Props)=><Textfield className={ax([
        isValid ? textFieldStyle.valid : textFieldStyle.invalid
    ])}/>;
