/* .tmp-swc-styled-calc-offset-1765246830732-6df6f8e1aa4df.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
import { LAYOUT_OFFSET } from './layout-offset';
const Container = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "_4t3i1i8v",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Container.displayName = "Container";
}
export const Component = ()=><Container>Content</Container>;
