/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ac, ix } from "@compiled/react/runtime";
import * as React from "react";
export const Component = () => <div className={ac(["_1wyb_a"])} />;
