/* .tmp-swc-class-name-compression-1765317760371-0fc1b7a1b5b07.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ac, ix } from "@compiled/react/runtime";
export const Component = ()=>(<div className={ac([
        "_1wyb_a"
    ])}/>);
