/* .tmp-swc-class-name-compression-1764713725599-f8c60deb18581.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ac, ix } from "@compiled/react/runtime";
export const Component = ()=>(<div className={ac([
        "_1wyb_a"
    ])}/>);
