/* .tmp-swc-class-name-compression-1765408331702-46b80b30cfc99.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ac, ix } from "@compiled/react/runtime";
export const Component = ()=>(<div className={ac([])}/>);
