/* .tmp-swc-class-name-compression-1765437463074-d8dd6e4a8629f.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ac, ix } from "@compiled/react/runtime";
export const Component = ()=>(<div className={ac([])}/>);
