/* .tmp-swc-class-name-compression-1765439408007-6c53402e1465d.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ac, ix } from "@compiled/react/runtime";
export const Component = ()=>(<div className={ac([])}/>);
