/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const underline = {
	"&::after": {
		position: "absolute",
		borderRadius: "1px",
	},
};
const pressed = {
	"&::after": {
		...underline["&::after"],
		backgroundColor: "red",
	},
};
const styles = null;
export const Component = () => (
	<div
		className={ax([
			"_1tfxstnw _ee5ostnw _ixiwstnw _5or0t94y _19v6t94y _qrdit94y _1uf0stnw _174kt94y _gcm15scu",
		])}
	/>
);
