/* .tmp-swc-css-nested-spread-active-after-1765439412181-0e8211e544d28.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const underline = {
    '&::after': {
        position: 'absolute',
        borderRadius: '1px'
    }
};
const pressed = {
    '&::after': {
        ...underline['&::after'],
        backgroundColor: 'red'
    }
};
const styles = null;
export const Component = ()=><div className={ax([])}/>;
