/* .tmp-swc-null-literal-styles-css-prop-1765404346931-e2cd3155b93e6.jsx generated by @compiled/babel-plugin v0.38.1 */
import React from 'react';
const CSS_VAR_ICON_COLOR = '--flag-icon-color';
const descriptionStyles = null;
const iconWrapperStyles = null;
const flagWrapperStyles = null;
const analyticsAttributes = {
    componentName: 'flag',
    packageName: 'test',
    packageVersion: '1.0.0'
};
function Flag({ children }) {
    return (<div css={iconWrapperStyles}>
            <span css={descriptionStyles}>
                {children}
            </span>
        </div>);
}
export default Flag;
