/* .tmp-swc-timeline-cell-no-cc-1765408360062-fe09b3ad5483b.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React, { useCallback, useState } from 'react';
import { Box } from '@atlaskit/primitives/compiled';
const styles = {
    cellWrapper: ""
};
export default function Component({ item }: {
    item: any;
}) {
    const [hover, setHover] = useState(false);
    const onEnter = useCallback(()=>setHover(true), []);
    const onLeave = useCallback(()=>setHover(false), []);
    const onClick = useCallback(()=>console.log(item?.key), [
        item?.key
    ]);
    return <Box xcss={styles.cellWrapper} onMouseEnter={onEnter} onMouseLeave={onLeave}>
      <div onClick={onClick}>{hover ? 'Hover' : 'Idle'}</div>
    </Box>;
}
