/* .tmp-swc-timeline-cell-no-cc-1764733735850-9a65201d9be59.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React, { useCallback, useState } from 'react';
import { Box } from '@atlaskit/primitives/compiled';
const styles = {
    cellWrapper: "_1r04ze3t _u5f3u2gc _19bvu2gc _4cvr1h6o _4t3i1osq _kqswh2mm _1bsb1osq _1e0c1txw _1reo15vq"
};
export default function Component({ item }: {
    item: any;
}) {
    const [hover, setHover] = useState(false);
    const onEnter = useCallback(()=>setHover(true), []);
    const onLeave = useCallback(()=>setHover(false), []);
    const onClick = useCallback(()=>console.log(item?.key), [
        item?.key
    ]);
    return <Box xcss={styles.cellWrapper} onMouseEnter={onEnter} onMouseLeave={onLeave}>
      <div onClick={onClick}>{hover ? 'Hover' : 'Idle'}</div>
    </Box>;
}
