/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
const titleStyles = {
  root: ""
};
const FeatureCard = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["", __cmplp.className])} />;
});
if (process.env.NODE_ENV !== 'production') {
  FeatureCard.displayName = 'FeatureCard';
}
const ButtonContainer = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["", __cmplp.className])} />;
});
if (process.env.NODE_ENV !== 'production') {
  ButtonContainer.displayName = 'ButtonContainer';
}
function FeatureCardView({
  title,
  description
}) {
  return <FeatureCard>
      <div className={ax([titleStyles.root])}>
        <h3>{title}</h3>
      </div>
      <div>{description}</div>
      <ButtonContainer>
        <button>Learn More</button>
      </ButtonContainer>
    </FeatureCard>;
}
export default FeatureCardView;
