/* .tmp-swc-css-tagged-template-literal-1763973271080-afb99c92af9f6.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=><div className={ax([
        "_syazruxl _30l3r3uz"
    ])}>Hello</div>;
