/* .tmp-swc-css-tagged-template-literal-1765439412889-88a505b4edc01.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = null;
export const Component = ()=><div className={ax([])}>Hello</div>;
