/* .tmp-swc-tokens-var-whitespace-1764627632001-a50699431c487.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const Component = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([
        "_19bvutpp _189ee4h9 _1h6dmuej _1mspu2gc",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    Component.displayName = "Component";
}
export const Example = ()=>(<Component>
		<span>Child</span>
	</Component>);
