/* .tmp-swc-styled-component-basic-1764029527075-dd74e79ebaad4.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import { forwardRef } from "react";
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const StyledButton = forwardRef(({ as: C = "button", style: __cmpls, ...__cmplp }, __cmplr)=>{
    if (__cmplp.innerRef) {
        throw new Error("Please use 'ref' instead of 'innerRef'.");
    }
    const { primary: primary, ...__cmpldp } = __cmplp;
    return <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax([
        "_ca0qftgi _u5f37vkz _n3tdftgi _19bv7vkz _19itglyw _2rko1y44 _syazu67f _80omtlke _16l4txnc _1j55105o _j5dh13gf",
        __cmplp.primary ? "_bfhk13q2" : "_bfhk17nt",
        __cmplp.className
    ])}/>;
});
if (process.env.NODE_ENV !== "production") {
    StyledButton.displayName = "StyledButton";
}
export const Component = ({ primary, disabled, children, ...props })=>{
    return (<StyledButton primary={primary} disabled={disabled} {...props}>
      {children}
    </StyledButton>);
};
