/* .tmp-swc-xcss-prop-unused-1765437477879-9e048304d041f.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    root: "",
    inner: ""
};
export function Aside({ children, xcss, label = 'Aside', testId }) {
    return (<aside aria-label={label} data-testid={testId} className={ax([
        styles.root
    ])}>
      <div className={ax([
        styles.inner
    ])}>
        {children}
      </div>
    </aside>);
}
