/* .tmp-swc-xcss-prop-unused-1764358663144-32f1dfad58cac.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    root: "_nd5lns35 _vchhusvi _kqswh2mm _glte25cg _ndwch9n0",
    inner: "_152tckbl _1reo1wug _18m91wug _4t3i1osq _165tk7wh _13wn1if8"
};
export function Aside({ children, xcss, label = 'Aside', testId }) {
    return (<aside aria-label={label} data-testid={testId} className={ax([
        styles.root
    ])}>
      <div className={ax([
        styles.inner
    ])}>
        {children}
      </div>
    </aside>);
}
