/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
const baseStyles = {
  color: 'red'
};
const hoverStyles = {
  '&:hover': {
    color: 'blue'
  }
};
export const Component = ({
  isActive,
  children
}) => {
  return <div className={ax(["_syaz5scu", isActive && "_30l313q2"])}>
			{children}
		</div>;
};
