/* .tmp-swc-css-array-missing-comma-1763963506521-378f7e9c56f71.jsx generated by @compiled/babel-plugin v0.38.1 */
;
const baseStyles = {
    color: 'red'
};
const hoverStyles = {
    '&:hover': {
        color: 'blue'
    }
};
export const Component = ({ isActive, children })=>{
    return (<div className={ax([
        "_syaz5scu",
        isActive && "_30l313q2"
    ])}>
			{children}
		</div>);
};
