/* .tmp-swc-css-array-missing-comma-1765437464342-03021ace363f4.jsx generated by @compiled/babel-plugin v0.38.1 */
;
const baseStyles = {
    color: 'red'
};
const hoverStyles = {
    '&:hover': {
        color: 'blue'
    }
};
export const Component = ({ isActive, children })=>{
    return (<div className={ax([
        isActive && ""
    ])}>
			{children}
		</div>);
};
