/* .tmp-swc-css-map-token-1765408337093-0dfd33c0e6725.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    root: ""
};
export const Component = ()=><div className={styles.root}>Hi</div>;
