/* .tmp-swc-css-map-token-1764020414433-97ffb393215bd.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    root: "_1q511wn3 _85i51wn3"
};
export const Component = ()=><div className={styles.root}>Hi</div>;
