/* .tmp-swc-css-map-atlaskit-1765408336613-76635f379ebce.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    base: ""
};
export const Component = ()=><div className={styles.base}>hello</div>;
