/* .tmp-swc-css-map-nested-1765408336848-18b989c288b9c.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
export const styles = {
    success: "",
    danger: ""
};
