/* .tmp-swc-css-map-nested-1765439411742-2f914a161c983.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
export const styles = {
    success: "",
    danger: ""
};
