/* .tmp-swc-modal-trigger-text-decoration-1765439418751-a0a2fcd93ac1.tsx generated by @compiled/babel-plugin v0.38.1 */
;
import { ax, ix } from "@compiled/react/runtime";
import React from 'react';
import { Pressable, Text } from '@atlaskit/primitives/compiled';
const styles = {
    trigger: ""
};
export const Example = ()=><Pressable xcss={styles.trigger}>
		<Text size="large" weight="bold" color="color.text">
			Trigger content
		</Text>
	</Pressable>;
