/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix } from "@compiled/react/runtime";
import React, { forwardRef } from 'react';
const baseStyles = {
  boxSizing: 'border-box',
  appearance: 'none',
  border: 'none'
};

// Massive background color map (simplified from the original 100+ entries)
const backgroundColorMap = {
  'color.background.accent.lime.subtlest': "",
  'color.background.accent.lime.subtler': ""
};

// CSS variables using unboundedCssMap
const CURRENT_SURFACE_CSS_VAR = '--ds-elevation-surface-current';
const setSurfaceTokenMap = {
  'elevation.surface': "",
  'elevation.surface.raised': ""
};

// Multiple padding maps
const paddingBlockStartMap = {
  'space.0': "",
  'space.100': "",
  'space.200': "",
  'space.300': ""
};
const paddingInlineStartMap = {
  'space.0': "",
  'space.100': "",
  'space.200': "",
  'space.300': ""
};

/**
 * __Box__
 *
 * A Box primitive component with massive cssMap configurations
 */
const Box = forwardRef((props, ref) => {
  const {
    as: Component = 'div',
    children,
    backgroundColor,
    paddingBlockStart,
    paddingInlineStart,
    style,
    testId,
    xcss,
    ...htmlAttributes
  } = props;
  const {
    className: _spreadClass,
    ...safeHtmlAttributes
  } = htmlAttributes;
  const isSurfaceToken = bg => bg in setSurfaceTokenMap;
  return <Component style={style} ref={ref} className={`
				${xcss || ''}
				${Object.keys(baseStyles).map(key => `${key}: ${baseStyles[key]}`).join('; ')}
				${backgroundColor ? backgroundColorMap[backgroundColor]() : ''}
				${backgroundColor && isSurfaceToken(backgroundColor) ? setSurfaceTokenMap[backgroundColor]() : ''}
				${paddingBlockStart ? paddingBlockStartMap[paddingBlockStart]() : ''}
				${paddingInlineStart ? paddingInlineStartMap[paddingInlineStart]() : ''}
			`.trim()} {...safeHtmlAttributes} data-testid={testId}>
      {children}
    </Component>;
});
Box.displayName = 'Box';
export default Box;
