/* .tmp-swc-css-map-pseudo-1765437465861-4ba3d180edc54.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    base: ""
};
export const Component = ()=><div className={ax([
        styles.base
    ])}>pseudo</div>;
