/* .tmp-swc-css-map-pseudo-1764625072151-a80b2b28b0d3e.jsx generated by @compiled/babel-plugin v0.38.1 */
;
import * as React from "react";
import { ax, ix } from "@compiled/react/runtime";
const styles = {
    base: "_19pkftgi _2hwxftgi _otyrftgi _18u0ftgi _kqswh2mm _1kt9b3bt _1cs8stnw _1mp41osq _kfgt1osq _jk43mw0c"
};
export const Component = ()=><div className={ax([
        styles.base
    ])}>pseudo</div>;
